# DODO was here
# DODO added #32839638
"""empty message

Revision ID: 2c0fc74666e7
Revises: dbe6e308abc8
Create Date: 2023-11-01 05:00:00.000000

"""

# revision identifiers, used by Alembic.
revision = "2c0fc74666e7"
down_revision = "dbe6e308abc8"

import sqlalchemy as sa  # noqa: E402
from alembic import op  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_external", sa.Boolean(), nullable=False),
        sa.Column("slug", sa.String(), unique=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["ab_role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["ab_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_users")
    op.drop_table("team_roles")
    op.drop_table("teams")
    # ### end Alembic commands ###
