# DODO was here
"""empty message

Revision ID: 3c0ff4a543a6
Revises: 7048393c1cd7
Create Date: 2023-11-01 07:00:00.000000

"""

# revision identifiers, used by Alembic.
revision = "3c0ff4a543a6"
down_revision = "7048393c1cd7"

import sqlalchemy as sa  # noqa: E402
from alembic import op  # noqa: E402
from sqlalchemy.dialects import mysql  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_info",
        sa.Column(
            "data_auth_dodo",
            sa.Text().with_variant(mysql.MEDIUMTEXT(), "mysql"),
            nullable=True,
        ),
    )
    op.add_column("user_info", sa.Column("country_num", sa.Integer(), nullable=True))
    op.add_column("user_info", sa.Column("country_name", sa.String(), nullable=True))
    op.add_column("logs", sa.Column("is_plugin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_info", "country_name")
    op.drop_column("user_info", "country_num")
    op.drop_column("user_info", "data_auth_dodo")
    op.drop_column("logs", "is_plugin")
    # ### end Alembic commands ###
