# DODO was here
"""required fields for multilingualism

Revision ID: 168cfd974dd1
Revises: 4b85906e5b91
Create Date: 2023-11-01 00:00:00.000000

"""

# revision identifiers, used by Alembic.
revision = "168cfd974dd1"
down_revision = "4b85906e5b91"

import sqlalchemy as sa  # noqa: E402
from alembic import op  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dashboards", sa.Column("selected_lang", sa.Text(), nullable=True))
    op.add_column(
        "dashboards", sa.Column("dashboard_title_second_lang", sa.Text(), nullable=True)
    )

    op.add_column("slices", sa.Column("extra_lang", sa.Text(), nullable=True))
    op.add_column(
        "slices", sa.Column("slice_name_second_lang", sa.Text(), nullable=True)
    )
    op.add_column("slices", sa.Column("primary_lang", sa.Text(), nullable=True))

    op.add_column(
        "sql_metrics", sa.Column("verbose_name_second_lang", sa.Text(), nullable=True)
    )
    op.add_column(
        "sql_metrics", sa.Column("description_second_lang", sa.Text(), nullable=True)
    )

    op.add_column(
        "table_columns", sa.Column("verbose_name_second_lang", sa.Text(), nullable=True)
    )
    op.add_column(
        "table_columns", sa.Column("description_second_lang", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("table_columns", "description_second_lang")
    op.drop_column("table_columns", "verbose_name_second_lang")

    op.drop_column("sql_metrics", "description_second_lang")
    op.drop_column("sql_metrics", "verbose_name_second_lang")

    op.drop_column("slices", "primary_lang")
    op.drop_column("slices", "slice_name_second_lang")
    op.drop_column("slices", "extra_lang")

    op.drop_column("dashboards", "dashboard_title_second_lang")
    op.drop_column("dashboards", "selected_lang")
    # ### end Alembic commands ###
