# DODO was here
"""empty message

Revision ID: a18f4c261e8b
Revises: 049632555b84
Create Date: 2023-11-01 02:00:00.000000

"""

# revision identifiers, used by Alembic.
revision = "a18f4c261e8b"
down_revision = "049632555b84"

import sqlalchemy as sa  # noqa: E402
from alembic import op  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sql_metrics", sa.Column("verbose_name_en", sa.Text(), nullable=True))
    op.add_column("sql_metrics", sa.Column("description_en", sa.Text(), nullable=True))

    op.add_column(
        "table_columns", sa.Column("verbose_name_en", sa.Text(), nullable=True)
    )
    op.add_column(
        "table_columns", sa.Column("description_en", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("table_columns", "description_en")
    op.drop_column("table_columns", "verbose_name_en")

    op.drop_column("sql_metrics", "description_en")
    op.drop_column("sql_metrics", "verbose_name_en")
    # ### end Alembic commands ###
