# DODO was here
"""empty message

Revision ID: f42525e2bb55
Revises: 3c0ff4a543a6
Create Date: 2023-11-01 08:00:00.000000

"""

# revision identifiers, used by Alembic.
revision = "f42525e2bb55"
down_revision = "3c0ff4a543a6"

import sqlalchemy as sa  # noqa: E402
from alembic import op  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sql_metrics", sa.Column("number_format", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sql_metrics", "number_format")
    # ### end Alembic commands ###
