# DODO was here
"""empty message
Revision ID: 24505e69a987
Revises: 864745c0a17d
Create Date: 2025-01-27 17:25:12.629299
"""

# revision identifiers, used by Alembic.
revision = "24505e69a987"
down_revision = "864745c0a17d"

from alembic import op  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key("embedded_dashboards_uuid", "embedded_dashboards", ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "embedded_dashboards_uuid", "embedded_dashboards", type_="primary"
    )
    # ### end Alembic commands ###
