"""empty message

Revision ID: 626ad9f93c09
Revises: ac2f436df15d
Create Date: 2018-11-26 13:35:07.913759

"""

# revision identifiers, used by Alembic.
revision = '626ad9f93c09'
down_revision = 'ac2f436df15d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'description')
    # ### end Alembic commands ###
