"""csv_upload_schema_control_column

Revision ID: 65b2eefd8247
Revises: 1a1d627ebd8e
Create Date: 2018-08-30 12:28:08.639614

"""

# revision identifiers, used by Alembic.
revision = '65b2eefd8247'
down_revision = '1a1d627ebd8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbs', sa.Column('schema_access_for_csv_upload', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbs', 'schema_access_for_csv_upload')
    # ### end Alembic commands ###
