"""support for lookup extraction filters and queries

Revision ID: 6871eee11243
Revises: a61b40f9f57f
Create Date: 2019-03-14 09:38:57.787087

"""

# revision identifiers, used by Alembic.
revision = '6871eee11243'
down_revision = 'a61b40f9f57f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clusters', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('clusters', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_unique_constraint(None, 'clusters', ['verbose_name'])
    op.alter_column('columns', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('columns', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('css_templates', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('css_templates', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('dashboards', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('dashboards', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_unique_constraint(None, 'dashboards', ['slug'])
    op.alter_column('datasources', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('datasources', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('dbs', 'allow_csv_upload',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('dbs', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('dbs', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_unique_constraint(None, 'dbs', ['verbose_name'])
    op.create_foreign_key(None, 'metrics', 'ab_user', ['changed_by_fk'], ['id'])
    op.create_foreign_key(None, 'metrics', 'ab_user', ['created_by_fk'], ['id'])
    op.alter_column('slices', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('slices', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('sql_metrics', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('sql_metrics', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_unique_constraint(None, 'sql_metrics', ['table_id', 'metric_name'])
    op.alter_column('table_columns', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('table_columns', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_unique_constraint(None, 'table_columns', ['table_id', 'column_name'])
    op.alter_column('tables', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('tables', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_unique_constraint(None, 'tables', ['database_id', 'table_name'])
    op.alter_column('url', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('url', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('url', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'tables', type_='unique')
    op.alter_column('tables', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('tables', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'table_columns', type_='unique')
    op.alter_column('table_columns', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('table_columns', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'sql_metrics', type_='unique')
    op.alter_column('sql_metrics', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('sql_metrics', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('slices', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('slices', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_constraint(None, 'dbs', type_='unique')
    op.alter_column('dbs', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('dbs', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('dbs', 'allow_csv_upload',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('datasources', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('datasources', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'dashboards', type_='unique')
    op.alter_column('dashboards', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('dashboards', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('css_templates', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('css_templates', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('columns', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('columns', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'clusters', type_='unique')
    op.alter_column('clusters', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('clusters', 'changed_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
