# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Custom fields for email reports

Revision ID: 721b47faf907
Revises: 6c7537a6004a
Create Date: 2018-12-11 22:37:40.542630

"""

# revision identifiers, used by Alembic.
revision = '721b47faf907'
down_revision = 'c82ee8a39623'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_email_schedules', sa.Column('email_subject', sa.String(length=80), nullable=True))
    op.add_column('dashboard_email_schedules', sa.Column('screen_height', sa.Integer(), nullable=True))
    op.add_column('dashboard_email_schedules', sa.Column('screen_width', sa.Integer(), nullable=True))
    op.add_column('slice_email_schedules', sa.Column('email_subject', sa.String(length=80), nullable=True))
    op.add_column('slice_email_schedules', sa.Column('screen_height', sa.Integer(), nullable=True))
    op.add_column('slice_email_schedules', sa.Column('screen_width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slice_email_schedules', 'screen_width')
    op.drop_column('slice_email_schedules', 'screen_height')
    op.drop_column('slice_email_schedules', 'email_subject')
    op.drop_column('dashboard_email_schedules', 'screen_width')
    op.drop_column('dashboard_email_schedules', 'screen_height')
    op.drop_column('dashboard_email_schedules', 'email_subject')
    # ### end Alembic commands ###
