"""add tags column to alerts

Revision ID: 8a93343c3445
Revises: ba851a9416c5
Create Date: 2018-11-07 15:18:37.691184

"""

# revision identifiers, used by Alembic.
revision = '8a93343c3445'
down_revision = 'ba851a9416c5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('tags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'tags')
    # ### end Alembic commands ###
