"""empty message

Revision ID: ac2f436df15d
Revises: 8a93343c3445
Create Date: 2018-11-26 13:08:55.166078

"""

# revision identifiers, used by Alembic.
revision = 'ac2f436df15d'
down_revision = '8a93343c3445'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('changed_by_fk', sa.Integer(), nullable=True))
    op.add_column('alert', sa.Column('changed_on', sa.DateTime(), nullable=True))
    op.add_column('alert', sa.Column('created_by_fk', sa.Integer(), nullable=True))
    op.add_column('alert', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'alert', 'ab_user', ['created_by_fk'], ['id'])
    op.create_foreign_key(None, 'alert', 'ab_user', ['changed_by_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'created_on')
    op.drop_column('alert', 'created_by_fk')
    op.drop_column('alert', 'changed_on')
    op.drop_column('alert', 'changed_by_fk')
    ### end Alembic commands ###
