"""empty message

Revision ID: c5e6fada92be
Revises:
Create Date: 2018-08-09 18:20:50.952435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5e6fada92be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_slices_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dashboard_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('slice_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_dashboard_slices_version_end_transaction_id'), 'dashboard_slices_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_dashboard_slices_version_operation_type'), 'dashboard_slices_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_dashboard_slices_version_transaction_id'), 'dashboard_slices_version', ['transaction_id'], unique=False)
    op.create_table('slice_user_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('slice_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_slice_user_version_end_transaction_id'), 'slice_user_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_slice_user_version_operation_type'), 'slice_user_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_slice_user_version_transaction_id'), 'slice_user_version', ['transaction_id'], unique=False)
    op.create_table('slices_version',
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('changed_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('slice_name', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('datasource_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('datasource_type', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('datasource_name', sa.String(length=2000), autoincrement=False, nullable=True),
    sa.Column('viz_type', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('params', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('cache_timeout', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('perm', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_by_fk', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_slices_version_end_transaction_id'), 'slices_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_slices_version_operation_type'), 'slices_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_slices_version_transaction_id'), 'slices_version', ['transaction_id'], unique=False)
    op.create_table('tables_version',
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('changed_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('default_endpoint', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('filter_select_enabled', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('offset', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('cache_timeout', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('params', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('perm', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('main_dttm_col', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('database_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('fetch_values_predicate', sa.String(length=1000), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('schema', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('sql', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('is_sqllab_view', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('template_params', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_by_fk', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_tables_version_end_transaction_id'), 'tables_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_tables_version_operation_type'), 'tables_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_tables_version_transaction_id'), 'tables_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_tables_version_transaction_id'), table_name='tables_version')
    op.drop_index(op.f('ix_tables_version_operation_type'), table_name='tables_version')
    op.drop_index(op.f('ix_tables_version_end_transaction_id'), table_name='tables_version')
    op.drop_table('tables_version')
    op.drop_index(op.f('ix_slices_version_transaction_id'), table_name='slices_version')
    op.drop_index(op.f('ix_slices_version_operation_type'), table_name='slices_version')
    op.drop_index(op.f('ix_slices_version_end_transaction_id'), table_name='slices_version')
    op.drop_table('slices_version')
    op.drop_index(op.f('ix_slice_user_version_transaction_id'), table_name='slice_user_version')
    op.drop_index(op.f('ix_slice_user_version_operation_type'), table_name='slice_user_version')
    op.drop_index(op.f('ix_slice_user_version_end_transaction_id'), table_name='slice_user_version')
    op.drop_table('slice_user_version')
    op.drop_index(op.f('ix_dashboard_slices_version_transaction_id'), table_name='dashboard_slices_version')
    op.drop_index(op.f('ix_dashboard_slices_version_operation_type'), table_name='dashboard_slices_version')
    op.drop_index(op.f('ix_dashboard_slices_version_end_transaction_id'), table_name='dashboard_slices_version')
    op.drop_table('dashboard_slices_version')
    # ### end Alembic commands ###
