# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""refractor_alerting_framework

Revision ID: c85b68800a5c
Revises: f2672aa8350a
Create Date: 2020-08-14 11:03:38.431388

"""

# revision identifiers, used by Alembic.
revision = "c85b68800a5c"
down_revision = "f2672aa8350a"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deviation_alert_validators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=True),
        sa.Column(
            "validation_type",
            sa.Enum("numerical", name="alertvalidationtype"),
            nullable=True,
        ),
        sa.Column("deviation_difference", sa.Float(), nullable=True),
        sa.Column("deviation_threshold", sa.Integer(), nullable=True),
        sa.Column("range_min", sa.Integer(), nullable=True),
        sa.Column("range_max", sa.Integer(), nullable=True),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "not_null_alert_validators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=True),
        sa.Column(
            "validation_type",
            sa.Enum("numerical", name="alertvalidationtype"),
            nullable=True,
        ),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sql_alert_observers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=True),
        sa.Column(
            "validation_type",
            sa.Enum("numerical", name="alertvalidationtype"),
            nullable=True,
        ),
        sa.Column("sql", sa.Text(), nullable=True),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("database_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"],),
        sa.ForeignKeyConstraint(["database_id"], ["dbs.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sql_alert_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dttm_ts", sa.DateTime(), nullable=True),
        sa.Column("observer_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["observer_id"], ["sql_alert_observers.id"],),
        sa.PrimaryKeyConstraint("id"),
    )

    op.drop_column("alerts", "sql")
    op.drop_column("alerts", "database_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alerts",
        sa.Column("database_id", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column("alerts", sa.Column("sql", mysql.TEXT(), nullable=True))

    op.drop_table("sql_alert_observations")
    op.drop_table("sql_alert_observers")
    op.drop_table("not_null_alert_validators")
    op.drop_table("deviation_alert_validators")
    # ### end Alembic commands ###
