"""add one more constraint

Revision ID: d6a223d2332a
Revises: 55e910a74826
Create Date: 2018-09-19 16:51:55.900887

"""

# revision identifiers, used by Alembic.
revision = 'd6a223d2332a'
down_revision = '55e910a74826'

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tables', ['database_id', 'schema', 'table_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='unique')
    # ### end Alembic commands ###
