"""empty message

Revision ID: e201cd43a98f
Revises: 3ba5164aa5dc
Create Date: 2018-12-13 18:25:56.553826

"""

# revision identifiers, used by Alembic.
revision = 'e201cd43a98f'
down_revision = '3ba5164aa5dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('deployment', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'deployment')
    # ### end Alembic commands ###
