/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

export const basic = [
  {
    source: '05/18/21 Live Demo',
    target: '05/04/21 Live Demo',
    value: 100,
    sourceCategory: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '05/04/21 Live Demo',
    target: '04/20/21 Live Demo',
    value: 110,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '05/04/21 Live Demo',
    target: '04/13/21 Live Demo',
    value: 40,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '05/04/21 Live Demo',
    target: '04/06/21 Live Demo',
    value: 30,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '05/04/21 Live Demo',
    target: '09/29/21 Live Demo',
    value: 25,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '05/04/21 Live Demo',
    target: '06/01/21 Live Demo',
    value: 43,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '04/20/21 Live Demo',
    target: '04/13/21 Live Demo',
    value: 50,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '04/20/21 Live Demo',
    target: '03/02/21 Meetup',
    value: 40,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
  {
    source: '04/20/21 Live Demo',
    target: '06/01/21 Live Demo',
    value: 58,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '04/20/21 Live Demo',
    target: '03/25/21 Meetup',
    value: 38,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
  {
    source: '04/20/21 Live Demo',
    target: '01/28/21 Meetup',
    value: 34,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
  {
    source: '04/13/21 Live Demo',
    target: '04/06/21 Live Demo',
    value: 34,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '04/13/21 Live Demo',
    target: '09/29/21 Live Demo',
    value: 56,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '04/06/21 Live Demo',
    target: '09/29/21 Live Demo',
    value: 77,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '04/13/21 Live Demo',
    target: '03/02/21 Meetup',
    value: 36,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
  {
    source: '04/13/21 Live Demo',
    target: '06/08/21 Live Demo',
    value: 77,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '09/29/21 Live Demo',
    target: '06/01/21 Live Demo',
    value: 44,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '09/29/21 Live Demo',
    target: '06/08/21 Live Demo',
    value: 30,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '06/01/21 Live Demo',
    target: '03/02/21 Meetup',
    value: 67,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
  {
    source: '06/01/21 Live Demo',
    target: '03/25/21 Meetup',
    value: 30,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
  {
    source: '06/01/21 Live Demo',
    target: '05/11/21 Meetup',
    value: 52,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
  {
    source: '06/01/21 Live Demo',
    target: '06/08/21 Live Demo',
    value: 43,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '06/01/21 Live Demo',
    target: '01/28/21 Meetup',
    value: 45,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
  {
    source: '06/01/21 Live Demo',
    target: '05/04/21 Live Demo',
    value: 42,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '06/01/21 Live Demo',
    target: '03/25/21 Meetup',
    value: 32,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
  {
    source: '03/02/21 Meetup',
    target: '03/25/21 Meetup',
    value: 23,
    category: 'Meetup',
    targetCategory: 'Meetup',
  },
  {
    source: '03/02/21 Meetup',
    target: '05/11/21 Meetup',
    value: 43,
    category: 'Meetup',
    targetCategory: 'Meetup',
  },
  {
    source: '03/02/21 Meetup',
    target: '01/28/21 Meetup',
    value: 33,
    category: 'Meetup',
    targetCategory: 'Meetup',
  },
  {
    source: '03/02/21 Meetup',
    target: '05/04/21 Live Demo',
    value: 53,
    category: 'Meetup',
    targetCategory: 'Live Demo',
  },
  {
    source: '03/02/21 Meetup',
    target: '03/25/21 Meetup',
    value: 55,
    category: 'Meetup',
    targetCategory: 'Meetup',
  },
  {
    source: '03/25/21 Meetup',
    target: '05/11/21 Meetup',
    value: 33,
    category: 'Meetup',
    targetCategory: 'Meetup',
  },
  {
    source: '03/25/21 Meetup',
    target: '06/08/21 Live Demo',
    value: 73,
    category: 'Meetup',
    targetCategory: 'Live Demo',
  },
  {
    source: '03/25/21 Meetup',
    target: '01/28/21 Meetup',
    value: 63,
    category: 'Meetup',
    targetCategory: 'Meetup',
  },
  {
    source: '03/25/21 Meetup',
    target: '05/04/21 Live Demo',
    value: 52,
    category: 'Meetup',
    targetCategory: 'Live Demo',
  },
  {
    source: '03/25/21 Meetup',
    target: '03/25/21 Meetup',
    value: 51,
    category: 'Meetup',
    targetCategory: 'Meetup',
  },
  {
    source: '05/11/21 Meetup',
    target: '06/08/21 Live Demo',
    value: 35,
    category: 'Meetup',
    targetCategory: 'Live Demo',
  },
  {
    source: '05/11/21 Meetup',
    target: '05/04/21 Live Demo',
    value: 75,
    category: 'Meetup',
    targetCategory: 'Live Demo',
  },
  {
    source: '05/11/21 Meetup',
    target: '01/28/21 Meetup',
    value: 65,
    category: 'Meetup',
    targetCategory: 'Meetup',
  },
  {
    source: '06/08/21 Live Demo',
    target: '01/28/21 Meetup',
    value: 36,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
  {
    source: '06/08/21 Live Demo',
    target: '05/04/21 Live Demo',
    value: 46,
    category: 'Live Demo',
    targetCategory: 'Live Demo',
  },
  {
    source: '06/08/21 Live Demo',
    target: '03/25/21 Meetup',
    value: 26,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
  {
    source: '03/25/21 Meetup',
    target: '05/04/21 Live Demo',
    value: 78,
    category: 'Meetup',
    targetCategory: 'Live Demo',
  },
  {
    source: '03/25/21 Meetup',
    target: '03/25/21 Meetup',
    value: 45,
    category: 'Meetup',
    targetCategory: 'Meetup',
  },
  {
    source: '05/18/21 Live Demo',
    target: '03/25/21 Meetup',
    value: 65,
    category: 'Live Demo',
    targetCategory: 'Meetup',
  },
];
