# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""Boundary identifiers generated from the country-map plugin GeoJSON.

Keep in sync using the geometry parity test; these are rendered identifiers,
not a substitute for a geocoding service or a complete ISO registry.
"""

REGIONS: dict[str, list[tuple[str, str]]] = {
    "australia": [
        ("AU-ACT", "Australian Capital Territory"),
        ("AU-NSW", "New South Wales"),
        ("AU-NT", "Northern Territory"),
        ("AU-QLD", "Queensland"),
        ("AU-SA", "South Australia"),
        ("AU-TAS", "Tasmania"),
        ("AU-VIC", "Victoria"),
        ("AU-WA", "Western Australia"),
        ("AU-X02~", "Jervis Bay Territory"),
    ],
    "canada": [
        ("CA-AB", "Alberta"),
        ("CA-BC", "British Columbia"),
        ("CA-MB", "Manitoba"),
        ("CA-NB", "New Brunswick"),
        ("CA-NL", "Newfoundland and Labrador"),
        ("CA-NS", "Nova Scotia"),
        ("CA-NT", "Northwest Territories"),
        ("CA-NU", "Nunavut"),
        ("CA-ON", "Ontario"),
        ("CA-PE", "Prince Edward Island"),
        ("CA-QC", "Québec"),
        ("CA-SK", "Saskatchewan"),
        ("CA-YT", "Yukon"),
    ],
    "japan": [
        ("JP-01", "Hokkaidō"),
        ("JP-02", "Aomori"),
        ("JP-03", "Iwate"),
        ("JP-04", "Miyagi"),
        ("JP-05", "Akita"),
        ("JP-06", "Yamagata"),
        ("JP-07", "Fukushima"),
        ("JP-08", "Ibaraki"),
        ("JP-09", "Tochigi"),
        ("JP-10", "Gunma"),
        ("JP-11", "Saitama"),
        ("JP-12", "Chiba"),
        ("JP-13", "Tokyo"),
        ("JP-14", "Kanagawa"),
        ("JP-15", "Niigata"),
        ("JP-16", "Toyama"),
        ("JP-17", "Ishikawa"),
        ("JP-18", "Fukui"),
        ("JP-19", "Yamanashi"),
        ("JP-20", "Nagano"),
        ("JP-21", "Gifu"),
        ("JP-22", "Shizuoka"),
        ("JP-23", "Aichi"),
        ("JP-24", "Mie"),
        ("JP-25", "Shiga"),
        ("JP-26", "Kyōto"),
        ("JP-27", "Ōsaka"),
        ("JP-28", "Hyōgo"),
        ("JP-29", "Nara"),
        ("JP-30", "Wakayama"),
        ("JP-31", "Tottori"),
        ("JP-32", "Shimane"),
        ("JP-33", "Okayama"),
        ("JP-34", "Hiroshima"),
        ("JP-35", "Yamaguchi"),
        ("JP-36", "Tokushima"),
        ("JP-37", "Kagawa"),
        ("JP-38", "Ehime"),
        ("JP-39", "Kōchi"),
        ("JP-40", "Fukuoka"),
        ("JP-41", "Saga"),
        ("JP-42", "Nagasaki"),
        ("JP-43", "Kumamoto"),
        ("JP-44", "Ōita"),
        ("JP-45", "Miyazaki"),
        ("JP-46", "Kagoshima"),
        ("JP-47", "Okinawa"),
    ],
    "uk": [
        ("GB-ABD", "Aberdeenshire"),
        ("GB-ABE", "Aberdeen"),
        ("GB-AGB", "Argyll and Bute"),
        ("GB-AGY", "Anglesey"),
        ("GB-ANS", "Angus"),
        ("GB-ANT", "Antrim"),
        ("GB-ARD", "Ards"),
        ("GB-ARM", "Armagh"),
        ("GB-BAS", "Bath and North East Somerset"),
        ("GB-BBD", "Blackburn with Darwen"),
        ("GB-BDF", "Bedford"),
        ("GB-BDG", "Barking and Dagenham"),
        ("GB-BEN", "Brent"),
        ("GB-BEX", "Bexley"),
        ("GB-BFS", "Belfast"),
        ("GB-BGE", "Bridgend"),
        ("GB-BGW", "Blaenau Gwent"),
        ("GB-BIR", "Birmingham"),
        ("GB-BKM", "Buckinghamshire"),
        ("GB-BLA", "Ballymena"),
        ("GB-BLY", "Ballymoney"),
        ("GB-BMH", "Bournemouth"),
        ("GB-BNB", "Banbridge"),
        ("GB-BNE", "Barnet"),
        ("GB-BNH", "Brighton and Hove"),
        ("GB-BNS", "Barnsley"),
        ("GB-BOL", "Bolton"),
        ("GB-BPL", "Blackpool"),
        ("GB-BRC", "Bracknell Forest"),
        ("GB-BRD", "Bradford"),
        ("GB-BRY", "Bromley"),
        ("GB-BST", "Bristol"),
        ("GB-BUR", "Bury"),
        ("GB-CAM", "Cambridgeshire"),
        ("GB-CAY", "Caerphilly"),
        ("GB-CBF", "Central Bedfordshire"),
        ("GB-CGN", "Ceredigion"),
        ("GB-CGV", "Craigavon"),
        ("GB-CHE", "Cheshire East"),
        ("GB-CHW", "Cheshire West and Chester"),
        ("GB-CKF", "Carrickfergus"),
        ("GB-CKT", "Mid Ulster"),
        ("GB-CLD", "Calderdale"),
        ("GB-CLK", "Clackmannanshire"),
        ("GB-CLR", "Coleraine"),
        ("GB-CMA", "Cumbria"),
        ("GB-CMD", "Camden"),
        ("GB-CMN", "Carmarthenshire"),
        ("GB-CON", "Cornwall"),
        ("GB-COV", "Coventry"),
        ("GB-CRF", "Cardiff"),
        ("GB-CRY", "Croydon"),
        ("GB-CSR", "Castlereagh"),
        ("GB-CWY", "Conwy"),
        ("GB-DAL", "Darlington"),
        ("GB-DBY", "Derbyshire"),
        ("GB-DEN", "Denbighshire"),
        ("GB-DER", "Derby"),
        ("GB-DEV", "Devon"),
        ("GB-DGN", "Dungannon"),
        ("GB-DGY", "Dumfries and Galloway"),
        ("GB-DNC", "Doncaster"),
        ("GB-DND", "Dundee"),
        ("GB-DOR", "Dorset"),
        ("GB-DOW", "Down"),
        ("GB-DRY", "Derry"),
        ("GB-DUD", "Dudley"),
        ("GB-DUR", "Durham"),
        ("GB-EAL", "Ealing"),
        ("GB-EAY", "East Ayrshire"),
        ("GB-EDH", "Edinburgh"),
        ("GB-EDU", "East Dunbartonshire"),
        ("GB-ELN", "East Lothian"),
        ("GB-ENF", "Enfield"),
        ("GB-ERW", "East Renfrewshire"),
        ("GB-ERY", "East Riding of Yorkshire"),
        ("GB-ESS", "Essex"),
        ("GB-ESX", "East Sussex"),
        ("GB-FAL", "Falkirk"),
        ("GB-FER", "Fermanagh"),
        ("GB-FIF", "Fife"),
        ("GB-FLN", "Flintshire"),
        ("GB-GAT", "Gateshead"),
        ("GB-GLG", "Glasgow"),
        ("GB-GLS", "Gloucestershire"),
        ("GB-GRE", "Greenwich"),
        ("GB-GWN", "Gwynedd"),
        ("GB-HAL", "Halton"),
        ("GB-HAM", "Hampshire"),
        ("GB-HAV", "Havering"),
        ("GB-HCK", "Hackney"),
        ("GB-HEF", "Herefordshire"),
        ("GB-HIL", "Hillingdon"),
        ("GB-HLD", "Highland"),
        ("GB-HMF", "Hammersmith and Fulham"),
        ("GB-HNS", "Hounslow"),
        ("GB-HPL", "Hartlepool"),
        ("GB-HRT", "Hertfordshire"),
        ("GB-HRW", "Harrow"),
        ("GB-HRY", "Haringey"),
        ("GB-IOS", "Isles of Scilly"),
        ("GB-IOW", "Isle of Wight"),
        ("GB-ISL", "Islington"),
        ("GB-IVC", "Inverclyde"),
        ("GB-KEC", "Kensington and Chelsea"),
        ("GB-KEN", "Kent"),
        ("GB-KHL", "Kingston upon Hull"),
        ("GB-KIR", "Kirklees"),
        ("GB-KTT", "Kingston upon Thames"),
        ("GB-KWL", "Knowsley"),
        ("GB-LAN", "Lancashire"),
        ("GB-LBH", "Lambeth"),
        ("GB-LCE", "Leicester"),
        ("GB-LDS", "Leeds"),
        ("GB-LEC", "Leicestershire"),
        ("GB-LEW", "Lewisham"),
        ("GB-LIN", "Lincolnshire"),
        ("GB-LIV", "Liverpool"),
        ("GB-LMV", "Limavady"),
        ("GB-LND", "City"),
        ("GB-LRN", "Larne"),
        ("GB-LSB", "Lisburn"),
        ("GB-LUT", "Luton"),
        ("GB-MAN", "Manchester"),
        ("GB-MDB", "Middlesbrough"),
        ("GB-MDW", "Medway"),
        ("GB-MFT", "Magherafelt"),
        ("GB-MIK", "Milton Keynes"),
        ("GB-MLN", "Midlothian"),
        ("GB-MON", "Monmouthshire"),
        ("GB-MRT", "Merton"),
        ("GB-MRY", "Moray"),
        ("GB-MTY", "Merthyr Tydfil"),
        ("GB-MYL", "Moyle"),
        ("GB-NAY", "North Ayshire"),
        ("GB-NBL", "Northumberland"),
        ("GB-NDN", "North Down"),
        ("GB-NEL", "North East Lincolnshire"),
        ("GB-NET", "Newcastle upon Tyne"),
        ("GB-NFK", "Norfolk"),
        ("GB-NGM", "Nottingham"),
        ("GB-NLK", "North Lanarkshire"),
        ("GB-NLN", "North Lincolnshire"),
        ("GB-NSM", "North Somerset"),
        ("GB-NTA", "Newtownabbey"),
        ("GB-NTH", "Northamptonshire"),
        ("GB-NTL", "Neath Port Talbot"),
        ("GB-NTT", "Nottinghamshire"),
        ("GB-NTY", "North Tyneside"),
        ("GB-NWM", "Newham"),
        ("GB-NWP", "Newport"),
        ("GB-NYK", "North Yorkshire"),
        ("GB-NYM", "Newry and Mourne"),
        ("GB-OLD", "Oldham"),
        ("GB-OMH", "Omagh"),
        ("GB-ORK", "Orkney"),
        ("GB-OXF", "Oxfordshire"),
        ("GB-PEM", "Pembrokeshire"),
        ("GB-PKN", "Perthshire and Kinross"),
        ("GB-PLY", "Plymouth"),
        ("GB-POL", "Poole"),
        ("GB-POR", "Portsmouth"),
        ("GB-POW", "Powys"),
        ("GB-PTE", "Peterborough"),
        ("GB-RCC", "Redcar and Cleveland"),
        ("GB-RCH", "Rochdale"),
        ("GB-RCT", "Rhondda, Cynon, Taff"),
        ("GB-RDB", "Redbridge"),
        ("GB-RDG", "Reading"),
        ("GB-RFW", "Renfrewshire"),
        ("GB-RIC", "Richmond upon Thames"),
        ("GB-ROT", "Rotherham"),
        ("GB-RUT", "Rutland"),
        ("GB-SAW", "Sandwell"),
        ("GB-SAY", "South Ayrshire"),
        ("GB-SCB", "Scottish Borders"),
        ("GB-SFK", "Suffolk"),
        ("GB-SFT", "Sefton"),
        ("GB-SGC", "South Gloucestershire"),
        ("GB-SHF", "Sheffield"),
        ("GB-SHN", "Merseyside"),
        ("GB-SHR", "Shropshire"),
        ("GB-SKP", "Stockport"),
        ("GB-SLF", "Salford"),
        ("GB-SLG", "Slough"),
        ("GB-SLK", "South Lanarkshire"),
        ("GB-SND", "Sunderland"),
        ("GB-SOL", "Solihull"),
        ("GB-SOM", "Somerset"),
        ("GB-SOS", "Southend-on-Sea"),
        ("GB-SRY", "Surrey"),
        ("GB-STB", "Strabane"),
        ("GB-STE", "Stoke-on-Trent"),
        ("GB-STG", "Stirling"),
        ("GB-STH", "Southampton"),
        ("GB-STN", "Sutton"),
        ("GB-STS", "Staffordshire"),
        ("GB-STT", "Stockton-on-Tees"),
        ("GB-STY", "South Tyneside"),
        ("GB-SWA", "Swansea"),
        ("GB-SWD", "Swindon"),
        ("GB-SWK", "Southwark"),
        ("GB-TAM", "Tameside"),
        ("GB-TFW", "Telford and Wrekin"),
        ("GB-THR", "Thurrock"),
        ("GB-TOB", "Torbay"),
        ("GB-TOF", "Torfaen"),
        ("GB-TRF", "Trafford"),
        ("GB-TWH", "Tower Hamlets"),
        ("GB-VGL", "Vale of Glamorgan"),
        ("GB-WAR", "Warwickshire"),
        ("GB-WBK", "West Berkshire"),
        ("GB-WDU", "West Dunbartonshire"),
        ("GB-WFT", "Waltham Forest"),
        ("GB-WGN", "Wigan"),
        ("GB-WIL", "Wiltshire"),
        ("GB-WKF", "Wakefield"),
        ("GB-WLL", "Walsall"),
        ("GB-WLN", "West Lothian"),
        ("GB-WLV", "Wolverhampton"),
        ("GB-WND", "Wandsworth"),
        ("GB-WNM", "Royal Borough of Windsor and Maidenhead"),
        ("GB-WOK", "Wokingham"),
        ("GB-WOR", "Worcestershire"),
        ("GB-WRL", "Halton"),
        ("GB-WRT", "Warrington"),
        ("GB-WRX", "Wrexham"),
        ("GB-WSM", "Westminster"),
        ("GB-WSX", "West Sussex"),
        ("GB-YOR", "York"),
    ],
    "usa": [
        ("US-AK", "Alaska"),
        ("US-AL", "Alabama"),
        ("US-AR", "Arkansas"),
        ("US-AZ", "Arizona"),
        ("US-CA", "California"),
        ("US-CO", "Colorado"),
        ("US-CT", "Connecticut"),
        ("US-DC", "District of Columbia"),
        ("US-DE", "Delaware"),
        ("US-FL", "Florida"),
        ("US-GA", "Georgia"),
        ("US-HI", "Hawaii"),
        ("US-IA", "Iowa"),
        ("US-ID", "Idaho"),
        ("US-IL", "Illinois"),
        ("US-IN", "Indiana"),
        ("US-KS", "Kansas"),
        ("US-KY", "Kentucky"),
        ("US-LA", "Louisiana"),
        ("US-MA", "Massachusetts"),
        ("US-MD", "Maryland"),
        ("US-ME", "Maine"),
        ("US-MI", "Michigan"),
        ("US-MN", "Minnesota"),
        ("US-MO", "Missouri"),
        ("US-MS", "Mississippi"),
        ("US-MT", "Montana"),
        ("US-NC", "North Carolina"),
        ("US-ND", "North Dakota"),
        ("US-NE", "Nebraska"),
        ("US-NH", "New Hampshire"),
        ("US-NJ", "New Jersey"),
        ("US-NM", "New Mexico"),
        ("US-NV", "Nevada"),
        ("US-NY", "New York"),
        ("US-OH", "Ohio"),
        ("US-OK", "Oklahoma"),
        ("US-OR", "Oregon"),
        ("US-PA", "Pennsylvania"),
        ("US-RI", "Rhode Island"),
        ("US-SC", "South Carolina"),
        ("US-SD", "South Dakota"),
        ("US-TN", "Tennessee"),
        ("US-TX", "Texas"),
        ("US-UT", "Utah"),
        ("US-VA", "Virginia"),
        ("US-VT", "Vermont"),
        ("US-WA", "Washington"),
        ("US-WI", "Wisconsin"),
        ("US-WV", "West Virginia"),
        ("US-WY", "Wyoming"),
    ],
}
