# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""Rendered world identifiers from datamaps/dist/datamaps.all.min.

The backend parity test checks this snapshot against the frontend boundary set,
which Jest verifies against the actual Datamaps world topology. The country
dictionary also includes countries with no polygon, which can only be drawn
as bubbles.
"""

WORLD_BOUNDARY_IDS: frozenset[str] = frozenset(
    {
        "-99",
        "AFG",
        "AGO",
        "ALB",
        "ARE",
        "ARG",
        "ARM",
        "ATA",
        "ATF",
        "AUS",
        "AUT",
        "AZE",
        "BDI",
        "BEL",
        "BEN",
        "BFA",
        "BGD",
        "BGR",
        "BHS",
        "BIH",
        "BLR",
        "BLZ",
        "BOL",
        "BRA",
        "BRN",
        "BTN",
        "BWA",
        "CAF",
        "CAN",
        "CHE",
        "CHL",
        "CHN",
        "CIV",
        "CMR",
        "COD",
        "COG",
        "COL",
        "CRI",
        "CUB",
        "CYP",
        "CZE",
        "DEU",
        "DJI",
        "DNK",
        "DOM",
        "DZA",
        "ECU",
        "EGY",
        "ERI",
        "ESH",
        "ESP",
        "EST",
        "ETH",
        "FIN",
        "FJI",
        "FLK",
        "FRA",
        "GAB",
        "GBR",
        "GEO",
        "GHA",
        "GIN",
        "GMB",
        "GNB",
        "GNQ",
        "GRC",
        "GRL",
        "GTM",
        "GUF",
        "GUY",
        "HND",
        "HRV",
        "HTI",
        "HUN",
        "IDN",
        "IND",
        "IRL",
        "IRN",
        "IRQ",
        "ISL",
        "ISR",
        "ITA",
        "JAM",
        "JOR",
        "JPN",
        "KAZ",
        "KEN",
        "KGZ",
        "KHM",
        "KOR",
        "KWT",
        "LAO",
        "LBN",
        "LBR",
        "LBY",
        "LKA",
        "LSO",
        "LTU",
        "LUX",
        "LVA",
        "MAR",
        "MDA",
        "MDG",
        "MEX",
        "MKD",
        "MLI",
        "MMR",
        "MNE",
        "MNG",
        "MOZ",
        "MRT",
        "MWI",
        "MYS",
        "NAM",
        "NCL",
        "NER",
        "NGA",
        "NIC",
        "NLD",
        "NOR",
        "NPL",
        "NZL",
        "OMN",
        "PAK",
        "PAN",
        "PER",
        "PHL",
        "PNG",
        "POL",
        "PRI",
        "PRK",
        "PRT",
        "PRY",
        "PSE",
        "QAT",
        "ROU",
        "RUS",
        "RWA",
        "SAU",
        "SDN",
        "SEN",
        "SLB",
        "SLE",
        "SLV",
        "SOM",
        "SRB",
        "SSD",
        "SUR",
        "SVK",
        "SVN",
        "SWE",
        "SWZ",
        "SYR",
        "TCD",
        "TGO",
        "THA",
        "TJK",
        "TKM",
        "TLS",
        "TTO",
        "TUN",
        "TUR",
        "TWN",
        "TZA",
        "UGA",
        "UKR",
        "URY",
        "USA",
        "UZB",
        "VEN",
        "VNM",
        "VUT",
        "YEM",
        "ZAF",
        "ZMB",
        "ZWE",
    }
)
