#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

######################################################################
# Dev image...
######################################################################
FROM preset/superset:dev

COPY ./requirements* ./docker/requirements* /app/

USER root
RUN cd /app \
    && pip install -e . \
    && pip install --no-cache -r requirements.txt -r requirements-dev.txt \
    && pip install --no-cache -r requirements-extra.txt \
    && pip install --no-cache -r requirements-local.txt || true
USER superset
