#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
[pytest]
testpaths =
    tests
python_files = *_test.py test_*.py *_tests.py *viz/utils.py
# `-p no:warnings` temporarily disabled in favor of more finely tuned `filterwarnings`.
#addopts = -p no:warnings
asyncio_mode = auto

# `ignore` is effectively equivalent to `-p no:warnings`.
# Always print RemovedIn20Warning when SQLALCHEMY_WARN_20=1.
# Additionally, raise errors for refactored RemovedIn20Warning cases to prevent regression.
filterwarnings =
    ignore
    always::sqlalchemy.exc.RemovedIn20Warning
    error:Passing a string to Connection.execute\(\) is deprecated:sqlalchemy.exc.RemovedIn20Warning
#    error:"Query" object is being merged into a Session:sqlalchemy.exc.RemovedIn20Warning
#    error:"SavedQuery" object is being merged into a Session:sqlalchemy.exc.RemovedIn20Warning
#    error:"SqlaTable" object is being merged into a Session:sqlalchemy.exc.RemovedIn20Warning
#    error:"SqlMetric" object is being merged into a Session:sqlalchemy.exc.RemovedIn20Warning
#    error:"TableColumn" object is being merged into a Session:sqlalchemy.exc.RemovedIn20Warning
#    error:"TaggedObject" object is being merged into a Session:sqlalchemy.exc.RemovedIn20Warning
#    error:The ``as_declarative\(\)`` function is now available:sqlalchemy.exc.RemovedIn20Warning
#    error:The autoload parameter is deprecated:sqlalchemy.exc.RemovedIn20Warning
#    error:The connection.execute\(\) method:sqlalchemy.exc.RemovedIn20Warning
#    error:The current statement is being autocommitted using implicit autocommit:sqlalchemy.exc.RemovedIn20Warning
#    error:The `database` package is deprecated:sqlalchemy.exc.RemovedIn20Warning
#    error:The ``declarative_base\(\)`` function is now available:sqlalchemy.exc.RemovedIn20Warning
#    error:The Engine.execute\(\) method is considered legacy:sqlalchemy.exc.RemovedIn20Warning
    error:The legacy calling style of select\(\) is deprecated:sqlalchemy.exc.RemovedIn20Warning
#    error:The "whens" argument to case:sqlalchemy.exc.RemovedIn20Warning
#    error:"User" object is being merged into a Session:sqlalchemy.exc.RemovedIn20Warning
