# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Shared hard-delete cascade for the purge task and force-purge command.

A single code path keeps the two surfaces from drifting. Every dependent row
is removed by an explicit ``sa.delete``;
the DB ``ON DELETE CASCADE`` constraints are a backstop only — SQLite does
not enforce FKs unless ``PRAGMA foreign_keys=ON`` and Core bulk DML fires
only DB-level cascades, so relying on cascade silently leaks rows.

Cascade tiers:

* **M:N join rows** — hard-deleted for the purged entity, including join
  rows owned by *surviving* entities (e.g. a live dashboard's
  ``dashboard_slices`` row to a purged chart). The entity on the other side
  is never touched except to lose that one relationship row.
* **Owned children** (``delete-orphan``, no independent existence) — a
  dataset's columns and metrics, hard-deleted with it.
* **Independently-owned entities** (a dashboard's charts, a chart's dataset)
  are **preserved**. A live chart's loose ``datasource_id`` to a purged
  dataset is left dangling — legacy hard-delete semantics, no guard.
* **Version history** — the entity's own ``*_version`` shadows and
  the ``version_changes`` scoped to them, plus an orphan-sweep of any
  ``version_transaction`` left owning zero surviving shadows. Runs
  behind a ``has_table`` check so it no-ops when versioning is absent.
"""

from __future__ import annotations

import logging
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import sqlalchemy as sa
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from superset.commands.deletion_retention.purge_impact import (
    collect_dataset_purge_impact,
    DatasetPurgeImpact,
    PurgeImpactChangedError,
)
from superset.commands.deletion_retention.purge_policy import (
    BlockerReason,
    get_purge_policy,
    PurgeBlockedError,
    PurgeEntityPolicy,
    REASON_CASCADE_INTEGRITY_FAILURE,
)

logger: logging.Logger = logging.getLogger(__name__)


@contextmanager
def suppress_purge_association_versions(session: Session) -> Iterator[None]:
    """Discard only association versions generated by this purge session.

    ``dashboard_slices`` is a Continuum-tracked association table. Its
    engine-level listener expects a unit-of-work even for Core deletes and
    queues a shadow-table insert for each removed relationship. A purge
    removes history rather than creating it, so preserve any pending work
    that predates this block and discard only statements queued by the purge.

    This is deliberately session-scoped. Mutating Continuum's process-global
    ``options["versioning"]`` would let concurrent requests silently lose
    unrelated history while a purge is running.
    """
    try:
        from sqlalchemy_continuum import versioning_manager
    except ImportError:
        yield
        return

    options = versioning_manager.options
    if not (options.get("versioning") or options.get("native_versioning")):
        yield
        return

    unit_of_work = versioning_manager.unit_of_work(session)
    pending_before = len(unit_of_work.pending_statements)
    try:
        yield
    finally:
        del unit_of_work.pending_statements[pending_before:]


def entity_uuid(entity: Any) -> str | None:
    """Return the entity's UUID as a string, or ``None`` if it has none."""
    value = getattr(entity, "uuid", None)
    return str(value) if value is not None else None


def _identity_predicates(table: sa.Table, entity_id: int, entity: Any) -> list[Any]:
    """Predicates pinning a statement to the exact row *entity* came from.

    The id alone is not an identity: a row can be removed and its id handed to
    a different entity, and both SQLite rowids and a sequence wrapped by an
    operator will reuse values. Callers snapshot the uuid well before the
    cascade runs -- the retention task writes an audit row in between -- so the
    locked claim and the conditional delete carry the uuid too, and a reused id
    simply matches nothing rather than purging a stranger under the snapshot's
    name. Checking it before the lock would only narrow that window; a
    predicate on the claim closes it.

    Falls back to the id alone for a model with no uuid column.
    """
    predicates: list[Any] = [table.c.id == entity_id]
    uuid_column = table.c.get("uuid")
    expected_uuid = entity_uuid(entity)
    if uuid_column is not None and expected_uuid is not None:
        predicates.append(uuid_column == expected_uuid)
    return predicates


def _version_tables_present(bind: Any) -> bool:
    """Whether the version-history tables exist (a testable seam, so the
    version cascade no-ops cleanly before versioning is installed)."""
    return sa.inspect(bind).has_table("version_transaction")


@dataclass
class CascadeResult:
    """Outcome of one entity's cascade.

    ``purged`` is False when the conditional entity-row delete matched no
    row — the entity was restored between selection and delete or was already
    gone. In that case
    no dependents are touched.
    """

    purged: bool
    entity_type: str
    entity_uuid: str | None
    dangling_chart_uuids: list[str] = field(default_factory=list)
    removed_dashboard_slices: int = 0
    version_rows_removed: int = 0
    blocker: BlockerReason | None = None

    @property
    def blocked_reason(self) -> str | None:
        """Return the operator-facing blocker phrase, if the purge was blocked."""
        return self.blocker.phrase if self.blocker else None

    @property
    def blocked_reason_code(self) -> str | None:
        """Return the stable audit code, if the purge was blocked."""
        return self.blocker.code if self.blocker else None


class PurgeRaceLostError(Exception):
    """Raised to roll back dependent cleanup when the entity delete loses."""


def _eligibility_predicates(
    table: sa.Table,
    *,
    enforce_window: bool,
    cutoff: datetime | None,
    require_archived: bool,
) -> list[Any]:
    """Row-state predicates that decide whether *entity* may still be purged.

    Returned as a list so the identical set can be carried by both the locked
    claim and the conditional delete. Eligibility has to be expressed as SQL
    predicates on those two statements rather than as a check beforehand: a
    restore committing between the check and the lock would otherwise go
    unnoticed. An empty list means every row is eligible.
    """
    if enforce_window:
        return [table.c.deleted_at.is_not(None), table.c.deleted_at < cutoff]
    if require_archived:
        return [table.c.deleted_at.is_not(None)]
    return []


def cascade_hard_delete(
    session: Session,
    entity: Any,
    *,
    enforce_window: bool,
    cutoff: datetime | None = None,
    require_archived: bool = False,
    confirmed_impact_token: str | None = None,
) -> CascadeResult:
    """Remove *entity* and everything that depends on it in one transaction.

    The entity row is locked and its eligibility is re-checked before any
    dependent state is touched. Ordinary deletion blockers remain
    authoritative. All cleanup and the conditional parent delete run inside a
    savepoint so a lost race or restrictive foreign key leaves no side effects.

    Eligibility means different things to the two callers, and both express it
    here rather than upstream, because only the predicates carried by the
    locked claim and the conditional delete are race-free. Anything checked
    before the lock can be invalidated by a commit landing in between.

    ``enforce_window`` (retention) requires the row to be soft-deleted and
    older than *cutoff*. ``require_archived`` (force purge, which ignores the
    window) requires only that it is still soft-deleted, so a restore
    committed after the caller resolved the entity cannot be destroyed.
    """
    if enforce_window and cutoff is None:
        raise ValueError("cutoff is required when enforce_window=True")

    model = type(entity)
    table = model.__table__
    entity_id = entity.id
    uuid = entity_uuid(entity)
    policy: PurgeEntityPolicy = get_purge_policy(model)
    entity_type: str = policy.entity_type

    dangling_chart_uuids: list[str] = []
    removed_dashboard_slices = 0
    version_rows = 0
    permission_name: str | None = None
    confirmed_impact: DatasetPurgeImpact | None = None

    try:
        with session.begin_nested():
            # Two independent questions, both answered under the lock:
            # identity pins which row this is (id can be reused; uuid cannot),
            # eligibility pins whether that row may still be purged.
            identity = _identity_predicates(table, entity_id, entity)
            eligibility = _eligibility_predicates(
                table,
                enforce_window=enforce_window,
                cutoff=cutoff,
                require_archived=require_archived,
            )
            claim = sa.select(table.c.id).where(*identity).where(*eligibility)
            if session.execute(claim.with_for_update()).scalar_one_or_none() is None:
                raise PurgeRaceLostError

            if entity_type == "dataset" and confirmed_impact_token is not None:
                confirmed_impact = collect_dataset_purge_impact(session, entity_id)
                if confirmed_impact.impact_token != confirmed_impact_token:
                    raise PurgeImpactChangedError(confirmed_impact)

            policy.validate(session, policy, entity_id)
            # Captured under the lock: the row is claimed, so the identity
            # the permission name is built from can no longer change.
            permission_name = policy.capture_permission_name(session, policy, entity_id)
            removed_dashboard_slices = policy.count_dashboard_slices(
                session, policy, entity_id
            )
            dangling_chart_uuids = (
                [chart.uuid for chart in confirmed_impact.charts]
                if confirmed_impact is not None
                else policy.collect_dangling_chart_uuids(session, policy, entity_id)
            )

            policy.delete_associations(session, policy, entity_id)
            policy.delete_owned_children(session, policy, entity_id)
            version_rows = _delete_version_history(session, entity, entity_id)

            delete_entity = sa.delete(table).where(*identity).where(*eligibility)
            if session.execute(delete_entity).rowcount == 0:
                raise PurgeRaceLostError

            if permission_name is not None:
                policy.cleanup_permission(session, policy, permission_name, entity_id)
    except PurgeRaceLostError:
        logger.info(
            "deletion_retention: %s id=%s not purged (restored or already gone)",
            entity_type,
            entity_id,
        )
        return CascadeResult(purged=False, entity_type=entity_type, entity_uuid=uuid)
    except PurgeBlockedError as ex:
        logger.info(
            "deletion_retention: %s id=%s blocked by existing deletion rules",
            entity_type,
            entity_id,
        )
        return CascadeResult(
            purged=False,
            entity_type=entity_type,
            entity_uuid=uuid,
            blocker=ex.reason,
        )
    except IntegrityError as ex:
        # Not a policy decision: a database integrity constraint failed.
        # Two audiences, two messages. The curated reason goes to the caller
        # (and from there into a user toast), because raw driver text carries
        # the failing SQL and bind parameters. The constraint detail goes to
        # the log at WARNING, because an entity permanently unpurgeable after
        # an integrity failure represents a cascade defect someone has to be
        # able to diagnose. The stable audit code identifies this as an unexpected
        # cascade failure rather than intended policy behavior without
        # claiming which kind of constraint the database reported.
        logger.warning(
            "deletion_retention: %s id=%s purge failed on a database "
            "integrity constraint: %s",
            entity_type,
            entity_id,
            ex,
        )
        return CascadeResult(
            purged=False,
            entity_type=entity_type,
            entity_uuid=uuid,
            blocker=BlockerReason(
                REASON_CASCADE_INTEGRITY_FAILURE,
                "cascade blocked by a database integrity constraint",
            ),
        )

    return CascadeResult(
        purged=True,
        entity_type=entity_type,
        entity_uuid=uuid,
        dangling_chart_uuids=dangling_chart_uuids,
        removed_dashboard_slices=removed_dashboard_slices,
        version_rows_removed=version_rows,
    )


def dashboard_slice_count(session: Session, entity: Any) -> int:
    """Return the current dashboard relationship count for audit write-ahead."""
    policy: PurgeEntityPolicy = get_purge_policy(type(entity))
    return policy.count_dashboard_slices(session, policy, entity.id)


def _entity_version_targets(
    model: type[Any],
    metadata: sa.MetaData,
    parent_shadow: sa.Table,
    entity_id: int,
) -> list[tuple[sa.Table, Any]]:
    """The ``(shadow_table, row_predicate)`` pairs that make up *this* entity's
    own version history: the parent shadow keyed by ``id``, plus — per type —
    the dashboard/chart M2M shadow (``dashboard_slices_version``) and a
    dataset's child shadows (``table_columns_version`` / ``sql_metrics_version``
    keyed by ``table_id``). It never touches another entity's rows."""
    targets: list[tuple[sa.Table, Any]] = []
    for table_name, column_name in get_purge_policy(model).version_shadow_names:
        shadow: sa.Table | None = (
            parent_shadow
            if table_name == parent_shadow.name
            else metadata.tables.get(table_name)
        )
        if shadow is None or column_name not in shadow.c:
            raise RuntimeError(
                f"Invalid version shadow declaration for {model.__name__}: "
                f"{table_name}.{column_name}"
            )
        targets.append((shadow, shadow.c[column_name] == entity_id))
    return targets


def _delete_version_history(session: Session, entity: Any, entity_id: int) -> int:
    """Remove the entity's own version-history rows.

    Deletes the entity's parent + child + M2M ``*_version`` shadow rows and the
    ``version_changes`` rows scoped to this entity (by ``entity_kind`` +
    ``entity_id`` — **not** by transaction, which is shared), then sweeps any
    ``version_transaction`` left owning zero surviving shadow / change rows. A
    ``version_transaction`` is a *shared* unit-of-work boundary that can span
    entities, so it is removed only once orphaned — never blind-deleted. Gated
    on the version tables existing, so it no-ops cleanly without versioning.
    """
    if not _version_tables_present(session.get_bind()):
        return 0

    # pylint: disable=import-outside-toplevel
    try:
        from sqlalchemy_continuum import version_class, versioning_manager
        from sqlalchemy_continuum.exc import ClassNotVersioned
    except ImportError:
        return 0

    model = type(entity)
    try:
        parent_shadow = version_class(model).__table__
    except ClassNotVersioned:
        return 0

    metadata = parent_shadow.metadata
    # version_transaction lives in Continuum's manager, not the shadow metadata.
    tx = versioning_manager.transaction_cls.__table__
    changes = metadata.tables.get("version_changes")
    targets = _entity_version_targets(model, metadata, parent_shadow, entity_id)

    # Transactions these shadow rows are anchored to — orphan-sweep candidates.
    tx_ids: set[int] = set()
    for tbl, pred in targets:
        if "transaction_id" in tbl.c:
            tx_ids.update(
                row[0]
                for row in session.execute(
                    sa.select(tbl.c.transaction_id).where(pred).distinct()
                )
            )

    removed = 0
    for tbl, pred in targets:
        removed += session.execute(sa.delete(tbl).where(pred)).rowcount

    # version_changes scoped to this entity (entity_kind + entity_id).
    # Counted alongside the shadow rows: callers report the total as the
    # definitive number of version-history rows removed.
    if changes is not None:
        from superset.versioning.changes import ENTITY_KIND_BY_CLASS_NAME

        kind = ENTITY_KIND_BY_CLASS_NAME.get(model.__name__)
        if kind is not None:
            removed += session.execute(
                sa.delete(changes).where(
                    changes.c.entity_kind == kind,
                    changes.c.entity_id == entity_id,
                )
            ).rowcount

    if tx is not None and tx_ids:
        _sweep_orphan_transactions(session, metadata, tx, changes, tx_ids)

    return removed


# Bound for IN() membership lists, below SQLite's historical 999
# bind-variable limit (well under PostgreSQL and MySQL limits). An entity
# with a long edit history can anchor thousands of transactions; unchunked
# IN lists would fail the sweep on SQLite — and a failing sweep makes the
# entity permanently unpurgeable.
_IN_CLAUSE_CHUNK: int = 500


def _chunked(values: set[int]) -> Iterator[list[int]]:
    """Yield sorted ``_IN_CLAUSE_CHUNK``-sized slices of *values*."""
    ordered = sorted(values)
    for start in range(0, len(ordered), _IN_CLAUSE_CHUNK):
        yield ordered[start : start + _IN_CLAUSE_CHUNK]


def _sweep_orphan_transactions(
    session: Session,
    metadata: sa.MetaData,
    tx: sa.Table,
    changes: sa.Table | None,
    tx_ids: set[int],
) -> None:
    """Delete unreferenced ``version_transaction`` rows.

    Every ``*_version`` table and ``version_changes`` is checked. A double-sweep
    of the same orphan is a harmless no-op.

    A shadow row references a transaction through **either** endpoint of its
    lifespan: ``transaction_id`` (created at) or ``end_transaction_id`` (closed
    at). Both are foreign keys, so both keep a transaction alive.

    Counting only the created-at side is a live FK hazard whenever a
    transaction spans entities, which is the normal case: one flush saving a
    dashboard, chart and dataset gives all three a shadow row at ``tx=X``. If
    the dashboard alone is later edited at ``tx=Y``, its row at ``tx=X`` closes
    with ``end_transaction_id=Y`` while the others stay live at ``tx=X``.
    Purging the dashboard removes its own shadow rows, after which nothing
    *creates* at ``tx=Y`` — but the sibling rows still point at it, or at ``X``,
    through their end column. Deleting the transaction then fails the foreign
    key, and the caller reports the entity as blocked by deletion rules rather
    than as the incomplete cascade it is. ``version_history_retention`` hit the
    same trap and documents it on ``_delete_for_transactions``.
    """
    sources = [
        t
        for name, t in metadata.tables.items()
        if name.endswith("_version") and "transaction_id" in t.c
    ]
    if changes is not None and "transaction_id" in changes.c:
        sources.append(changes)
    still_referenced: set[int] = set()
    for source in sources:
        # ``version_changes`` has no closing endpoint; shadow tables do.
        columns = [
            source.c[name]
            for name in ("transaction_id", "end_transaction_id")
            if name in source.c
        ]
        for column in columns:
            for chunk in _chunked(tx_ids):
                still_referenced.update(
                    row[0]
                    for row in session.execute(
                        sa.select(column).where(column.in_(chunk)).distinct()
                    )
                )
    if orphaned := tx_ids - still_referenced:
        for chunk in _chunked(orphaned):
            session.execute(sa.delete(tx).where(tx.c.id.in_(chunk)))
