{{/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secretStoreRef.name }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "superset.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    {{- include "superset.labels" . | nindent 4 }}
    {{- if .Values.extraLabels }}
      {{- toYaml .Values.extraLabels | nindent 4 }}
    {{- end }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ template "superset.fullname" . }}-env
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{- if .Values.database.password }}
        DB_PASS: "{{ .Values.externalSecrets.keys.databasePassword }}"
        {{- end }}
        {{- if .Values.cache.password }}
        REDIS_PASSWORD: "{{ .Values.externalSecrets.keys.redisPassword }}"
        {{- end }}
        {{- if .Values.extraSecretEnv.SUPERSET_SECRET_KEY }}
        SUPERSET_SECRET_KEY: "{{ .Values.externalSecrets.keys.secretKey }}"
        {{- end }}
        {{- if and .Values.init.createAdmin .Values.init.adminUser.password }}
        ADMIN_PASSWORD: "{{ .Values.externalSecrets.keys.adminPassword }}"
        {{- end }}
        {{- if and .Values.supersetWebsockets.enabled .Values.supersetWebsockets.config.jwtSecret }}
        JWT_SECRET: "{{ .Values.externalSecrets.keys.jwtSecret }}"
        {{- end }}
  data:
    {{- if .Values.database.password }}
    - secretKey: DB_PASS
      remoteRef:
        key: {{ .Values.externalSecrets.keys.databasePassword }}
    {{- end }}
    {{- if .Values.cache.password }}
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.keys.redisPassword }}
    {{- end }}
    {{- if .Values.extraSecretEnv.SUPERSET_SECRET_KEY }}
    - secretKey: SUPERSET_SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.keys.secretKey }}
    {{- end }}
    {{- if and .Values.init.createAdmin .Values.init.adminUser.password }}
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.keys.adminPassword }}
    {{- end }}
    {{- if and .Values.supersetWebsockets.enabled .Values.supersetWebsockets.config.jwtSecret }}
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.keys.jwtSecret }}
    {{- end }}
{{- end }}
