/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/**
 * The original Cypress suite's second case ("should have different key when
 * page reloads") was non-functional: it compared `native_filters_key` against
 * an `initialFilterKey` variable that was declared but never assigned, so it
 * asserted against `undefined` and passed vacuously. The real backend
 * contract is the opposite — CreateFilterStateCommand reuses the existing key
 * for a given (session, tab, dashboard) via a contextual cache — so this
 * migration asserts the true behaviour (reuse), not the inherited bug.
 *
 * The second visit is deliberately a fresh `page.goto` to the bare dashboard
 * URL, not `page.reload()`: a reload keeps `?native_filters_key=` in the
 * address bar, so the wait for the key would resolve against the pre-existing
 * param and take the PUT (update) branch instead of re-exercising the create
 * path. The bare URL forces a new POST, and the backend still answers with
 * the same key because its contextual cache is keyed on the tab id (persisted
 * in sessionStorage across the navigation), not on the URL.
 *
 * Key reuse also requires every request to reach the same filter_state cache.
 * The test config uses a per-process SimpleCache, and CI runs a single
 * gunicorn worker without recycling, so reuse is deterministic there; a
 * multi-worker or worker-recycling backend would make the reuse assertion
 * flaky.
 */
import { testWithAssets, expect } from '../../helpers/fixtures';
import {
  apiGetDashboardFilterState,
  ENDPOINTS,
} from '../../helpers/api/dashboard';
import { expectStatus } from '../../helpers/api/assertions';
import { waitForPost } from '../../helpers/api/intercepts';
import { TIMEOUT } from '../../utils/constants';
import { DashboardPage } from '../../pages/DashboardPage';
import {
  buildFilterJsonMetadata,
  buildSelectFilter,
  createDashboardWithCharts,
} from './dashboard-test-helpers';

const DATASET_NAME = 'birth_names';
const FILTER_COLUMN = 'gender';

testWithAssets(
  'native filter bar mints a persisted, server-resolvable filter_state key and reuses it on a fresh navigation',
  async ({ page, testAssets }, testInfo) => {
    testWithAssets.setTimeout(TIMEOUT.SLOW_TEST);

    // The filter id is generated by the builder; capture it so the stored data
    // mask can be checked for this dashboard's filter specifically.
    let filterId = '';
    const { dashboardId } = await createDashboardWithCharts(
      page,
      testAssets,
      testInfo,
      {
        datasetName: DATASET_NAME,
        chartNamePrefix: 'nf_key',
        dashboardTitlePrefix: 'nf_key',
        chartSpecs: [
          {
            viz_type: 'big_number_total',
            params: { metric: 'count', adhoc_filters: [] },
          },
        ],
        buildJsonMetadata: ({ charts, datasetId }) => {
          const chartsInScope = charts.map(chart => chart.id);
          const filter = buildSelectFilter({
            datasetId,
            column: FILTER_COLUMN,
            chartsInScope,
            name: 'Gender',
          });
          filterId = filter.id;
          return buildFilterJsonMetadata({
            chartsInScope,
            nativeFilters: [filter],
          });
        },
      },
    );

    const dashboard = new DashboardPage(page);
    const filterStateEndpoint = `${ENDPOINTS.DASHBOARD}${dashboardId}/filter_state`;

    // Load the dashboard and return the URL key together with the key the
    // filter_state POST minted, so the two can be compared.
    const visitAndCaptureKeys = async () => {
      const created = waitForPost(page, filterStateEndpoint, {
        timeout: TIMEOUT.API_RESPONSE,
      });
      await dashboard.gotoById(dashboardId);
      await dashboard.waitForLoad();
      const urlKey = await dashboard.waitForNativeFiltersKey();
      const { key: postedKey } = await expectStatus(await created, 201).json();
      return { urlKey, postedKey };
    };

    // Confirm the key resolves to this dashboard's stored data mask via the
    // backend filter_state GET endpoint — proving it is a real server-side
    // entry, not a client token. A client-only token would not resolve.
    const assertKeyResolves = async (key: string) => {
      const stateResp = await apiGetDashboardFilterState(
        page,
        dashboardId,
        key,
        { failOnStatusCode: false },
      );
      expectStatus(stateResp, 200);
      const stateBody = await stateResp.json();
      // The stored value is the serialized data mask, keyed by filter id.
      expect(
        JSON.parse(stateBody.value),
        `filter_state key ${key} should carry the data mask for filter ${filterId}`,
      ).toHaveProperty(filterId);
    };

    const first = await visitAndCaptureKeys();
    expect(
      first.urlKey,
      'the key in the URL should be the one minted by the filter_state POST',
    ).toBe(first.postedKey);
    await assertKeyResolves(first.urlKey);

    // Fresh navigation: the backend reuses the existing key for this
    // (session, tab, dashboard), and the overwritten entry still resolves.
    const second = await visitAndCaptureKeys();
    expect(second.urlKey).toBe(second.postedKey);
    expect(
      second.urlKey,
      'a fresh navigation should reuse the same filter_state key for the session/tab',
    ).toBe(first.urlKey);
    await assertKeyResolves(second.urlKey);
  },
);
