/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/**
 * Country reference data used to map an entity value (in any supported code
 * convention) to the ISO 3166-1 alpha-3 code, display name and centroid that
 * the world map renderer consumes.
 *
 * Mirrors superset/examples/countries.py, which performed this lookup
 * server-side when this chart still used the legacy /superset/explore_json/
 * data endpoint.
 */

export interface CountryInfo {
  name: string;
  cca2: string;
  cca3: string;
  cioc: string;
  lat: number;
  lng: number;
}

export type CountryFieldType = 'name' | 'cca2' | 'cca3' | 'cioc';

const countries: CountryInfo[] = [
  {
    name: 'Angola',
    cca2: 'AO',
    cca3: 'AGO',
    cioc: 'ANG',
    lat: -12.5,
    lng: 18.5,
  },
  { name: 'Algeria', cca2: 'DZ', cca3: 'DZA', cioc: 'ALG', lat: 28, lng: 3 },
  { name: 'Egypt', cca2: 'EG', cca3: 'EGY', cioc: 'EGY', lat: 27, lng: 30 },
  {
    name: 'Bangladesh',
    cca2: 'BD',
    cca3: 'BGD',
    cioc: 'BAN',
    lat: 24,
    lng: 90,
  },
  { name: 'Niger', cca2: 'NE', cca3: 'NER', cioc: 'NIG', lat: 16, lng: 8 },
  {
    name: 'Liechtenstein',
    cca2: 'LI',
    cca3: 'LIE',
    cioc: 'LIE',
    lat: 47.26666666,
    lng: 9.53333333,
  },
  { name: 'Namibia', cca2: 'NA', cca3: 'NAM', cioc: 'NAM', lat: -22, lng: 17 },
  { name: 'Bulgaria', cca2: 'BG', cca3: 'BGR', cioc: 'BUL', lat: 43, lng: 25 },
  { name: 'Bolivia', cca2: 'BO', cca3: 'BOL', cioc: 'BOL', lat: -17, lng: -65 },
  { name: 'Ghana', cca2: 'GH', cca3: 'GHA', cioc: 'GHA', lat: 8, lng: -2 },
  {
    name: 'Cocos (Keeling) Islands',
    cca2: 'CC',
    cca3: 'CCK',
    cioc: '',
    lat: -12.5,
    lng: 96.83333333,
  },
  { name: 'Pakistan', cca2: 'PK', cca3: 'PAK', cioc: 'PAK', lat: 30, lng: 70 },
  {
    name: 'Cape Verde',
    cca2: 'CV',
    cca3: 'CPV',
    cioc: 'CPV',
    lat: 16,
    lng: -24,
  },
  { name: 'Jordan', cca2: 'JO', cca3: 'JOR', cioc: 'JOR', lat: 31, lng: 36 },
  {
    name: 'Liberia',
    cca2: 'LR',
    cca3: 'LBR',
    cioc: 'LBR',
    lat: 6.5,
    lng: -9.5,
  },
  { name: 'Libya', cca2: 'LY', cca3: 'LBY', cioc: 'LBA', lat: 25, lng: 17 },
  {
    name: 'Malaysia',
    cca2: 'MY',
    cca3: 'MYS',
    cioc: 'MAS',
    lat: 2.5,
    lng: 112.5,
  },
  {
    name: 'Dominican Republic',
    cca2: 'DO',
    cca3: 'DOM',
    cioc: 'DOM',
    lat: 19,
    lng: -70.66666666,
  },
  {
    name: 'Puerto Rico',
    cca2: 'PR',
    cca3: 'PRI',
    cioc: 'PUR',
    lat: 18.25,
    lng: -66.5,
  },
  {
    name: 'Mayotte',
    cca2: 'YT',
    cca3: 'MYT',
    cioc: '',
    lat: -12.83333333,
    lng: 45.16666666,
  },
  {
    name: 'North Korea',
    cca2: 'KP',
    cca3: 'PRK',
    cioc: 'PRK',
    lat: 40,
    lng: 127,
  },
  {
    name: 'Palestine',
    cca2: 'PS',
    cca3: 'PSE',
    cioc: 'PLE',
    lat: 31.9,
    lng: 35.2,
  },
  { name: 'Tanzania', cca2: 'TZ', cca3: 'TZA', cioc: 'TAN', lat: -6, lng: 35 },
  { name: 'Botswana', cca2: 'BW', cca3: 'BWA', cioc: 'BOT', lat: -22, lng: 24 },
  { name: 'Cambodia', cca2: 'KH', cca3: 'KHM', cioc: 'CAM', lat: 13, lng: 105 },
  {
    name: 'Nicaragua',
    cca2: 'NI',
    cca3: 'NIC',
    cioc: 'NCA',
    lat: 13,
    lng: -85,
  },
  {
    name: 'Trinidad and Tobago',
    cca2: 'TT',
    cca3: 'TTO',
    cioc: 'TTO',
    lat: 11,
    lng: -61,
  },
  { name: 'Ethiopia', cca2: 'ET', cca3: 'ETH', cioc: 'ETH', lat: 8, lng: 38 },
  {
    name: 'Paraguay',
    cca2: 'PY',
    cca3: 'PRY',
    cioc: 'PAR',
    lat: -23,
    lng: -58,
  },
  {
    name: 'Hong Kong',
    cca2: 'HK',
    cca3: 'HKG',
    cioc: 'HKG',
    lat: 22.267,
    lng: 114.188,
  },
  {
    name: 'Saudi Arabia',
    cca2: 'SA',
    cca3: 'SAU',
    cioc: 'KSA',
    lat: 25,
    lng: 45,
  },
  {
    name: 'Lebanon',
    cca2: 'LB',
    cca3: 'LBN',
    cioc: 'LIB',
    lat: 33.83333333,
    lng: 35.83333333,
  },
  {
    name: 'Slovenia',
    cca2: 'SI',
    cca3: 'SVN',
    cioc: 'SLO',
    lat: 46.11666666,
    lng: 14.81666666,
  },
  {
    name: 'Burkina Faso',
    cca2: 'BF',
    cca3: 'BFA',
    cioc: 'BUR',
    lat: 13,
    lng: -2,
  },
  {
    name: 'Switzerland',
    cca2: 'CH',
    cca3: 'CHE',
    cioc: 'SUI',
    lat: 47,
    lng: 8,
  },
  {
    name: 'Mauritania',
    cca2: 'MR',
    cca3: 'MRT',
    cioc: 'MTN',
    lat: 20,
    lng: -12,
  },
  {
    name: 'Croatia',
    cca2: 'HR',
    cca3: 'HRV',
    cioc: 'CRO',
    lat: 45.16666666,
    lng: 15.5,
  },
  { name: 'Chile', cca2: 'CL', cca3: 'CHL', cioc: 'CHI', lat: -30, lng: -71 },
  { name: 'China', cca2: 'CN', cca3: 'CHN', cioc: 'CHN', lat: 35, lng: 105 },
  {
    name: 'Saint Kitts and Nevis',
    cca2: 'KN',
    cca3: 'KNA',
    cioc: 'SKN',
    lat: 17.33333333,
    lng: -62.75,
  },
  {
    name: 'Sierra Leone',
    cca2: 'SL',
    cca3: 'SLE',
    cioc: 'SLE',
    lat: 8.5,
    lng: -11.5,
  },
  {
    name: 'Jamaica',
    cca2: 'JM',
    cca3: 'JAM',
    cioc: 'JAM',
    lat: 18.25,
    lng: -77.5,
  },
  {
    name: 'San Marino',
    cca2: 'SM',
    cca3: 'SMR',
    cioc: 'SMR',
    lat: 43.76666666,
    lng: 12.41666666,
  },
  {
    name: 'Gibraltar',
    cca2: 'GI',
    cca3: 'GIB',
    cioc: '',
    lat: 36.13333333,
    lng: -5.35,
  },
  {
    name: 'Djibouti',
    cca2: 'DJ',
    cca3: 'DJI',
    cioc: 'DJI',
    lat: 11.5,
    lng: 43,
  },
  { name: 'Guinea', cca2: 'GN', cca3: 'GIN', cioc: 'GUI', lat: 11, lng: -10 },
  { name: 'Finland', cca2: 'FI', cca3: 'FIN', cioc: 'FIN', lat: 64, lng: 26 },
  { name: 'Uruguay', cca2: 'UY', cca3: 'URY', cioc: 'URU', lat: -33, lng: -56 },
  { name: 'Thailand', cca2: 'TH', cca3: 'THA', cioc: 'THA', lat: 15, lng: 100 },
  {
    name: 'Sao Tome and Principe',
    cca2: 'ST',
    cca3: 'STP',
    cioc: 'STP',
    lat: 1,
    lng: 7,
  },
  {
    name: 'Seychelles',
    cca2: 'SC',
    cca3: 'SYC',
    cioc: 'SEY',
    lat: -4.58333333,
    lng: 55.66666666,
  },
  { name: 'Nepal', cca2: 'NP', cca3: 'NPL', cioc: 'NEP', lat: 28, lng: 84 },
  {
    name: 'Christmas Island',
    cca2: 'CX',
    cca3: 'CXR',
    cioc: '',
    lat: -10.5,
    lng: 105.66666666,
  },
  { name: 'Laos', cca2: 'LA', cca3: 'LAO', cioc: 'LAO', lat: 18, lng: 105 },
  { name: 'Yemen', cca2: 'YE', cca3: 'YEM', cioc: 'YEM', lat: 15, lng: 48 },
  {
    name: 'Bouvet Island',
    cca2: 'BV',
    cca3: 'BVT',
    cioc: '',
    lat: -54.43333333,
    lng: 3.4,
  },
  {
    name: 'South Africa',
    cca2: 'ZA',
    cca3: 'ZAF',
    cioc: 'RSA',
    lat: -29,
    lng: 24,
  },
  {
    name: 'Kiribati',
    cca2: 'KI',
    cca3: 'KIR',
    cioc: 'KIR',
    lat: 1.41666666,
    lng: 173,
  },
  {
    name: 'Philippines',
    cca2: 'PH',
    cca3: 'PHL',
    cioc: 'PHI',
    lat: 13,
    lng: 122,
  },
  {
    name: 'Sint Maarten',
    cca2: 'SX',
    cca3: 'SXM',
    cioc: '',
    lat: 18.033333,
    lng: -63.05,
  },
  { name: 'Romania', cca2: 'RO', cca3: 'ROU', cioc: 'ROU', lat: 46, lng: 25 },
  {
    name: 'United States Virgin Islands',
    cca2: 'VI',
    cca3: 'VIR',
    cioc: 'ISV',
    lat: 18.35,
    lng: -64.933333,
  },
  { name: 'Syria', cca2: 'SY', cca3: 'SYR', cioc: 'SYR', lat: 35, lng: 38 },
  {
    name: 'Macau',
    cca2: 'MO',
    cca3: 'MAC',
    cioc: '',
    lat: 22.16666666,
    lng: 113.55,
  },
  {
    name: 'Saint Martin',
    cca2: 'MF',
    cca3: 'MAF',
    cioc: '',
    lat: 18.08333333,
    lng: -63.95,
  },
  {
    name: 'Malta',
    cca2: 'MT',
    cca3: 'MLT',
    cioc: 'MLT',
    lat: 35.83333333,
    lng: 14.58333333,
  },
  {
    name: 'Kazakhstan',
    cca2: 'KZ',
    cca3: 'KAZ',
    cioc: 'KAZ',
    lat: 48,
    lng: 68,
  },
  {
    name: 'Turks and Caicos Islands',
    cca2: 'TC',
    cca3: 'TCA',
    cioc: '',
    lat: 21.75,
    lng: -71.58333333,
  },
  {
    name: 'French Polynesia',
    cca2: 'PF',
    cca3: 'PYF',
    cioc: '',
    lat: -15,
    lng: -140,
  },
  {
    name: 'Niue',
    cca2: 'NU',
    cca3: 'NIU',
    cioc: '',
    lat: -19.03333333,
    lng: -169.86666666,
  },
  {
    name: 'Dominica',
    cca2: 'DM',
    cca3: 'DMA',
    cioc: 'DMA',
    lat: 15.41666666,
    lng: -61.33333333,
  },
  { name: 'Benin', cca2: 'BJ', cca3: 'BEN', cioc: 'BEN', lat: 9.5, lng: 2.25 },
  {
    name: 'French Guiana',
    cca2: 'GF',
    cca3: 'GUF',
    cioc: '',
    lat: 4,
    lng: -53,
  },
  {
    name: 'Belgium',
    cca2: 'BE',
    cca3: 'BEL',
    cioc: 'BEL',
    lat: 50.83333333,
    lng: 4,
  },
  {
    name: 'Montserrat',
    cca2: 'MS',
    cca3: 'MSR',
    cioc: '',
    lat: 16.75,
    lng: -62.2,
  },
  {
    name: 'Togo',
    cca2: 'TG',
    cca3: 'TGO',
    cioc: 'TOG',
    lat: 8,
    lng: 1.16666666,
  },
  { name: 'Germany', cca2: 'DE', cca3: 'DEU', cioc: 'GER', lat: 51, lng: 9 },
  {
    name: 'Guam',
    cca2: 'GU',
    cca3: 'GUM',
    cioc: 'GUM',
    lat: 13.46666666,
    lng: 144.78333333,
  },
  { name: 'Sri Lanka', cca2: 'LK', cca3: 'LKA', cioc: 'SRI', lat: 7, lng: 81 },
  { name: 'South Sudan', cca2: 'SS', cca3: 'SSD', cioc: '', lat: 7, lng: 30 },
  {
    name: 'Falkland Islands',
    cca2: 'FK',
    cca3: 'FLK',
    cioc: '',
    lat: -51.75,
    lng: -59,
  },
  {
    name: 'United Kingdom',
    cca2: 'GB',
    cca3: 'GBR',
    cioc: 'GBR',
    lat: 54,
    lng: -2,
  },
  { name: 'Guyana', cca2: 'GY', cca3: 'GUY', cioc: 'GUY', lat: 5, lng: -59 },
  {
    name: 'Costa Rica',
    cca2: 'CR',
    cca3: 'CRI',
    cioc: 'CRC',
    lat: 10,
    lng: -84,
  },
  { name: 'Cameroon', cca2: 'CM', cca3: 'CMR', cioc: 'CMR', lat: 6, lng: 12 },
  { name: 'Morocco', cca2: 'MA', cca3: 'MAR', cioc: 'MAR', lat: 32, lng: -5 },
  {
    name: 'Northern Mariana Islands',
    cca2: 'MP',
    cca3: 'MNP',
    cioc: '',
    lat: 15.2,
    lng: 145.75,
  },
  {
    name: 'Lesotho',
    cca2: 'LS',
    cca3: 'LSO',
    cioc: 'LES',
    lat: -29.5,
    lng: 28.5,
  },
  { name: 'Hungary', cca2: 'HU', cca3: 'HUN', cioc: 'HUN', lat: 47, lng: 20 },
  {
    name: 'Turkmenistan',
    cca2: 'TM',
    cca3: 'TKM',
    cioc: 'TKM',
    lat: 40,
    lng: 60,
  },
  { name: 'Suriname', cca2: 'SR', cca3: 'SUR', cioc: 'SUR', lat: 4, lng: -56 },
  {
    name: 'Netherlands',
    cca2: 'NL',
    cca3: 'NLD',
    cioc: 'NED',
    lat: 52.5,
    lng: 5.75,
  },
  {
    name: 'Bermuda',
    cca2: 'BM',
    cca3: 'BMU',
    cioc: 'BER',
    lat: 32.33333333,
    lng: -64.75,
  },
  {
    name: 'Heard Island and McDonald Islands',
    cca2: 'HM',
    cca3: 'HMD',
    cioc: '',
    lat: -53.1,
    lng: 72.51666666,
  },
  { name: 'Chad', cca2: 'TD', cca3: 'TCD', cioc: 'CHA', lat: 15, lng: 19 },
  { name: 'Georgia', cca2: 'GE', cca3: 'GEO', cioc: 'GEO', lat: 42, lng: 43.5 },
  {
    name: 'Montenegro',
    cca2: 'ME',
    cca3: 'MNE',
    cioc: 'MNE',
    lat: 42.5,
    lng: 19.3,
  },
  { name: 'Mongolia', cca2: 'MN', cca3: 'MNG', cioc: 'MGL', lat: 46, lng: 105 },
  {
    name: 'Marshall Islands',
    cca2: 'MH',
    cca3: 'MHL',
    cioc: 'MHL',
    lat: 9,
    lng: 168,
  },
  {
    name: 'Martinique',
    cca2: 'MQ',
    cca3: 'MTQ',
    cioc: '',
    lat: 14.666667,
    lng: -61,
  },
  {
    name: 'Belize',
    cca2: 'BZ',
    cca3: 'BLZ',
    cioc: 'BIZ',
    lat: 17.25,
    lng: -88.75,
  },
  {
    name: 'Norfolk Island',
    cca2: 'NF',
    cca3: 'NFK',
    cioc: '',
    lat: -29.03333333,
    lng: 167.95,
  },
  { name: 'Myanmar', cca2: 'MM', cca3: 'MMR', cioc: 'MYA', lat: 22, lng: 98 },
  {
    name: 'Afghanistan',
    cca2: 'AF',
    cca3: 'AFG',
    cioc: 'AFG',
    lat: 33,
    lng: 65,
  },
  { name: 'Burundi', cca2: 'BI', cca3: 'BDI', cioc: 'BDI', lat: -3.5, lng: 30 },
  {
    name: 'British Virgin Islands',
    cca2: 'VG',
    cca3: 'VGB',
    cioc: 'IVB',
    lat: 18.431383,
    lng: -64.62305,
  },
  { name: 'Belarus', cca2: 'BY', cca3: 'BLR', cioc: 'BLR', lat: 53, lng: 28 },
  {
    name: 'Saint Barthelemy',
    cca2: 'BL',
    cca3: 'BLM',
    cioc: '',
    lat: 18.5,
    lng: -63.41666666,
  },
  {
    name: 'Grenada',
    cca2: 'GD',
    cca3: 'GRD',
    cioc: 'GRN',
    lat: 12.11666666,
    lng: -61.66666666,
  },
  { name: 'Tokelau', cca2: 'TK', cca3: 'TKL', cioc: '', lat: -9, lng: -172 },
  { name: 'Greece', cca2: 'GR', cca3: 'GRC', cioc: 'GRE', lat: 39, lng: 22 },
  { name: 'Russia', cca2: 'RU', cca3: 'RUS', cioc: 'RUS', lat: 60, lng: 100 },
  { name: 'Greenland', cca2: 'GL', cca3: 'GRL', cioc: '', lat: 72, lng: -40 },
  {
    name: 'Andorra',
    cca2: 'AD',
    cca3: 'AND',
    cioc: 'AND',
    lat: 42.5,
    lng: 1.5,
  },
  {
    name: 'Mozambique',
    cca2: 'MZ',
    cca3: 'MOZ',
    cioc: 'MOZ',
    lat: -18.25,
    lng: 35,
  },
  {
    name: 'Tajikistan',
    cca2: 'TJ',
    cca3: 'TJK',
    cioc: 'TJK',
    lat: 39,
    lng: 71,
  },
  {
    name: 'Haiti',
    cca2: 'HT',
    cca3: 'HTI',
    cioc: 'HAI',
    lat: 19,
    lng: -72.41666666,
  },
  { name: 'Mexico', cca2: 'MX', cca3: 'MEX', cioc: 'MEX', lat: 23, lng: -102 },
  { name: 'Zimbabwe', cca2: 'ZW', cca3: 'ZWE', cioc: 'ZIM', lat: -20, lng: 30 },
  {
    name: 'Saint Lucia',
    cca2: 'LC',
    cca3: 'LCA',
    cioc: 'LCA',
    lat: 13.88333333,
    lng: -60.96666666,
  },
  { name: 'India', cca2: 'IN', cca3: 'IND', cioc: 'IND', lat: 20, lng: 77 },
  { name: 'Latvia', cca2: 'LV', cca3: 'LVA', cioc: 'LAT', lat: 57, lng: 25 },
  {
    name: 'Bhutan',
    cca2: 'BT',
    cca3: 'BTN',
    cioc: 'BHU',
    lat: 27.5,
    lng: 90.5,
  },
  {
    name: 'Saint Vincent and the Grenadines',
    cca2: 'VC',
    cca3: 'VCT',
    cioc: 'VIN',
    lat: 13.25,
    lng: -61.2,
  },
  {
    name: 'Vietnam',
    cca2: 'VN',
    cca3: 'VNM',
    cioc: 'VIE',
    lat: 16.16666666,
    lng: 107.83333333,
  },
  { name: 'Norway', cca2: 'NO', cca3: 'NOR', cioc: 'NOR', lat: 62, lng: 10 },
  {
    name: 'Czech Republic',
    cca2: 'CZ',
    cca3: 'CZE',
    cioc: 'CZE',
    lat: 49.75,
    lng: 15.5,
  },
  {
    name: 'French Southern and Antarctic Lands',
    cca2: 'TF',
    cca3: 'ATF',
    cioc: '',
    lat: -49.25,
    lng: 69.167,
  },
  {
    name: 'Antigua and Barbuda',
    cca2: 'AG',
    cca3: 'ATG',
    cioc: 'ANT',
    lat: 17.05,
    lng: -61.8,
  },
  { name: 'Fiji', cca2: 'FJ', cca3: 'FJI', cioc: 'FIJ', lat: -18, lng: 175 },
  {
    name: 'British Indian Ocean Territory',
    cca2: 'IO',
    cca3: 'IOT',
    cioc: '',
    lat: -6,
    lng: 71.5,
  },
  {
    name: 'Honduras',
    cca2: 'HN',
    cca3: 'HND',
    cioc: 'HON',
    lat: 15,
    lng: -86.5,
  },
  {
    name: 'Mauritius',
    cca2: 'MU',
    cca3: 'MUS',
    cioc: 'MRI',
    lat: -20.28333333,
    lng: 57.55,
  },
  { name: 'Antarctica', cca2: 'AQ', cca3: 'ATA', cioc: '', lat: -90, lng: 0 },
  {
    name: 'Luxembourg',
    cca2: 'LU',
    cca3: 'LUX',
    cioc: 'LUX',
    lat: 49.75,
    lng: 6.16666666,
  },
  {
    name: 'Israel',
    cca2: 'IL',
    cca3: 'ISR',
    cioc: 'ISR',
    lat: 31.47,
    lng: 35.13,
  },
  {
    name: 'Micronesia',
    cca2: 'FM',
    cca3: 'FSM',
    cioc: 'FSM',
    lat: 6.91666666,
    lng: 158.25,
  },
  { name: 'Peru', cca2: 'PE', cca3: 'PER', cioc: 'PER', lat: -10, lng: -76 },
  {
    name: 'Reunion',
    cca2: 'RE',
    cca3: 'REU',
    cioc: '',
    lat: -21.15,
    lng: 55.5,
  },
  {
    name: 'Indonesia',
    cca2: 'ID',
    cca3: 'IDN',
    cioc: 'INA',
    lat: -5,
    lng: 120,
  },
  { name: 'Vanuatu', cca2: 'VU', cca3: 'VUT', cioc: 'VAN', lat: -16, lng: 167 },
  {
    name: 'Macedonia',
    cca2: 'MK',
    cca3: 'MKD',
    cioc: 'MKD',
    lat: 41.83333333,
    lng: 22,
  },
  { name: 'DR Congo', cca2: 'CD', cca3: 'COD', cioc: 'COD', lat: 0, lng: 25 },
  {
    name: 'Republic of the Congo',
    cca2: 'CG',
    cca3: 'COG',
    cioc: 'CGO',
    lat: -1,
    lng: 15,
  },
  { name: 'Iceland', cca2: 'IS', cca3: 'ISL', cioc: 'ISL', lat: 65, lng: -18 },
  {
    name: 'Guadeloupe',
    cca2: 'GP',
    cca3: 'GLP',
    cioc: '',
    lat: 16.25,
    lng: -61.583333,
  },
  {
    name: 'Cook Islands',
    cca2: 'CK',
    cca3: 'COK',
    cioc: 'COK',
    lat: -21.23333333,
    lng: -159.76666666,
  },
  {
    name: 'Comoros',
    cca2: 'KM',
    cca3: 'COM',
    cioc: 'COM',
    lat: -12.16666666,
    lng: 44.25,
  },
  { name: 'Colombia', cca2: 'CO', cca3: 'COL', cioc: 'COL', lat: 4, lng: -72 },
  { name: 'Nigeria', cca2: 'NG', cca3: 'NGA', cioc: 'NGR', lat: 10, lng: 8 },
  {
    name: 'Timor-Leste',
    cca2: 'TL',
    cca3: 'TLS',
    cioc: 'TLS',
    lat: -8.83333333,
    lng: 125.91666666,
  },
  { name: 'Taiwan', cca2: 'TW', cca3: 'TWN', cioc: 'TPE', lat: 23.5, lng: 121 },
  {
    name: 'Portugal',
    cca2: 'PT',
    cca3: 'PRT',
    cioc: 'POR',
    lat: 39.5,
    lng: -8,
  },
  { name: 'Moldova', cca2: 'MD', cca3: 'MDA', cioc: 'MDA', lat: 47, lng: 29 },
  {
    name: 'Guernsey',
    cca2: 'GG',
    cca3: 'GGY',
    cioc: '',
    lat: 49.46666666,
    lng: -2.58333333,
  },
  {
    name: 'Madagascar',
    cca2: 'MG',
    cca3: 'MDG',
    cioc: 'MAD',
    lat: -20,
    lng: 47,
  },
  {
    name: 'Ecuador',
    cca2: 'EC',
    cca3: 'ECU',
    cioc: 'ECU',
    lat: -2,
    lng: -77.5,
  },
  { name: 'Senegal', cca2: 'SN', cca3: 'SEN', cioc: 'SEN', lat: 14, lng: -14 },
  {
    name: 'New Zealand',
    cca2: 'NZ',
    cca3: 'NZL',
    cioc: 'NZL',
    lat: -41,
    lng: 174,
  },
  {
    name: 'Maldives',
    cca2: 'MV',
    cca3: 'MDV',
    cioc: 'MDV',
    lat: 3.25,
    lng: 73,
  },
  {
    name: 'American Samoa',
    cca2: 'AS',
    cca3: 'ASM',
    cioc: 'ASA',
    lat: -14.33333333,
    lng: -170,
  },
  {
    name: 'Saint Pierre and Miquelon',
    cca2: 'PM',
    cca3: 'SPM',
    cioc: '',
    lat: 46.83333333,
    lng: -56.33333333,
  },
  {
    name: 'Curacao',
    cca2: 'CW',
    cca3: 'CUW',
    cioc: '',
    lat: 12.116667,
    lng: -68.933333,
  },
  { name: 'France', cca2: 'FR', cca3: 'FRA', cioc: 'FRA', lat: 46, lng: 2 },
  { name: 'Lithuania', cca2: 'LT', cca3: 'LTU', cioc: 'LTU', lat: 56, lng: 24 },
  { name: 'Rwanda', cca2: 'RW', cca3: 'RWA', cioc: 'RWA', lat: -2, lng: 30 },
  { name: 'Zambia', cca2: 'ZM', cca3: 'ZMB', cioc: 'ZAM', lat: -15, lng: 30 },
  {
    name: 'Gambia',
    cca2: 'GM',
    cca3: 'GMB',
    cioc: 'GAM',
    lat: 13.46666666,
    lng: -16.56666666,
  },
  {
    name: 'Wallis and Futuna',
    cca2: 'WF',
    cca3: 'WLF',
    cioc: '',
    lat: -13.3,
    lng: -176.2,
  },
  {
    name: 'Jersey',
    cca2: 'JE',
    cca3: 'JEY',
    cioc: '',
    lat: 49.25,
    lng: -2.16666666,
  },
  {
    name: 'Faroe Islands',
    cca2: 'FO',
    cca3: 'FRO',
    cioc: '',
    lat: 62,
    lng: -7,
  },
  {
    name: 'Guatemala',
    cca2: 'GT',
    cca3: 'GTM',
    cioc: 'GUA',
    lat: 15.5,
    lng: -90.25,
  },
  { name: 'Denmark', cca2: 'DK', cca3: 'DNK', cioc: 'DEN', lat: 56, lng: 10 },
  {
    name: 'Isle of Man',
    cca2: 'IM',
    cca3: 'IMN',
    cioc: '',
    lat: 54.25,
    lng: -4.5,
  },
  {
    name: 'Australia',
    cca2: 'AU',
    cca3: 'AUS',
    cioc: 'AUS',
    lat: -27,
    lng: 133,
  },
  {
    name: 'Austria',
    cca2: 'AT',
    cca3: 'AUT',
    cioc: 'AUT',
    lat: 47.33333333,
    lng: 13.33333333,
  },
  {
    name: 'Svalbard and Jan Mayen',
    cca2: 'SJ',
    cca3: 'SJM',
    cioc: '',
    lat: 78,
    lng: 20,
  },
  { name: 'Venezuela', cca2: 'VE', cca3: 'VEN', cioc: 'VEN', lat: 8, lng: -66 },
  {
    name: 'Kosovo',
    cca2: 'XK',
    cca3: 'UNK',
    cioc: 'KOS',
    lat: 42.666667,
    lng: 21.166667,
  },
  { name: 'Palau', cca2: 'PW', cca3: 'PLW', cioc: 'PLW', lat: 7.5, lng: 134.5 },
  { name: 'Kenya', cca2: 'KE', cca3: 'KEN', cioc: 'KEN', lat: 1, lng: 38 },
  {
    name: 'Samoa',
    cca2: 'WS',
    cca3: 'WSM',
    cioc: 'SAM',
    lat: -13.58333333,
    lng: -172.33333333,
  },
  { name: 'Turkey', cca2: 'TR', cca3: 'TUR', cioc: 'TUR', lat: 39, lng: 35 },
  { name: 'Albania', cca2: 'AL', cca3: 'ALB', cioc: 'ALB', lat: 41, lng: 20 },
  { name: 'Oman', cca2: 'OM', cca3: 'OMN', cioc: 'OMA', lat: 21, lng: 57 },
  { name: 'Tuvalu', cca2: 'TV', cca3: 'TUV', cioc: 'TUV', lat: -8, lng: 178 },
  {
    name: 'Aland Islands',
    cca2: 'AX',
    cca3: 'ALA',
    cioc: '',
    lat: 60.116667,
    lng: 19.9,
  },
  {
    name: 'Brunei',
    cca2: 'BN',
    cca3: 'BRN',
    cioc: 'BRU',
    lat: 4.5,
    lng: 114.66666666,
  },
  { name: 'Tunisia', cca2: 'TN', cca3: 'TUN', cioc: 'TUN', lat: 34, lng: 9 },
  {
    name: 'Pitcairn Islands',
    cca2: 'PN',
    cca3: 'PCN',
    cioc: '',
    lat: -25.06666666,
    lng: -130.1,
  },
  {
    name: 'Barbados',
    cca2: 'BB',
    cca3: 'BRB',
    cioc: 'BAR',
    lat: 13.16666666,
    lng: -59.53333333,
  },
  { name: 'Brazil', cca2: 'BR', cca3: 'BRA', cioc: 'BRA', lat: -10, lng: -55 },
  {
    name: 'Ivory Coast',
    cca2: 'CI',
    cca3: 'CIV',
    cioc: 'CIV',
    lat: 8,
    lng: -5,
  },
  { name: 'Serbia', cca2: 'RS', cca3: 'SRB', cioc: 'SRB', lat: 44, lng: 21 },
  {
    name: 'Equatorial Guinea',
    cca2: 'GQ',
    cca3: 'GNQ',
    cioc: 'GEQ',
    lat: 2,
    lng: 10,
  },
  {
    name: 'United States',
    cca2: 'US',
    cca3: 'USA',
    cioc: 'USA',
    lat: 38,
    lng: -97,
  },
  {
    name: 'Qatar',
    cca2: 'QA',
    cca3: 'QAT',
    cioc: 'QAT',
    lat: 25.5,
    lng: 51.25,
  },
  { name: 'Sweden', cca2: 'SE', cca3: 'SWE', cioc: 'SWE', lat: 62, lng: 15 },
  {
    name: 'Azerbaijan',
    cca2: 'AZ',
    cca3: 'AZE',
    cioc: 'AZE',
    lat: 40.5,
    lng: 47.5,
  },
  {
    name: 'Guinea-Bissau',
    cca2: 'GW',
    cca3: 'GNB',
    cioc: 'GBS',
    lat: 12,
    lng: -15,
  },
  {
    name: 'Swaziland',
    cca2: 'SZ',
    cca3: 'SWZ',
    cioc: 'SWZ',
    lat: -26.5,
    lng: 31.5,
  },
  { name: 'Tonga', cca2: 'TO', cca3: 'TON', cioc: 'TGA', lat: -20, lng: -175 },
  { name: 'Canada', cca2: 'CA', cca3: 'CAN', cioc: 'CAN', lat: 60, lng: -95 },
  { name: 'Ukraine', cca2: 'UA', cca3: 'UKR', cioc: 'UKR', lat: 49, lng: 32 },
  {
    name: 'South Korea',
    cca2: 'KR',
    cca3: 'KOR',
    cioc: 'KOR',
    lat: 37,
    lng: 127.5,
  },
  {
    name: 'Anguilla',
    cca2: 'AI',
    cca3: 'AIA',
    cioc: '',
    lat: 18.25,
    lng: -63.16666666,
  },
  {
    name: 'Central African Republic',
    cca2: 'CF',
    cca3: 'CAF',
    cioc: 'CAF',
    lat: 7,
    lng: 21,
  },
  {
    name: 'Slovakia',
    cca2: 'SK',
    cca3: 'SVK',
    cioc: 'SVK',
    lat: 48.66666666,
    lng: 19.5,
  },
  { name: 'Cyprus', cca2: 'CY', cca3: 'CYP', cioc: 'CYP', lat: 35, lng: 33 },
  {
    name: 'Bosnia and Herzegovina',
    cca2: 'BA',
    cca3: 'BIH',
    cioc: 'BIH',
    lat: 44,
    lng: 18,
  },
  {
    name: 'Singapore',
    cca2: 'SG',
    cca3: 'SGP',
    cioc: 'SIN',
    lat: 1.36666666,
    lng: 103.8,
  },
  {
    name: 'South Georgia',
    cca2: 'GS',
    cca3: 'SGS',
    cioc: '',
    lat: -54.5,
    lng: -37,
  },
  { name: 'Somalia', cca2: 'SO', cca3: 'SOM', cioc: 'SOM', lat: 10, lng: 49 },
  {
    name: 'Uzbekistan',
    cca2: 'UZ',
    cca3: 'UZB',
    cioc: 'UZB',
    lat: 41,
    lng: 64,
  },
  { name: 'Eritrea', cca2: 'ER', cca3: 'ERI', cioc: 'ERI', lat: 15, lng: 39 },
  { name: 'Poland', cca2: 'PL', cca3: 'POL', cioc: 'POL', lat: 52, lng: 20 },
  {
    name: 'Kuwait',
    cca2: 'KW',
    cca3: 'KWT',
    cioc: 'KUW',
    lat: 29.5,
    lng: 45.75,
  },
  { name: 'Gabon', cca2: 'GA', cca3: 'GAB', cioc: 'GAB', lat: -1, lng: 11.75 },
  {
    name: 'Cayman Islands',
    cca2: 'KY',
    cca3: 'CYM',
    cioc: 'CAY',
    lat: 19.5,
    lng: -80.5,
  },
  {
    name: 'Vatican City',
    cca2: 'VA',
    cca3: 'VAT',
    cioc: '',
    lat: 41.9,
    lng: 12.45,
  },
  { name: 'Estonia', cca2: 'EE', cca3: 'EST', cioc: 'EST', lat: 59, lng: 26 },
  { name: 'Malawi', cca2: 'MW', cca3: 'MWI', cioc: 'MAW', lat: -13.5, lng: 34 },
  { name: 'Spain', cca2: 'ES', cca3: 'ESP', cioc: 'ESP', lat: 40, lng: -4 },
  { name: 'Iraq', cca2: 'IQ', cca3: 'IRQ', cioc: 'IRQ', lat: 33, lng: 44 },
  {
    name: 'El Salvador',
    cca2: 'SV',
    cca3: 'SLV',
    cioc: 'ESA',
    lat: 13.83333333,
    lng: -88.91666666,
  },
  { name: 'Mali', cca2: 'ML', cca3: 'MLI', cioc: 'MLI', lat: 17, lng: -4 },
  { name: 'Ireland', cca2: 'IE', cca3: 'IRL', cioc: 'IRL', lat: 53, lng: -8 },
  { name: 'Iran', cca2: 'IR', cca3: 'IRN', cioc: 'IRI', lat: 32, lng: 53 },
  {
    name: 'Aruba',
    cca2: 'AW',
    cca3: 'ABW',
    cioc: 'ARU',
    lat: 12.5,
    lng: -69.96666666,
  },
  {
    name: 'Papua New Guinea',
    cca2: 'PG',
    cca3: 'PNG',
    cioc: 'PNG',
    lat: -6,
    lng: 147,
  },
  { name: 'Panama', cca2: 'PA', cca3: 'PAN', cioc: 'PAN', lat: 9, lng: -80 },
  { name: 'Sudan', cca2: 'SD', cca3: 'SDN', cioc: 'SUD', lat: 15, lng: 30 },
  {
    name: 'Solomon Islands',
    cca2: 'SB',
    cca3: 'SLB',
    cioc: 'SOL',
    lat: -8,
    lng: 159,
  },
  {
    name: 'Western Sahara',
    cca2: 'EH',
    cca3: 'ESH',
    cioc: '',
    lat: 24.5,
    lng: -13,
  },
  {
    name: 'Monaco',
    cca2: 'MC',
    cca3: 'MCO',
    cioc: 'MON',
    lat: 43.73333333,
    lng: 7.4,
  },
  {
    name: 'Italy',
    cca2: 'IT',
    cca3: 'ITA',
    cioc: 'ITA',
    lat: 42.83333333,
    lng: 12.83333333,
  },
  { name: 'Japan', cca2: 'JP', cca3: 'JPN', cioc: 'JPN', lat: 36, lng: 138 },
  {
    name: 'Kyrgyzstan',
    cca2: 'KG',
    cca3: 'KGZ',
    cioc: 'KGZ',
    lat: 41,
    lng: 75,
  },
  { name: 'Uganda', cca2: 'UG', cca3: 'UGA', cioc: 'UGA', lat: 1, lng: 32 },
  {
    name: 'New Caledonia',
    cca2: 'NC',
    cca3: 'NCL',
    cioc: '',
    lat: -21.5,
    lng: 165.5,
  },
  {
    name: 'United Arab Emirates',
    cca2: 'AE',
    cca3: 'ARE',
    cioc: 'UAE',
    lat: 24,
    lng: 54,
  },
  {
    name: 'Argentina',
    cca2: 'AR',
    cca3: 'ARG',
    cioc: 'ARG',
    lat: -34,
    lng: -64,
  },
  {
    name: 'Bahamas',
    cca2: 'BS',
    cca3: 'BHS',
    cioc: 'BAH',
    lat: 24.25,
    lng: -76,
  },
  {
    name: 'Bahrain',
    cca2: 'BH',
    cca3: 'BHR',
    cioc: 'BRN',
    lat: 26,
    lng: 50.55,
  },
  { name: 'Armenia', cca2: 'AM', cca3: 'ARM', cioc: 'ARM', lat: 40, lng: 45 },
  {
    name: 'Nauru',
    cca2: 'NR',
    cca3: 'NRU',
    cioc: 'NRU',
    lat: -0.53333333,
    lng: 166.91666666,
  },
  { name: 'Cuba', cca2: 'CU', cca3: 'CUB', cioc: 'CUB', lat: 21.5, lng: -80 },
];

const lookups: Record<CountryFieldType, Map<string, CountryInfo>> = {
  name: new Map(),
  cca2: new Map(),
  cca3: new Map(),
  cioc: new Map(),
};
(Object.keys(lookups) as CountryFieldType[]).forEach(field => {
  countries.forEach(country => {
    lookups[field].set(country[field].toLowerCase(), country);
  });
});

/**
 * Case-insensitive country lookup by a supported code convention,
 * mirroring superset/examples/countries.py `get()`.
 */
export default function getCountry(
  field: CountryFieldType,
  symbol: string,
): CountryInfo | undefined {
  return lookups[field]?.get(symbol.toLowerCase());
}
