(function () {var enterModule = typeof reactHotLoaderGlobal !== 'undefined' ? reactHotLoaderGlobal.enterModule : undefined;enterModule && enterModule(module);})();var __signature__ = typeof reactHotLoaderGlobal !== 'undefined' ? reactHotLoaderGlobal.default.signature : function (a) {return a;};























export let Behavior;(function (Behavior) {Behavior["INTERACTIVE_CHART"] = "INTERACTIVE_CHART";Behavior["NATIVE_FILTER"] = "NATIVE_FILTER";})(Behavior || (Behavior = {}));




export let AppSection;(function (AppSection) {AppSection["EXPLORE"] = "EXPLORE";AppSection["DASHBOARD"] = "DASHBOARD";AppSection["FILTER_BAR"] = "FILTER_BAR";AppSection["FILTER_CONFIG_MODAL"] = "FILTER_CONFIG_MODAL";AppSection["EMBEDDED"] = "EMBEDDED";})(AppSection || (AppSection = {}));const _default =
























{};export default _default;;(function () {var reactHotLoader = typeof reactHotLoaderGlobal !== 'undefined' ? reactHotLoaderGlobal.default : undefined;if (!reactHotLoader) {return;}reactHotLoader.register(_default, "default", "/Users/evan/GitHub/superset/superset-frontend/packages/superset-ui-core/src/chart/types/Base.ts");})();;(function () {var leaveModule = typeof reactHotLoaderGlobal !== 'undefined' ? reactHotLoaderGlobal.leaveModule : undefined;leaveModule && leaveModule(module);})();