import {
  PROD_DODOPIZZA,
  PROD_DODOPIZZA_COMMON_DASHBOARDS,
  PROD_DODOPIZZA_MAIN_MENU_HELPER,
  PROD_DODOPIZZA_AVAILABLE_EXTRA,
  PROD_DODOPIZZA_AVAILABLE_ROLES,
} from './DODOPIZZA';

import {
  PROD_DRINKIT,
  PROD_DRINKIT_COMMON_DASHBOARDS,
  PROD_DRINKIT_MAIN_MENU_HELPER,
  PROD_DRINKIT_AVAILABLE_EXTRA,
  PROD_DRINKIT_AVAILABLE_ROLES,
} from './DRINKIT';

import {
  PROD_DONER42,
  PROD_DONER42_COMMON_DASHBOARDS,
  PROD_DONER42_MAIN_MENU_HELPER,
  PROD_DONER42_AVAILABLE_EXTRA,
  PROD_DONER42_AVAILABLE_ROLES,
} from './DONER42';

const PROD = {
  dodopizza: {
    CONFIGURATION: PROD_DODOPIZZA,
    COMMON_DASHBOARDS: PROD_DODOPIZZA_COMMON_DASHBOARDS,
    MAIN_MENU_HELPER: PROD_DODOPIZZA_MAIN_MENU_HELPER,
    AVAILABLE_EXTRA: PROD_DODOPIZZA_AVAILABLE_EXTRA,
    AVAILABLE_ROLES: PROD_DODOPIZZA_AVAILABLE_ROLES,
  },
  drinkit: {
    CONFIGURATION: PROD_DRINKIT,
    COMMON_DASHBOARDS: PROD_DRINKIT_COMMON_DASHBOARDS,
    MAIN_MENU_HELPER: PROD_DRINKIT_MAIN_MENU_HELPER,
    AVAILABLE_EXTRA: PROD_DRINKIT_AVAILABLE_EXTRA,
    AVAILABLE_ROLES: PROD_DRINKIT_AVAILABLE_ROLES,
  },
  doner42: {
    CONFIGURATION: PROD_DONER42,
    COMMON_DASHBOARDS: PROD_DONER42_COMMON_DASHBOARDS,
    MAIN_MENU_HELPER: PROD_DONER42_MAIN_MENU_HELPER,
    AVAILABLE_EXTRA: PROD_DONER42_AVAILABLE_EXTRA,
    AVAILABLE_ROLES: PROD_DONER42_AVAILABLE_ROLES,
  },
};

export { PROD };
