import {
  DEV_DODOPIZZA,
  DEV_DODOPIZZA_COMMON_DASHBOARDS,
  DEV_DODOPIZZA_MAIN_MENU_HELPER,
  DEV_DODOPIZZA_AVAILABLE_EXTRA,
  DEV_DODOPIZZA_AVAILABLE_ROLES,
} from './DODOPIZZA';

import {
  DEV_DRINKIT,
  DEV_DRINKIT_COMMON_DASHBOARDS,
  DEV_DRINKIT_MAIN_MENU_HELPER,
  DEV_DRINKIT_AVAILABLE_EXTRA,
  DEV_DRINKIT_AVAILABLE_ROLES,
} from './DRINKIT';

import {
  DEV_DONER42,
  DEV_DONER42_COMMON_DASHBOARDS,
  DEV_DONER42_MAIN_MENU_HELPER,
  DEV_DONER42_AVAILABLE_EXTRA,
  DEV_DONER42_AVAILABLE_ROLES,
} from './DONER42';

const DEV = {
  dodopizza: {
    CONFIGURATION: DEV_DODOPIZZA,
    COMMON_DASHBOARDS: DEV_DODOPIZZA_COMMON_DASHBOARDS,
    MAIN_MENU_HELPER: DEV_DODOPIZZA_MAIN_MENU_HELPER,
    AVAILABLE_EXTRA: DEV_DODOPIZZA_AVAILABLE_EXTRA,
    AVAILABLE_ROLES: DEV_DODOPIZZA_AVAILABLE_ROLES,
  },
  drinkit: {
    CONFIGURATION: DEV_DRINKIT,
    COMMON_DASHBOARDS: DEV_DRINKIT_COMMON_DASHBOARDS,
    MAIN_MENU_HELPER: DEV_DRINKIT_MAIN_MENU_HELPER,
    AVAILABLE_EXTRA: DEV_DRINKIT_AVAILABLE_EXTRA,
    AVAILABLE_ROLES: DEV_DRINKIT_AVAILABLE_ROLES,
  },
  doner42: {
    CONFIGURATION: DEV_DONER42,
    COMMON_DASHBOARDS: DEV_DONER42_COMMON_DASHBOARDS,
    MAIN_MENU_HELPER: DEV_DONER42_MAIN_MENU_HELPER,
    AVAILABLE_EXTRA: DEV_DONER42_AVAILABLE_EXTRA,
    AVAILABLE_ROLES: DEV_DONER42_AVAILABLE_ROLES,
  },
};

export { DEV };
