export enum LabelPositionDoDo {
  left = 'left',
  right = 'right',
  top = 'top',
  bottom = 'bottom',
  inside = 'inside',
  insideTop = 'insideTop',
  insideLeft = 'insideLeft',
  insideRight = 'insideRight',
  insideBottom = 'insideBottom',
  insideTopLeft = 'insideTopLeft',
  insideTopRight = 'insideTopRight',
  insideBottomLeft = 'insideBottomLeft',
  insideBottomRight = 'insideBottomRight',
}
