/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface AdvancedDataTypeSchema {
  /** The string representation of the parsed values */
  display_value?: string;
  error_message?: string;
  valid_filter_operators?: string[];
  values?: string[];
}
