/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Type of source for annotation data
 */
export type AnnotationLayerSourceType =
  (typeof AnnotationLayerSourceType)[keyof typeof AnnotationLayerSourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnnotationLayerSourceType = {
  '': '',
  line: 'line',
  NATIVE: 'NATIVE',
  table: 'table',
} as const;
