/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { AnnotationLayerAnnotationType } from './annotationLayerAnnotationType';
import type { AnnotationLayerOpacity } from './annotationLayerOpacity';
import type { AnnotationLayerOverrides } from './annotationLayerOverrides';
import type { AnnotationLayerSourceType } from './annotationLayerSourceType';
import type { AnnotationLayerStyle } from './annotationLayerStyle';

export interface AnnotationLayer {
  /** Type of annotation layer */
  annotationType?: AnnotationLayerAnnotationType;
  /**
   * Layer color
   * @nullable
   */
  color?: string | null;
  /** Columns to use as the description. If none are provided, all will be shown. */
  descriptionColumns?: string[];
  /**
   * Should line be hidden. Only applies to line annotations
   * @nullable
   */
  hideLine?: boolean | null;
  /**
   * Column containing end of interval. Only applies to interval layers
   * @nullable
   */
  intervalEndColumn?: string | null;
  /** Name of layer */
  name: string;
  /**
   * Opacity of layer
   * @nullable
   */
  opacity?: AnnotationLayerOpacity;
  /**
   * which properties should be overridable
   * @nullable
   */
  overrides?: AnnotationLayerOverrides;
  /** Should the layer be shown */
  show: boolean;
  /**
   * Should the label always be shown
   * @nullable
   */
  showLabel?: boolean | null;
  /** Should markers be shown. Only applies to line annotations. */
  showMarkers: boolean;
  /** Type of source for annotation data */
  sourceType?: AnnotationLayerSourceType;
  /** Line style. Only applies to time-series annotations */
  style?: AnnotationLayerStyle;
  /**
   * Column with event date or interval start date
   * @nullable
   */
  timeColumn?: string | null;
  /**
   * Column with title
   * @nullable
   */
  titleColumn?: string | null;
  /** For formula annotations, this contains the formula. For other types, this is the primary key of the source object. */
  value: unknown;
  /**
   * Width of annotation line
   * @minimum 0
   */
  width?: number;
}
