/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface AnnotationRestApiPost {
  /** The annotation end date time */
  end_dttm: string;
  /**
   * JSON metadata
   * @nullable
   */
  json_metadata?: string | null;
  /**
   * A long description
   * @nullable
   */
  long_descr?: string | null;
  /**
   * A short description
   * @minLength 1
   * @maxLength 500
   */
  short_descr: string;
  /** The annotation start date time */
  start_dttm: string;
}
