/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface AnnotationLayerRestApiPost {
  /**
   * Give a description for this annotation layer
   * @nullable
   */
  descr?: string | null;
  /**
   * The annotation layer name
   * @minLength 1
   * @maxLength 250
   */
  name: string;
}
