/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Opacity of layer
 * @nullable
 */
export type AnnotationLayerOpacity =
  | (typeof AnnotationLayerOpacity)[keyof typeof AnnotationLayerOpacity]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnnotationLayerOpacity = {
  '': '',
  opacityLow: 'opacityLow',
  opacityMedium: 'opacityMedium',
  opacityHigh: 'opacityHigh',
} as const;
