/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { AnnotationRestApiGetAnnotationLayer } from './annotationRestApiGetAnnotationLayer';

export interface AnnotationRestApiGet {
  /** @nullable */
  end_dttm?: string | null;
  id?: number;
  /** @nullable */
  json_metadata?: string | null;
  layer: AnnotationRestApiGetAnnotationLayer;
  /** @nullable */
  long_descr?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  short_descr?: string | null;
  /** @nullable */
  start_dttm?: string | null;
}
