/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Type of annotation layer
 */
export type AnnotationLayerAnnotationType =
  (typeof AnnotationLayerAnnotationType)[keyof typeof AnnotationLayerAnnotationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnnotationLayerAnnotationType = {
  FORMULA: 'FORMULA',
  INTERVAL: 'INTERVAL',
  EVENT: 'EVENT',
  TIME_SERIES: 'TIME_SERIES',
} as const;
