/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Line style. Only applies to time-series annotations
 */
export type AnnotationLayerStyle =
  (typeof AnnotationLayerStyle)[keyof typeof AnnotationLayerStyle];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnnotationLayerStyle = {
  dashed: 'dashed',
  dotted: 'dotted',
  solid: 'solid',
  longDashed: 'longDashed',
} as const;
