/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartDataPivotOptionsSchemaAggregates } from './chartDataPivotOptionsSchemaAggregates';

export interface ChartDataPivotOptionsSchema {
  /** The keys are the name of the aggregate column to be created, and the values specify the details of how to apply the aggregation. If an operator requires additional options, these can be passed here to be unpacked in the operator call. The following numpy operators are supported: average, argmin, argmax, cumsum, cumprod, max, mean, median, nansum, nanmin, nanmax, nanmean, nanmedian, min, percentile, prod, product, std, sum, var. Any options required by the operator can be passed to the `options` object.

In the example, a new column `first_quantile` is created based on values in the column `my_col` using the `percentile` operator with the `q=0.25` parameter. */
  aggregates?: ChartDataPivotOptionsSchemaAggregates;
  /** Value to replace missing pivot columns names with. */
  column_fill_value?: string;
  /** Columns to group by on the table columns */
  columns?: string[];
  /** Do not include columns whose entries are all missing (default: `true`). */
  drop_missing_columns?: boolean;
  /** Name of marginal distribution row/column. (default: `All`) */
  marginal_distribution_name?: string;
  /** Add totals for row/column. (default: `false`) */
  marginal_distributions?: boolean;
  /** Value to replace missing values with in aggregate calculations. */
  metric_fill_value?: number;
}
