/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Datasource type
 */
export type ChartDataDatasourceType =
  (typeof ChartDataDatasourceType)[keyof typeof ChartDataDatasourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChartDataDatasourceType = {
  table: 'table',
  dataset: 'dataset',
  query: 'query',
  saved_query: 'saved_query',
  view: 'view',
} as const;
