/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset Charts API
 * OpenAPI spec version: 1.0.0
 */

export interface ChartCreatePayload {
  slice_name: string;
  description?: string;
  viz_type: string;
  params?: string;
  cache_timeout?: number;
  datasource_id: number;
  datasource_type: string;
  owners?: number[];
}
