/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface ChartRestApiGetListSqlaTable {
  /** @nullable */
  default_endpoint?: string | null;
  /** @maxLength 250 */
  table_name: string;
}
