/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartDataResponseResult } from './chartDataResponseResult';

export interface ChartDataResponseSchema {
  /** A list of results for each corresponding query in the request. */
  result?: ChartDataResponseResult[];
}
