/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface ChartDataAsyncResponseSchema {
  /** Unique session async channel ID */
  channel_id?: string;
  /** Unique async job ID */
  job_id?: string;
  /** Unique result URL for fetching async query data */
  result_url?: string;
  /** Status value for async job */
  status?: string;
  /**
   * Requesting user ID
   * @nullable
   */
  user_id?: string | null;
}
