/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Status of the query
 */
export type ChartDataResponseResultStatus =
  (typeof ChartDataResponseResultStatus)[keyof typeof ChartDataResponseResultStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChartDataResponseResultStatus = {
  stopped: 'stopped',
  failed: 'failed',
  pending: 'pending',
  running: 'running',
  scheduled: 'scheduled',
  success: 'success',
  timed_out: 'timed_out',
} as const;
