/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * A mapping of temporal extras that have been applied to the query
 * @nullable
 */
export type ChartDataQueryObjectAppliedTimeExtras = {
  [key: string]: unknown;
} | null;
