/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface ChartGetDatasourceObjectDataResponse {
  /** The datasource identifier */
  datasource_id?: number;
  /** The datasource type */
  datasource_type?: number;
}
