/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartDataExtrasRelativeEnd } from './chartDataExtrasRelativeEnd';
import type { ChartDataExtrasRelativeStart } from './chartDataExtrasRelativeStart';
import type { ChartDataExtrasTimeGrainSqla } from './chartDataExtrasTimeGrainSqla';

export interface ChartDataExtras {
  /** HAVING clause to be added to aggregate queries using AND operator. */
  having?: string;
  /**
   * This is only set using the new time comparison controls that is made available in some plugins behind the experimental feature flag.
   * @nullable
   */
  instant_time_comparison_range?: string | null;
  /** End time for relative time deltas. Default: `config["DEFAULT_RELATIVE_START_TIME"]` */
  relative_end?: ChartDataExtrasRelativeEnd;
  /** Start time for relative time deltas. Default: `config["DEFAULT_RELATIVE_START_TIME"]` */
  relative_start?: ChartDataExtrasRelativeStart;
  /**
   * To what level of granularity should the temporal column be aggregated. Supports [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations) durations.
   * @nullable
   */
  time_grain_sqla?: ChartDataExtrasTimeGrainSqla;
  /** WHERE clause to be added to queries using AND operator. */
  where?: string;
}
