/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset Charts API
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface Chart {
  id?: number;
  slice_name?: string;
  description?: string;
  viz_type?: string;
  params?: string;
  query_context?: string;
  cache_timeout?: number;
  datasource_id?: number;
  datasource_type?: string;
  datasource_name?: string;
  owners?: User[];
}
