/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartRestApiPostDatasourceType } from './chartRestApiPostDatasourceType';

export interface ChartRestApiPost {
  /**
   * Duration (in seconds) of the caching timeout for this chart. Note this defaults to the datasource/table timeout if undefined.
   * @nullable
   */
  cache_timeout?: number | null;
  /**
   * Details of the certification
   * @nullable
   */
  certification_details?: string | null;
  /**
   * Person or group that has certified this chart
   * @nullable
   */
  certified_by?: string | null;
  dashboards?: number[];
  /** The id of the dataset/datasource this new chart will use. A complete datasource identification needs `datasource_id` and `datasource_type`. */
  datasource_id: number;
  /**
   * The datasource name.
   * @nullable
   */
  datasource_name?: string | null;
  /** The type of dataset/datasource identified on `datasource_id`. */
  datasource_type: ChartRestApiPostDatasourceType;
  /**
   * A description of the chart propose.
   * @nullable
   */
  description?: string | null;
  /** @nullable */
  external_url?: string | null;
  /** @nullable */
  is_managed_externally?: boolean | null;
  owners?: number[];
  /**
   * Parameters are generated dynamically when clicking the save or overwrite button in the explore view. This JSON object for power users who may want to alter specific parameters.
   * @nullable
   */
  params?: string | null;
  /**
   * The query context represents the queries that need to run in order to generate the data the visualization, and in what format the data should be returned.
   * @nullable
   */
  query_context?: string | null;
  /**
   * The query context generation represents whether the query_contextis user generated or not so that it does not update user modifiedstate.
   * @nullable
   */
  query_context_generation?: boolean | null;
  /**
   * The name of the chart.
   * @minLength 1
   * @maxLength 250
   */
  slice_name: string;
  /** @nullable */
  uuid?: string | null;
  /**
   * The type of chart visualization used.
   * @minLength 0
   * @maxLength 250
   */
  viz_type?: string;
}
