/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type ChartDataQueryContextSchemaFormData = unknown | null;
