/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartDataResponseResultAnnotationDataItem } from './chartDataResponseResultAnnotationDataItem';
import type { ChartDataResponseResultAppliedFiltersItem } from './chartDataResponseResultAppliedFiltersItem';
import type { ChartDataResponseResultDataItem } from './chartDataResponseResultDataItem';
import type { ChartDataResponseResultRejectedFiltersItem } from './chartDataResponseResultRejectedFiltersItem';
import type { ChartDataResponseResultStatus } from './chartDataResponseResultStatus';

export interface ChartDataResponseResult {
  /**
   * All requested annotation data
   * @nullable
   */
  annotation_data?: ChartDataResponseResultAnnotationDataItem[] | null;
  /** A list with applied filters */
  applied_filters?: ChartDataResponseResultAppliedFiltersItem[];
  /**
   * Unique cache key for query object
   * @nullable
   */
  cache_key: string | null;
  /**
   * Cache timeout in following order: custom timeout, datasource timeout, cache default timeout, config default cache timeout.
   * @nullable
   */
  cache_timeout: number | null;
  /**
   * Cache timestamp
   * @nullable
   */
  cached_dttm: string | null;
  /** A list of column names */
  colnames?: string[];
  /** A list of generic data types of each column */
  coltypes?: number[];
  /** A list with results */
  data?: ChartDataResponseResultDataItem[];
  /**
   * Error
   * @nullable
   */
  error?: string | null;
  /**
   * Start timestamp of time range
   * @nullable
   */
  from_dttm?: number | null;
  /** Is the result cached */
  is_cached: boolean;
  /** The executed query statement */
  query: string;
  /** A list with rejected filters */
  rejected_filters?: ChartDataResponseResultRejectedFiltersItem[];
  /** Amount of rows in result set */
  rowcount?: number;
  /**
   * Stacktrace if there was an error
   * @nullable
   */
  stacktrace?: string | null;
  /** Status of the query */
  status?: ChartDataResponseResultStatus;
  /**
   * End timestamp of time range
   * @nullable
   */
  to_dttm?: number | null;
}
