/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartDataRollingOptionsSchemaRollingType } from './chartDataRollingOptionsSchemaRollingType';
import type { ChartDataRollingOptionsSchemaRollingTypeOptions } from './chartDataRollingOptionsSchemaRollingTypeOptions';
import type { ChartDataRollingOptionsSchemaWinType } from './chartDataRollingOptionsSchemaWinType';

export interface ChartDataRollingOptionsSchema {
  /** Should the label be at the center of the window.Default: `false` */
  center?: boolean;
  /** The minimum amount of periods required for a row to be included in the result set. */
  min_periods?: number;
  /** Type of rolling window. Any numpy function will work. */
  rolling_type: ChartDataRollingOptionsSchemaRollingType;
  /** Optional options to pass to rolling method. Needed for e.g. quantile operation. */
  rolling_type_options?: ChartDataRollingOptionsSchemaRollingTypeOptions;
  /** Type of window function. See [SciPy window functions](https://docs.scipy.org/doc/scipy/reference /signal.windows.html#module-scipy.signal.windows) for more details. Some window functions require passing additional parameters to `rolling_type_options`. For instance, to use `gaussian`, the parameter `std` needs to be provided. */
  win_type?: ChartDataRollingOptionsSchemaWinType;
  /** Size of the rolling window in days. */
  window: number;
}
