/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * columns by by which to sort. The key specifies the column name, value specifies if sorting in ascending order.
 */
export type ChartDataSortOptionsSchemaColumns = { [key: string]: unknown };
