/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface ChartCacheWarmUpResponseSingle {
  /** The ID of the chart the status belongs to */
  chart_id?: number;
  /** Error that occurred when warming cache for chart */
  viz_error?: string;
  /** Status of the underlying query for the viz */
  viz_status?: string;
}
