/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface ChartCacheWarmUpRequestSchema {
  /** The ID of the chart to warm up cache for */
  chart_id: number;
  /** The ID of the dashboard to get filters for when warming cache */
  dashboard_id?: number;
  /** Extra filters to apply when warming up cache */
  extra_filters?: string;
}
