/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartDataRestApiGetListUser } from './chartDataRestApiGetListUser';
import type { ChartDataRestApiGetListUser1 } from './chartDataRestApiGetListUser1';
import type { ChartDataRestApiGetListDashboard } from './chartDataRestApiGetListDashboard';
import type { ChartDataRestApiGetListUser2 } from './chartDataRestApiGetListUser2';
import type { ChartDataRestApiGetListUser3 } from './chartDataRestApiGetListUser3';
import type { ChartDataRestApiGetListSqlaTable } from './chartDataRestApiGetListSqlaTable';
import type { ChartDataRestApiGetListTag } from './chartDataRestApiGetListTag';

export interface ChartDataRestApiGetList {
  /** @nullable */
  cache_timeout?: number | null;
  /** @nullable */
  certification_details?: string | null;
  /** @nullable */
  certified_by?: string | null;
  changed_by?: ChartDataRestApiGetListUser;
  readonly changed_by_name?: unknown;
  readonly changed_on_delta_humanized?: unknown;
  readonly changed_on_dttm?: unknown;
  readonly changed_on_utc?: unknown;
  created_by?: ChartDataRestApiGetListUser1;
  readonly created_by_name?: unknown;
  readonly created_on_delta_humanized?: unknown;
  dashboards?: ChartDataRestApiGetListDashboard;
  /** @nullable */
  datasource_id?: number | null;
  readonly datasource_name_text?: unknown;
  /**
   * @maxLength 200
   * @nullable
   */
  datasource_type?: string | null;
  readonly datasource_url?: unknown;
  /** @nullable */
  description?: string | null;
  readonly description_markeddown?: unknown;
  readonly edit_url?: unknown;
  readonly form_data?: unknown;
  id?: number;
  is_managed_externally?: boolean;
  /** @nullable */
  last_saved_at?: string | null;
  last_saved_by?: ChartDataRestApiGetListUser2;
  owners?: ChartDataRestApiGetListUser3;
  /** @nullable */
  params?: string | null;
  /**
   * @maxLength 250
   * @nullable
   */
  slice_name?: string | null;
  readonly slice_url?: unknown;
  table?: ChartDataRestApiGetListSqlaTable;
  tags?: ChartDataRestApiGetListTag;
  readonly thumbnail_url?: unknown;
  readonly url?: unknown;
  /** @nullable */
  uuid?: string | null;
  /**
   * @maxLength 250
   * @nullable
   */
  viz_type?: string | null;
}
