/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartGetDatasourceObjectDataResponse } from './chartGetDatasourceObjectDataResponse';

export interface ChartGetDatasourceObjectResponse {
  /** The name of the datasource */
  label?: string;
  value?: ChartGetDatasourceObjectDataResponse;
}
