/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Metric used to limit timeseries queries by. Requires `series` and `series_limit` to be set.
 * @nullable
 */
export type ChartDataQueryObjectSeriesLimitMetric = unknown | null;
