/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * The type of dataset/datasource identified on `datasource_id`.
 * @nullable
 */
export type ChartDataRestApiPutDatasourceType =
  | (typeof ChartDataRestApiPutDatasourceType)[keyof typeof ChartDataRestApiPutDatasourceType]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChartDataRestApiPutDatasourceType = {
  table: 'table',
  dataset: 'dataset',
  query: 'query',
  saved_query: 'saved_query',
  view: 'view',
} as const;
