/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * End time for relative time deltas. Default: `config["DEFAULT_RELATIVE_START_TIME"]`
 */
export type ChartDataExtrasRelativeEnd =
  (typeof ChartDataExtrasRelativeEnd)[keyof typeof ChartDataExtrasRelativeEnd];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChartDataExtrasRelativeEnd = {
  today: 'today',
  now: 'now',
} as const;
