/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Optional query parameters passed to a dashboard or Explore  view
 * @nullable
 */
export type ChartDataQueryObjectUrlParams = { [key: string]: string } | null;
