/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * The comparison operator.
 */
export type ChartDataFilterOp =
  (typeof ChartDataFilterOp)[keyof typeof ChartDataFilterOp];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChartDataFilterOp = {
  '==': '==',
  '!=': '!=',
  '>': '>',
  '<': '<',
  '>=': '>=',
  '<=': '<=',
  LIKE: 'LIKE',
  NOT_LIKE: 'NOT LIKE',
  ILIKE: 'ILIKE',
  IS_NULL: 'IS NULL',
  IS_NOT_NULL: 'IS NOT NULL',
  IN: 'IN',
  NOT_IN: 'NOT IN',
  IS_TRUE: 'IS TRUE',
  IS_FALSE: 'IS FALSE',
  TEMPORAL_RANGE: 'TEMPORAL_RANGE',
} as const;
