/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface ChartFavStarResponseResult {
  /** The Chart id */
  id?: number;
  /** The FaveStar value */
  value?: boolean;
}
