/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset Charts API
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';
import type { Tag } from './tag';

export interface ChartListItem {
  id?: number;
  slice_name?: string;
  description?: string;
  viz_type?: string;
  url?: string;
  changed_on?: string;
  changed_by_name?: string;
  created_by_name?: string;
  datasource_name_text?: string;
  last_saved_at?: string;
  last_saved_by_name?: string;
  owners?: User[];
  tags?: Tag[];
}
