/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export type ChartDataQueryContextSchemaResultFormat =
  (typeof ChartDataQueryContextSchemaResultFormat)[keyof typeof ChartDataQueryContextSchemaResultFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChartDataQueryContextSchemaResultFormat = {
  csv: 'csv',
  json: 'json',
  xlsx: 'xlsx',
} as const;
