/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartRestApiGetListTagType } from './chartRestApiGetListTagType';

export interface ChartRestApiGetListTag {
  id?: number;
  /**
   * @maxLength 250
   * @nullable
   */
  name?: string | null;
  type?: ChartRestApiGetListTagType;
}
