/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartDataAdhocMetricSchemaAggregate } from './chartDataAdhocMetricSchemaAggregate';
import type { ChartDataColumn } from './chartDataColumn';
import type { ChartDataAdhocMetricSchemaExpressionType } from './chartDataAdhocMetricSchemaExpressionType';

export interface ChartDataAdhocMetricSchema {
  /** Aggregation operator.Only required for simple expression types. */
  aggregate?: ChartDataAdhocMetricSchemaAggregate;
  column?: ChartDataColumn;
  /** Simple or SQL metric */
  expressionType: ChartDataAdhocMetricSchemaExpressionType;
  /** When false, the label will be automatically generated based on the aggregate expression. When true, a custom label has to be specified. */
  hasCustomLabel?: boolean;
  /** Indicates if the filter has been added by a filter component as opposed to being a part of the original query. */
  isExtra?: boolean;
  /** Label for the metric. Is automatically generated unlesshasCustomLabel is true, in which case label must be defined. */
  label?: string;
  /** Unique identifier. Can be any string value, as long as all metrics have a unique identifier. If undefined, a random namewill be generated. */
  optionName?: string;
  /** The metric as defined by a SQL aggregate expression. Only required for SQL expression type. */
  sqlExpression?: string;
  /** Optional time grain for temporal filters */
  timeGrain?: string;
}
