/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Should cell values be calculated across the row or column.
 */
export type ChartDataContributionOptionsSchemaOrientation =
  (typeof ChartDataContributionOptionsSchemaOrientation)[keyof typeof ChartDataContributionOptionsSchemaOrientation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChartDataContributionOptionsSchemaOrientation = {
  row: 'row',
  column: 'column',
} as const;
