/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * To what level of granularity should the temporal column be aggregated. Supports [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations) durations.
 * @nullable
 */
export type ChartDataExtrasTimeGrainSqla =
  | (typeof ChartDataExtrasTimeGrainSqla)[keyof typeof ChartDataExtrasTimeGrainSqla]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChartDataExtrasTimeGrainSqla = {
  PT1S: 'PT1S',
  PT5S: 'PT5S',
  PT30S: 'PT30S',
  PT1M: 'PT1M',
  PT5M: 'PT5M',
  PT10M: 'PT10M',
  PT15M: 'PT15M',
  PT30M: 'PT30M',
  PT1H: 'PT1H',
  PT6H: 'PT6H',
  P1D: 'P1D',
  P1W: 'P1W',
  P1M: 'P1M',
  P3M: 'P3M',
  P1Y: 'P1Y',
  '1969-12-28T00:00:00Z/P1W': '1969-12-28T00:00:00Z/P1W',
  '1969-12-29T00:00:00Z/P1W': '1969-12-29T00:00:00Z/P1W',
  'P1W/1970-01-03T00:00:00Z': 'P1W/1970-01-03T00:00:00Z',
  'P1W/1970-01-04T00:00:00Z': 'P1W/1970-01-04T00:00:00Z',
} as const;
