/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset Charts API
 * OpenAPI spec version: 1.0.0
 */
import type { ChartListItem } from './chartListItem';

export interface ChartsListResponse {
  count?: number;
  result?: ChartListItem[];
}
