/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartGetDatasourceObjectResponse } from './chartGetDatasourceObjectResponse';

export interface ChartGetDatasourceResponseSchema {
  /** The total number of datasources */
  count?: number;
  result?: ChartGetDatasourceObjectResponse;
}
