/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartDataContributionOptionsSchemaOrientation } from './chartDataContributionOptionsSchemaOrientation';

export interface ChartDataContributionOptionsSchema {
  /** Should cell values be calculated across the row or column. */
  orientation: ChartDataContributionOptionsSchemaOrientation;
}
