/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface CssTemplateRestApiPost {
  /** @nullable */
  css?: string | null;
  /**
   * @maxLength 250
   * @nullable
   */
  template_name?: string | null;
}
