/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { CssTemplateRestApiGetUser } from './cssTemplateRestApiGetUser';
import type { CssTemplateRestApiGetUser1 } from './cssTemplateRestApiGetUser1';

export interface CssTemplateRestApiGet {
  changed_by?: CssTemplateRestApiGetUser;
  readonly changed_on_delta_humanized?: unknown;
  created_by?: CssTemplateRestApiGetUser1;
  /** @nullable */
  css?: string | null;
  id?: number;
  /**
   * @maxLength 250
   * @nullable
   */
  template_name?: string | null;
}
