/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { CssTemplateRestApiGetListUser } from './cssTemplateRestApiGetListUser';
import type { CssTemplateRestApiGetListUser1 } from './cssTemplateRestApiGetListUser1';

export interface CssTemplateRestApiGetList {
  changed_by?: CssTemplateRestApiGetListUser;
  readonly changed_on_delta_humanized?: unknown;
  created_by?: CssTemplateRestApiGetListUser1;
  /** @nullable */
  created_on?: string | null;
  /** @nullable */
  css?: string | null;
  id?: number;
  /**
   * @maxLength 250
   * @nullable
   */
  template_name?: string | null;
}
