/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface CurrentUserPutSchema {
  /**
   * The current user's first name
   * @minLength 1
   * @maxLength 64
   */
  first_name?: string;
  /**
   * The current user's last name
   * @minLength 1
   * @maxLength 64
   */
  last_name?: string;
  /** The current user's password for authentication */
  password?: string;
}
