/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { DashboardScreenshotPostSchemaDataMask } from './dashboardScreenshotPostSchemaDataMask';

export interface DashboardScreenshotPostSchema {
  /** A list representing active tabs. */
  activeTabs?: string[];
  /** A string representing the anchor. */
  anchor?: string;
  /** An object representing the data mask. */
  dataMask?: DashboardScreenshotPostSchemaDataMask;
  /** A list of tuples, each containing two strings. */
  urlParams?: unknown[];
}
