/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface DashboardRestApiGetListUser2 {
  /** @maxLength 64 */
  first_name: string;
  id?: number;
  /** @maxLength 64 */
  last_name: string;
}
