/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { DashboardDatasetSchemaColumnFormats } from './dashboardDatasetSchemaColumnFormats';
import type { DashboardDatasetSchemaColumnsItem } from './dashboardDatasetSchemaColumnsItem';
import type { Database } from './database';
import type { DashboardDatasetSchemaMetricsItem } from './dashboardDatasetSchemaMetricsItem';
import type { DashboardDatasetSchemaOwnersItem } from './dashboardDatasetSchemaOwnersItem';
import type { DashboardDatasetSchemaVerboseMap } from './dashboardDatasetSchemaVerboseMap';

export interface DashboardDatasetSchema {
  always_filter_main_dttm?: boolean;
  cache_timeout?: number;
  column_formats?: DashboardDatasetSchemaColumnFormats;
  column_names?: string[];
  column_types?: number[];
  columns?: DashboardDatasetSchemaColumnsItem[];
  database?: Database;
  datasource_name?: string;
  default_endpoint?: string;
  edit_url?: string;
  fetch_values_predicate?: string;
  filter_select?: boolean;
  filter_select_enabled?: boolean;
  granularity_sqla?: string[][];
  health_check_message?: string;
  id?: number;
  is_sqllab_view?: boolean;
  main_dttm_col?: string;
  metrics?: DashboardDatasetSchemaMetricsItem[];
  name?: string;
  normalize_columns?: boolean;
  offset?: number;
  order_by_choices?: string[][];
  owners?: DashboardDatasetSchemaOwnersItem[];
  params?: string;
  perm?: string;
  schema?: string;
  select_star?: string;
  sql?: string;
  table_name?: string;
  template_params?: string;
  time_grain_sqla?: string[][];
  type?: string;
  uid?: string;
  verbose_map?: DashboardDatasetSchemaVerboseMap;
}
