/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Configuration_method is used on the frontend to inform the backend whether to explode parameters or to provide only a sqlalchemy_uri.
 */
export type DatabaseTestConnectionSchemaConfigurationMethod =
  (typeof DatabaseTestConnectionSchemaConfigurationMethod)[keyof typeof DatabaseTestConnectionSchemaConfigurationMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatabaseTestConnectionSchemaConfigurationMethod = {
  sqlalchemy_form: 'sqlalchemy_form',
  dynamic_form: 'dynamic_form',
} as const;
