/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { DatasetRestApiGetSqlMetricCurrency } from './datasetRestApiGetSqlMetricCurrency';

export interface DatasetRestApiGetSqlMetric {
  /** @nullable */
  changed_on?: string | null;
  /** @nullable */
  created_on?: string | null;
  /** @nullable */
  currency?: DatasetRestApiGetSqlMetricCurrency;
  /**
   * @maxLength 128
   * @nullable
   */
  d3format?: string | null;
  /** @nullable */
  description?: string | null;
  expression: string;
  /** @nullable */
  extra?: string | null;
  id?: number;
  /** @maxLength 255 */
  metric_name: string;
  /**
   * @maxLength 32
   * @nullable
   */
  metric_type?: string | null;
  /** @nullable */
  uuid?: string | null;
  /**
   * @maxLength 1024
   * @nullable
   */
  verbose_name?: string | null;
  /** @nullable */
  warning_text?: string | null;
}
