/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface DatasetRestApiPost {
  always_filter_main_dttm?: boolean;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  catalog?: string | null;
  database: number;
  /** @nullable */
  external_url?: string | null;
  /** @nullable */
  is_managed_externally?: boolean | null;
  normalize_columns?: boolean;
  owners?: number[];
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  schema?: string | null;
  /** @nullable */
  sql?: string | null;
  /**
   * @minLength 1
   * @maxLength 250
   */
  table_name: string;
  /** @nullable */
  template_params?: string | null;
  /** @nullable */
  uuid?: string | null;
}
