/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { DatasetRestApiGetUser2 } from './datasetRestApiGetUser2';
import type { DatasetRestApiGetTableColumn } from './datasetRestApiGetTableColumn';
import type { DatasetRestApiGetUser1 } from './datasetRestApiGetUser1';
import type { DatasetRestApiGetDatabase } from './datasetRestApiGetDatabase';
import type { DatasetRestApiGetFolders } from './datasetRestApiGetFolders';
import type { DatasetRestApiGetSqlMetric } from './datasetRestApiGetSqlMetric';
import type { DatasetRestApiGetUser } from './datasetRestApiGetUser';

export interface DatasetRestApiGet {
  /** @nullable */
  always_filter_main_dttm?: boolean | null;
  /** @nullable */
  cache_timeout?: number | null;
  /**
   * @maxLength 256
   * @nullable
   */
  catalog?: string | null;
  changed_by?: DatasetRestApiGetUser2;
  /** @nullable */
  changed_on?: string | null;
  readonly changed_on_humanized?: unknown;
  readonly column_formats?: unknown;
  columns: DatasetRestApiGetTableColumn;
  created_by?: DatasetRestApiGetUser1;
  /** @nullable */
  created_on?: string | null;
  readonly created_on_humanized?: unknown;
  database: DatasetRestApiGetDatabase;
  readonly datasource_name?: unknown;
  readonly datasource_type?: unknown;
  /** @nullable */
  default_endpoint?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  extra?: string | null;
  /** @nullable */
  fetch_values_predicate?: string | null;
  /** @nullable */
  filter_select_enabled?: boolean | null;
  /** @nullable */
  folders?: DatasetRestApiGetFolders;
  readonly granularity_sqla?: unknown;
  id?: number;
  is_managed_externally?: boolean;
  /** @nullable */
  is_sqllab_view?: boolean | null;
  readonly kind?: unknown;
  /**
   * @maxLength 250
   * @nullable
   */
  main_dttm_col?: string | null;
  metrics: DatasetRestApiGetSqlMetric;
  readonly name?: unknown;
  /** @nullable */
  normalize_columns?: boolean | null;
  /** @nullable */
  offset?: number | null;
  readonly order_by_choices?: unknown;
  owners?: DatasetRestApiGetUser;
  /**
   * @maxLength 255
   * @nullable
   */
  schema?: string | null;
  readonly select_star?: unknown;
  /** @nullable */
  sql?: string | null;
  /** @maxLength 250 */
  table_name: string;
  /** @nullable */
  template_params?: string | null;
  readonly time_grain_sqla?: unknown;
  readonly uid?: unknown;
  readonly url?: unknown;
  /** @nullable */
  uuid?: string | null;
  readonly verbose_map?: unknown;
}
