/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * DB-specific parameters for configuration
 */
export type DatabaseRestApiPutParameters = { [key: string]: unknown };
