/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface DatasetRestApiGetDatabase {
  readonly allow_multi_catalog?: unknown;
  readonly backend?: unknown;
  /** @maxLength 250 */
  database_name: string;
  id?: number;
  /** @nullable */
  uuid?: string | null;
}
