/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { DatasetRelatedDashboard } from './datasetRelatedDashboard';

export interface DatasetRelatedDashboards {
  /** Dashboard count */
  count?: number;
  /** A list of dashboards */
  result?: DatasetRelatedDashboard[];
}
