/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { DatabaseRelatedDashboard } from './databaseRelatedDashboard';

export interface DatabaseRelatedDashboards {
  /** Dashboard count */
  count?: number;
  /** A list of dashboards */
  result?: DatabaseRelatedDashboard[];
}
