/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface Database {
  allow_multi_catalog?: boolean;
  allows_cost_estimate?: boolean;
  allows_subquery?: boolean;
  allows_virtual_table_explore?: boolean;
  backend?: string;
  disable_data_preview?: boolean;
  disable_drill_to_detail?: boolean;
  explore_database_id?: number;
  id?: number;
  name?: string;
}
