/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * JSON string containing extra configuration elements.
 */
export type DatasetExtra = { [key: string]: unknown };
