/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface DatabaseRestApiGet {
  /** @nullable */
  allow_ctas?: boolean | null;
  /** @nullable */
  allow_cvas?: boolean | null;
  /** @nullable */
  allow_dml?: boolean | null;
  /** @nullable */
  allow_file_upload?: boolean | null;
  /** @nullable */
  allow_run_async?: boolean | null;
  readonly backend?: unknown;
  /** @nullable */
  cache_timeout?: number | null;
  /**
   * @maxLength 255
   * @nullable
   */
  configuration_method?: string | null;
  /** @maxLength 250 */
  database_name: string;
  readonly driver?: unknown;
  readonly engine_information?: unknown;
  /** @nullable */
  expose_in_sqllab?: boolean | null;
  /**
   * @maxLength 250
   * @nullable
   */
  force_ctas_schema?: string | null;
  id?: number;
  /** @nullable */
  impersonate_user?: boolean | null;
  is_managed_externally?: boolean;
  /** @nullable */
  uuid?: string | null;
}
