/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface DatabaseTablesQuerySchema {
  catalog_name?: string;
  force?: boolean;
  schema_name: string;
}
