/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface DatabaseSSHTunnel {
  /**
   * SSH Tunnel ID (for updates)
   * @nullable
   */
  id?: number | null;
  password?: string;
  private_key?: string;
  private_key_password?: string;
  server_address?: string;
  server_port?: number;
  username?: string;
}
