/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface DatasetCacheWarmUpRequestSchema {
  /** The ID of the dashboard to get filters for when warming cache */
  dashboard_id?: number;
  /** The name of the database where the table is located */
  db_name: string;
  /** Extra filters to apply when warming up cache */
  extra_filters?: string;
  /** The name of the table to warm up cache for */
  table_name: string;
}
