/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { DatasetMetricsPutCurrency } from './datasetMetricsPutCurrency';

export interface DatasetMetricsPut {
  /** @nullable */
  currency?: DatasetMetricsPutCurrency;
  /**
   * @minLength 1
   * @maxLength 128
   * @nullable
   */
  d3format?: string | null;
  /** @nullable */
  description?: string | null;
  expression: string;
  /** @nullable */
  extra?: string | null;
  id?: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  metric_name: string;
  /**
   * @minLength 1
   * @maxLength 32
   * @nullable
   */
  metric_type?: string | null;
  /** @nullable */
  uuid?: string | null;
  /** @nullable */
  verbose_name?: string | null;
  /** @nullable */
  warning_text?: string | null;
}
