/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface DatasetColumnsPut {
  /**
   * @minLength 1
   * @maxLength 255
   * @nullable
   */
  advanced_data_type?: string | null;
  /**
   * @minLength 1
   * @maxLength 255
   */
  column_name: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  expression?: string | null;
  /** @nullable */
  extra?: string | null;
  filterable?: boolean;
  groupby?: boolean;
  id?: number;
  /** @nullable */
  is_active?: boolean | null;
  /** @nullable */
  is_dttm?: boolean | null;
  /**
   * @minLength 1
   * @maxLength 255
   * @nullable
   */
  python_date_format?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  uuid?: string | null;
  /** @nullable */
  verbose_name?: string | null;
}
