/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface DatasetMetricCurrencyPut {
  /**
   * @minLength 1
   * @maxLength 128
   */
  symbol?: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  symbolPosition?: string;
}
