/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { DeleteApiV1ChartPkFavorites200Result } from './deleteApiV1ChartPkFavorites200Result';

export type DeleteApiV1ChartPkFavorites200 = {
  result?: DeleteApiV1ChartPkFavorites200Result;
};
