/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { User2 } from './user2';

export interface EmbeddedDashboardResponseSchema {
  allowed_domains?: string[];
  changed_by?: User2;
  changed_on?: string;
  dashboard_id?: string;
  uuid?: string;
}
