/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * URL Parameter key-value pair
 * @nullable
 */
export type ExplorePermalinkStateSchemaUrlParamsItem = unknown | null;
