/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartFavStarResponseResult } from './chartFavStarResponseResult';

export interface FavoriteIdsSchema {
  /** A list of results for each corresponding chart in the request */
  result?: ChartFavStarResponseResult[];
}
