/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export type FolderType = (typeof FolderType)[keyof typeof FolderType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FolderType = {
  metric: 'metric',
  column: 'column',
  folder: 'folder',
} as const;
