/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { FormDataPostSchemaDatasourceType } from './formDataPostSchemaDatasourceType';

export interface FormDataPostSchema {
  /** The chart ID */
  chart_id?: number;
  /** The datasource ID */
  datasource_id: number;
  /** The datasource type */
  datasource_type: FormDataPostSchemaDatasourceType;
  /** Any type of JSON supported text. */
  form_data: string;
}
