/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export type GetApiV1ChartInfo200FiltersColumnNameItem = {
  /** The filter name. Will be translated by babel */
  name?: string;
  /** The filter operation key to use on list filters */
  operator?: string;
};
