/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { GetListSchema } from './getListSchema';

export type GetApiV1ChartParams = {
  q?: GetListSchema;
};
