/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { GetApiV1ChartInfo200FiltersColumnNameItem } from './getApiV1ChartInfo200FiltersColumnNameItem';

export type GetApiV1ChartInfo200Filters = {
  column_name?: GetApiV1ChartInfo200FiltersColumnNameItem[];
};
