/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ChartGetResponseSchema } from './chartGetResponseSchema';

export type GetApiV1ChartIdOrUuid200 = {
  result?: ChartGetResponseSchema;
};
