/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export type GetApiV1Chart200DescriptionColumns = {
  /** The description for the column name. Will be translated by babel */
  column_name?: string;
};
