/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export type GetListSchemaOrderDirection =
  (typeof GetListSchemaOrderDirection)[keyof typeof GetListSchemaOrderDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetListSchemaOrderDirection = {
  asc: 'asc',
  desc: 'desc',
} as const;
