/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { GetListSchemaFiltersItem } from './getListSchemaFiltersItem';
import type { GetListSchemaKeysItem } from './getListSchemaKeysItem';
import type { GetListSchemaOrderDirection } from './getListSchemaOrderDirection';

export interface GetListSchema {
  columns?: string[];
  filters?: GetListSchemaFiltersItem[];
  keys?: GetListSchemaKeysItem[];
  order_column?: string;
  order_direction?: GetListSchemaOrderDirection;
  page?: number;
  page_size?: number;
  select_columns?: string[];
}
