/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface GetRelatedSchema {
  filter?: string;
  include_ids?: number[];
  page?: number;
  page_size?: number;
}
