/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { GroupApiGetListRole } from './groupApiGetListRole';
import type { GroupApiGetListUser } from './groupApiGetListUser';

export interface GroupApiGetList {
  /**
   * @maxLength 512
   * @nullable
   */
  description?: string | null;
  id?: number;
  /**
   * @maxLength 150
   * @nullable
   */
  label?: string | null;
  /** @maxLength 100 */
  name: string;
  roles?: GroupApiGetListRole;
  users?: GroupApiGetListUser;
}
