/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface GroupPostSchema {
  /**
   * Group description
   * @minLength 0
   * @maxLength 512
   * @nullable
   */
  description?: string | null;
  /**
   * Group label
   * @minLength 0
   * @maxLength 150
   * @nullable
   */
  label?: string | null;
  /**
   * Group name
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** Group roles */
  roles?: number[];
  /** Group users */
  users?: number[];
}
