/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { Resource } from './resource';
import type { RlsRule } from './rlsRule';
import type { User3 } from './user3';

export interface GuestTokenCreate {
  resources: Resource[];
  rls: RlsRule[];
  user?: User3;
}
