/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { LogRestApiGetUser } from './logRestApiGetUser';

export interface LogRestApiGet {
  /**
   * @maxLength 512
   * @nullable
   */
  action?: string | null;
  /** @nullable */
  dashboard_id?: number | null;
  /** @nullable */
  dttm?: string | null;
  /** @nullable */
  duration_ms?: number | null;
  /** @nullable */
  json?: string | null;
  /**
   * @maxLength 1024
   * @nullable
   */
  referrer?: string | null;
  /** @nullable */
  slice_id?: number | null;
  user?: LogRestApiGetUser;
  user_id?: unknown;
}
