/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { LogRestApiPutUser } from './logRestApiPutUser';

export interface LogRestApiPut {
  /**
   * @maxLength 512
   * @nullable
   */
  action?: string | null;
  /** @nullable */
  dttm?: string | null;
  /** @nullable */
  json?: string | null;
  /** @nullable */
  user?: LogRestApiPutUser;
}
