/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface LogRestApiGetUser {
  /** @nullable */
  active?: boolean | null;
  /** @nullable */
  changed_on?: string | null;
  /** @nullable */
  created_on?: string | null;
  /** @maxLength 320 */
  email: string;
  /** @nullable */
  fail_login_count?: number | null;
  /** @maxLength 64 */
  first_name: string;
  id?: number;
  /** @nullable */
  last_login?: string | null;
  /** @maxLength 64 */
  last_name: string;
  /** @nullable */
  login_count?: number | null;
  /**
   * @maxLength 256
   * @nullable
   */
  password?: string | null;
  /** @maxLength 64 */
  username: string;
}
