/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { N410ResponseResponseErrorsItemErrorType } from './n410ResponseResponseErrorsItemErrorType';
import type { N410ResponseResponseErrorsItemExtra } from './n410ResponseResponseErrorsItemExtra';
import type { N410ResponseResponseErrorsItemLevel } from './n410ResponseResponseErrorsItemLevel';

export type N410ResponseResponseErrorsItem = {
  error_type?: N410ResponseResponseErrorsItemErrorType;
  extra?: N410ResponseResponseErrorsItemExtra;
  level?: N410ResponseResponseErrorsItemLevel;
  message?: string;
};
