/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { N410ResponseResponseErrorsItem } from './n410ResponseResponseErrorsItem';

export type N410ResponseResponse = {
  errors?: N410ResponseResponseErrorsItem[];
  message?: string;
};
