/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface PermissionViewMenuApiPut {
  permission_id?: unknown;
  view_menu_id?: unknown;
}
