/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { Database1 } from './database1';
import type { User1 } from './user1';

export interface QueryRestApiGetList {
  changed_on?: string;
  database?: Database1;
  end_time?: number;
  executed_sql?: string;
  id?: number;
  rows?: number;
  schema?: string;
  sql?: string;
  readonly sql_tables?: unknown;
  start_time?: number;
  status?: string;
  tab_name?: string;
  tmp_table_name?: string;
  tracking_url?: string;
  user?: User1;
}
