/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { QueryResultExtra } from './queryResultExtra';

export interface QueryResult {
  changed_on?: string;
  ctas?: boolean;
  db?: string;
  dbId?: number;
  endDttm?: number;
  /** @nullable */
  errorMessage?: string | null;
  executedSql?: string;
  extra?: QueryResultExtra;
  id?: string;
  limit?: number;
  limitingFactor?: string;
  progress?: number;
  queryId?: number;
  resultsKey?: string;
  rows?: number;
  schema?: string;
  serverId?: number;
  sql?: string;
  sqlEditorId?: string;
  startDttm?: number;
  state?: string;
  tab?: string;
  /** @nullable */
  tempSchema?: string | null;
  /** @nullable */
  tempTable?: string | null;
  /** @nullable */
  trackingUrl?: string | null;
  user?: string;
  userId?: number;
}
