/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { RecentActivity } from './recentActivity';

export interface RecentActivityResponseSchema {
  /** A list of recent activity objects */
  result?: RecentActivity[];
}
