/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface RecentActivity {
  /** Action taken describing type of activity */
  action?: string;
  /** Title of item */
  item_title?: string;
  /** Type of item, e.g. slice or dashboard */
  item_type?: string;
  /** URL to item */
  item_url?: string;
  /** Time of activity, in epoch milliseconds */
  time?: number;
  /** Human-readable description of how long ago activity took place. */
  time_delta_humanized?: string;
}
