/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * The recipient type, check spec for valid options
 */
export type ReportRecipientType =
  (typeof ReportRecipientType)[keyof typeof ReportRecipientType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportRecipientType = {
  Email: 'Email',
  Slack: 'Slack',
  SlackV2: 'SlackV2',
} as const;
