/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * The report schedule type
 */
export type ReportScheduleRestApiPutType =
  (typeof ReportScheduleRestApiPutType)[keyof typeof ReportScheduleRestApiPutType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportScheduleRestApiPutType = {
  Alert: 'Alert',
  Report: 'Report',
} as const;
