/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ReportRecipientConfigJSON } from './reportRecipientConfigJSON';
import type { ReportRecipientType } from './reportRecipientType';

export interface ReportRecipient {
  recipient_config_json?: ReportRecipientConfigJSON;
  /** The recipient type, check spec for valid options */
  type: ReportRecipientType;
}
