/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Determines when to trigger alert based off value from alert query. Alerts will be triggered with these validator types:
- Not Null - When the return value is Not NULL, Empty, or 0
- Operator - When `sql_return_value comparison_operator threshold` is True e.g. `50 <= 75`<br>Supports the comparison operators <, <=, >, >=, ==, and !=
 * @nullable
 */
export type ReportScheduleRestApiPutValidatorType =
  | (typeof ReportScheduleRestApiPutValidatorType)[keyof typeof ReportScheduleRestApiPutValidatorType]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportScheduleRestApiPutValidatorType = {
  not_null: 'not null',
  operator: 'operator',
} as const;
