/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export type ReportScheduleRestApiPutReportFormat =
  (typeof ReportScheduleRestApiPutReportFormat)[keyof typeof ReportScheduleRestApiPutReportFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportScheduleRestApiPutReportFormat = {
  PDF: 'PDF',
  PNG: 'PNG',
  CSV: 'CSV',
  TEXT: 'TEXT',
} as const;
