/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ReportScheduleRestApiGetSlice } from './reportScheduleRestApiGetSlice';
import type { ReportScheduleRestApiGetDashboard } from './reportScheduleRestApiGetDashboard';
import type { ReportScheduleRestApiGetDatabase } from './reportScheduleRestApiGetDatabase';
import type { ReportScheduleRestApiGetUser } from './reportScheduleRestApiGetUser';
import type { ReportScheduleRestApiGetReportRecipients } from './reportScheduleRestApiGetReportRecipients';

export interface ReportScheduleRestApiGet {
  /** @nullable */
  active?: boolean | null;
  chart?: ReportScheduleRestApiGetSlice;
  /** @nullable */
  context_markdown?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  creation_method?: string | null;
  /** @maxLength 1000 */
  crontab: string;
  /** @nullable */
  custom_width?: number | null;
  dashboard?: ReportScheduleRestApiGetDashboard;
  database?: ReportScheduleRestApiGetDatabase;
  /** @nullable */
  description?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  email_subject?: string | null;
  readonly extra?: unknown;
  /** @nullable */
  force_screenshot?: boolean | null;
  /** @nullable */
  grace_period?: number | null;
  id?: number;
  /** @nullable */
  last_eval_dttm?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  last_state?: string | null;
  /** @nullable */
  last_value?: number | null;
  /** @nullable */
  last_value_row_json?: string | null;
  /** @nullable */
  log_retention?: number | null;
  /** @maxLength 150 */
  name: string;
  owners?: ReportScheduleRestApiGetUser;
  recipients: ReportScheduleRestApiGetReportRecipients;
  /**
   * @maxLength 50
   * @nullable
   */
  report_format?: string | null;
  /** @nullable */
  sql?: string | null;
  /** @maxLength 100 */
  timezone?: string;
  /** @maxLength 50 */
  type: string;
  /** @nullable */
  validator_config_json?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  validator_type?: string | null;
  /** @nullable */
  working_timeout?: number | null;
}
