/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface ReportScheduleRestApiGetSlice {
  id?: number;
  /**
   * @maxLength 250
   * @nullable
   */
  slice_name?: string | null;
  /**
   * @maxLength 250
   * @nullable
   */
  viz_type?: string | null;
}
