/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Creation method is used to inform the frontend whether the report/alert was created in the dashboard, chart, or alerts and reports UI.
 */
export type ReportScheduleRestApiPostCreationMethod =
  (typeof ReportScheduleRestApiPostCreationMethod)[keyof typeof ReportScheduleRestApiPostCreationMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportScheduleRestApiPostCreationMethod = {
  charts: 'charts',
  dashboards: 'dashboards',
  alerts_reports: 'alerts_reports',
} as const;
