/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface ReportScheduleRestApiGetDashboard {
  /**
   * @maxLength 500
   * @nullable
   */
  dashboard_title?: string | null;
  id?: number;
}
