/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface ReportRecipientConfigJSON {
  bccTarget?: string;
  ccTarget?: string;
  target?: string;
}
