/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface ReportExecutionLogRestApiGetList {
  /** @nullable */
  end_dttm?: string | null;
  /** @nullable */
  error_message?: string | null;
  id?: number;
  scheduled_dttm: string;
  /** @nullable */
  start_dttm?: string | null;
  /** @maxLength 50 */
  state: string;
  /** @nullable */
  uuid?: string | null;
  /** @nullable */
  value?: number | null;
  /** @nullable */
  value_row_json?: string | null;
}
