/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export type ReportScheduleRestApiPostReportFormat =
  (typeof ReportScheduleRestApiPostReportFormat)[keyof typeof ReportScheduleRestApiPostReportFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportScheduleRestApiPostReportFormat = {
  PDF: 'PDF',
  PNG: 'PNG',
  CSV: 'CSV',
  TEXT: 'TEXT',
} as const;
