/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { User1 } from './user1';
import type { RLSRestApiGetListFilterType } from './rLSRestApiGetListFilterType';
import type { Roles1 } from './roles1';
import type { Tables } from './tables';

export interface RLSRestApiGetList {
  changed_by?: User1;
  readonly changed_on_delta_humanized?: unknown;
  /** clause_description */
  clause?: string;
  /** description_description */
  description?: string;
  /** filter_type_description */
  filter_type?: RLSRestApiGetListFilterType;
  /** group_key_description */
  group_key?: string;
  /** id_description */
  id?: number;
  /** name_description */
  name?: string;
  roles?: Roles1[];
  tables?: Tables[];
}
