/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * filter_type_description
 */
export type RLSRestApiGetListFilterType =
  (typeof RLSRestApiGetListFilterType)[keyof typeof RLSRestApiGetListFilterType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RLSRestApiGetListFilterType = {
  Regular: 'Regular',
  Base: 'Base',
} as const;
