/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { RLSRestApiPutFilterType } from './rLSRestApiPutFilterType';

export interface RLSRestApiPut {
  /** clause_description */
  clause?: string;
  /**
   * description_description
   * @nullable
   */
  description?: string | null;
  /** filter_type_description */
  filter_type?: RLSRestApiPutFilterType;
  /**
   * group_key_description
   * @nullable
   */
  group_key?: string | null;
  /**
   * name_description
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  /** roles_description */
  roles?: number[];
  /** tables_description */
  tables?: number[];
}
