/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface RoleResponseSchema {
  id?: number;
  name?: string;
  permission_ids?: number[];
  user_ids?: number[];
}
