/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface RolePermissionPostSchema {
  /** List of permission view menu id */
  permission_view_menu_ids: number[];
}
