/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface RolePermissionListSchema {
  id?: number;
  permission_name?: string;
  view_menu_name?: string;
}
