/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { SavedQueryRestApiGetListTagType } from './savedQueryRestApiGetListTagType';

export interface SavedQueryRestApiGetListTag {
  id?: number;
  /**
   * @maxLength 250
   * @nullable
   */
  name?: string | null;
  type?: SavedQueryRestApiGetListTagType;
}
