/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface SavedQueryRestApiPut {
  /**
   * @maxLength 256
   * @nullable
   */
  catalog?: string | null;
  db_id?: unknown;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  extra_json?: string | null;
  /**
   * @maxLength 256
   * @nullable
   */
  label?: string | null;
  /**
   * @maxLength 128
   * @nullable
   */
  schema?: string | null;
  /** @nullable */
  sql?: string | null;
  /** @nullable */
  template_parameters?: string | null;
}
