/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { SavedQueryRestApiGetUser } from './savedQueryRestApiGetUser';
import type { SavedQueryRestApiGetUser1 } from './savedQueryRestApiGetUser1';
import type { SavedQueryRestApiGetDatabase } from './savedQueryRestApiGetDatabase';

export interface SavedQueryRestApiGet {
  /**
   * @maxLength 256
   * @nullable
   */
  catalog?: string | null;
  changed_by?: SavedQueryRestApiGetUser;
  /** @nullable */
  changed_on?: string | null;
  readonly changed_on_delta_humanized?: unknown;
  created_by?: SavedQueryRestApiGetUser1;
  database?: SavedQueryRestApiGetDatabase;
  /** @nullable */
  description?: string | null;
  id?: number;
  /**
   * @maxLength 256
   * @nullable
   */
  label?: string | null;
  /**
   * @maxLength 128
   * @nullable
   */
  schema?: string | null;
  /** @nullable */
  sql?: string | null;
  readonly sql_tables?: unknown;
  /** @nullable */
  template_parameters?: string | null;
}
