/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export type SavedQueryRestApiGetListTagType =
  (typeof SavedQueryRestApiGetListTagType)[keyof typeof SavedQueryRestApiGetListTagType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SavedQueryRestApiGetListTagType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
