/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * Form data associated with the slice.
 */
export type SliceFormData = { [key: string]: unknown };
