/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface SqlLabPermalinkSchema {
  autorun?: boolean;
  /**
   * The catalog name of the query
   * @nullable
   */
  catalog?: string | null;
  /** The id of the database */
  dbId: number;
  /** The label of the editor tab */
  name: string;
  /**
   * The schema name of the query
   * @nullable
   */
  schema?: string | null;
  /** SQL query text */
  sql: string;
  /**
   * stringfied JSON string for template parameters
   * @nullable
   */
  templateParams?: string | null;
}
