/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { TabState } from './tabState';
import type { SQLLabBootstrapSchemaDatabases } from './sQLLabBootstrapSchemaDatabases';
import type { SQLLabBootstrapSchemaQueries } from './sQLLabBootstrapSchemaQueries';

export interface SQLLabBootstrapSchema {
  active_tab?: TabState;
  databases?: SQLLabBootstrapSchemaDatabases;
  queries?: SQLLabBootstrapSchemaQueries;
  tab_state_ids?: string[];
}
