/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface SupersetUserApiGetListGroup {
  /**
   * @maxLength 512
   * @nullable
   */
  description?: string | null;
  id?: number;
  /**
   * @maxLength 150
   * @nullable
   */
  label?: string | null;
  /** @maxLength 100 */
  name: string;
}
