/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { SupersetUserApiGetUser1 } from './supersetUserApiGetUser1';
import type { SupersetUserApiGetUser } from './supersetUserApiGetUser';
import type { SupersetUserApiGetGroup } from './supersetUserApiGetGroup';
import type { SupersetUserApiGetRole } from './supersetUserApiGetRole';

export interface SupersetUserApiGet {
  /** @nullable */
  active?: boolean | null;
  changed_by?: SupersetUserApiGetUser1;
  /** @nullable */
  changed_on?: string | null;
  created_by?: SupersetUserApiGetUser;
  /** @nullable */
  created_on?: string | null;
  /** @maxLength 320 */
  email: string;
  /** @nullable */
  fail_login_count?: number | null;
  /** @maxLength 64 */
  first_name: string;
  groups?: SupersetUserApiGetGroup;
  id?: number;
  /** @nullable */
  last_login?: string | null;
  /** @maxLength 64 */
  last_name: string;
  /** @nullable */
  login_count?: number | null;
  roles?: SupersetUserApiGetRole;
  /** @maxLength 64 */
  username: string;
}
