/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { TableMetadataOptionsResponse } from './tableMetadataOptionsResponse';

export interface TableMetadataForeignKeysIndexesResponse {
  column_names?: string[];
  /** The name of the foreign key or index */
  name?: string;
  options?: TableMetadataOptionsResponse;
  referred_columns?: string[];
  referred_schema?: string;
  referred_table?: string;
  type?: string;
}
