/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { TableExtraMetadataResponseSchemaClustering } from './tableExtraMetadataResponseSchemaClustering';
import type { TableExtraMetadataResponseSchemaMetadata } from './tableExtraMetadataResponseSchemaMetadata';
import type { TableExtraMetadataResponseSchemaPartitions } from './tableExtraMetadataResponseSchemaPartitions';

export interface TableExtraMetadataResponseSchema {
  clustering?: TableExtraMetadataResponseSchemaClustering;
  metadata?: TableExtraMetadataResponseSchemaMetadata;
  partitions?: TableExtraMetadataResponseSchemaPartitions;
}
