/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface Table {
  database_id?: number;
  description?: string;
  expanded?: boolean;
  id?: number;
  schema?: string;
  tab_state_id?: number;
  table?: string;
}
