/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { TabStateExtraJson } from './tabStateExtraJson';
import type { QueryResult } from './queryResult';
import type { TabStateSavedQuery } from './tabStateSavedQuery';
import type { Table } from './table';

export interface TabState {
  active?: boolean;
  autorun?: boolean;
  database_id?: number;
  extra_json?: TabStateExtraJson;
  hide_left_bar?: boolean;
  id?: string;
  label?: string;
  latest_query?: QueryResult;
  query_limit?: number;
  /** @nullable */
  saved_query?: TabStateSavedQuery;
  schema?: string;
  sql?: string;
  table_schemas?: Table[];
  user_id?: number;
}
