/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset Charts API
 * OpenAPI spec version: 1.0.0
 */
import type { TagType } from './tagType';

export interface Tag {
  id?: number;
  name?: string;
  type?: TagType;
}
