/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export type Tag1Type = (typeof Tag1Type)[keyof typeof Tag1Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Tag1Type = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
