/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { Tag1Type } from './tag1Type';

export interface Tag1 {
  id?: number;
  name?: string;
  type?: Tag1Type;
}
