/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface TagObject {
  /** @nullable */
  description?: string | null;
  /** @minLength 1 */
  name?: string;
  /** Objects to tag */
  objects_to_tag?: unknown[];
}
