/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface TagPostBulkResponseObject {
  /** Objects to tag */
  objects_skipped?: unknown[];
  /** Objects to tag */
  objects_tagged?: unknown[];
}
