/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { TagPostBulkResponseObject } from './tagPostBulkResponseObject';

export interface TagPostBulkResponseSchema {
  result?: TagPostBulkResponseObject;
}
