/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface TagRestApiGetListUser1 {
  /** @maxLength 64 */
  first_name: string;
  /** @maxLength 64 */
  last_name: string;
}
