/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset Charts API
 * OpenAPI spec version: 1.0.0
 */

export type TagType = (typeof TagType)[keyof typeof TagType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TagType = {
  custom: 'custom',
  dashboard: 'dashboard',
  chart: 'chart',
  query: 'query',
  owner: 'owner',
} as const;
