/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * File type to upload
 */
export type UploadFileMetadataPostSchemaType =
  (typeof UploadFileMetadataPostSchemaType)[keyof typeof UploadFileMetadataPostSchemaType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadFileMetadataPostSchemaType = {
  csv: 'csv',
  excel: 'excel',
  columnar: 'columnar',
} as const;
