/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

/**
 * What to do if the table already exists accepts: fail, replace, append
 */
export type UploadPostSchemaAlreadyExists =
  (typeof UploadPostSchemaAlreadyExists)[keyof typeof UploadPostSchemaAlreadyExists];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadPostSchemaAlreadyExists = {
  fail: 'fail',
  replace: 'replace',
  append: 'append',
} as const;
