/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface UploadFileMetadataItem {
  /** A list of columns names in the sheet */
  column_names?: string[];
  /** The name of the sheet */
  sheet_name?: string;
}
