/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface UserRegistrationsRestAPIGetList {
  /** @maxLength 64 */
  email: string;
  /** @maxLength 64 */
  first_name: string;
  id?: number;
  /** @maxLength 64 */
  last_name: string;
  /** @nullable */
  registration_date?: string | null;
  /**
   * @maxLength 256
   * @nullable
   */
  registration_hash?: string | null;
  /** @maxLength 64 */
  username: string;
}
