/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */
import type { ValidateSQLRequestTemplateParams } from './validateSQLRequestTemplateParams';

export interface ValidateSQLRequest {
  /** @nullable */
  catalog?: string | null;
  /** @nullable */
  schema?: string | null;
  /** SQL statement to validate */
  sql: string;
  /** @nullable */
  template_params?: ValidateSQLRequestTemplateParams;
}
