/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Superset
 * Superset
 * OpenAPI spec version: v1
 */

export interface ValidateSQLResponse {
  end_column?: number;
  line_number?: number;
  message?: string;
  start_column?: number;
}
