import React from 'react';

const lookup = {
  Andorra: 'ad',
  'United Arab Emirates': 'ae',
  Afghanistan: 'af',
  'Antigua and Barbuda': 'ag',
  Anguilla: 'ai',
  Albania: 'al',
  Armenia: 'am',
  'Netherland Antilles': 'an',
  Angola: 'ao',
  Antarctica: 'aq',
  Argentina: 'ar',
  'American Samoa': 'as',
  Austria: 'at',
  Australia: 'au',
  Aruba: 'aw',
  Azerbaijan: 'az',
  'Bosnia- Herzegovina': 'ba',
  Barbados: 'bb',
  Bangladesh: 'bd',
  Belgium: 'be',
  'Burkina Faso': 'bf',
  Bulgaria: 'bg',
  Bahrain: 'bh',
  Burundi: 'bi',
  Benin: 'bj',
  Bermuda: 'bm',
  'Brunei Darussalam': 'bn',
  Bolivia: 'bo',
  Brazil: 'br',
  Bahamas: 'bs',
  Bhutan: 'bt',
  'Bouvet Island': 'bv',
  Botswana: 'bw',
  Belarus: 'by',
  Belize: 'bz',
  Canada: 'ca',
  'Cocos (Keeling) Islands': 'cc',
  'Central African Republic': 'cf',
  Congo: 'cg',
  Switzerland: 'ch',
  'Ivory Coast': 'ci',
  'Cook Islands': 'ck',
  Chile: 'cl',
  Cameroon: 'cm',
  China: 'cn',
  Colombia: 'co',
  'Costa Rica': 'cr',
  'Czechoslovakia (obsolete)': 'cs',
  Cuba: 'cu',
  'Cape Verde': 'cv',
  'Christmas Island': 'cx',
  Cyprus: 'cy',
  'Czech Republic': 'cz',
  Germany: 'de',
  Djibouti: 'dj',
  Denmark: 'dk',
  Dominica: 'dm',
  'Dominican Republic': 'do',
  Algeria: 'dz',
  Ecuador: 'ec',
  Estonia: 'ee',
  Egypt: 'eg',
  'Western Sahara': 'eh',
  Eritrea: 'er',
  Spain: 'es',
  Ethiopia: 'et',
  Finland: 'fi',
  Fiji: 'fj',
  'Falkland Isl.( Malvinas)': 'fk',
  Micronesia: 'fm',
  'Faroe Islands': 'fo',
  France: 'fr',
  'France (Europe only)': 'fx',
  Gabon: 'ga',
  'Great Britain (UK)': 'gb',
  Grenada: 'gd',
  Georgia: 'ge',
  'Guyana (Fr.)': 'gf',
  Ghana: 'gh',
  Gibraltar: 'gi',
  Greenland: 'gl',
  Gambia: 'gm',
  Guinea: 'gn',
  'Guadeloupe (Fr.)': 'gp',
  'Equatorial Guinea': 'gq',
  Greece: 'gr',
  'South Georgia & South Sandwich Islands': 'gs',
  Guatemala: 'gt',
  'Guam (US)': 'gu',
  'Guinea Bissau': 'gw',
  Guyana: 'gy',
  'Hong Kong': 'hk',
  'Heard & McDonald Islands': 'hm',
  Honduras: 'hn',
  Croatia: 'hr',
  Haiti: 'ht',
  Hungary: 'hu',
  Indonesia: 'id',
  Ireland: 'ie',
  Israel: 'il',
  India: 'in',
  'British Indian Ocean Terr.': 'io',
  Iraq: 'iq',
  Iran: 'ir',
  Iceland: 'is',
  Italy: 'it',
  Jamaica: 'jm',
  Jordan: 'jo',
  Japan: 'jp',
  Kenya: 'ke',
  'Kyrgyz Republic': 'kg',
  Cambodia: 'kh',
  Kiribati: 'ki',
  Comoros: 'km',
  'St. Kitts Nevis Anguilla': 'kn',
  'Korea (North)': 'kp',
  'Korea (South)': 'kr',
  Kuwait: 'kw',
  'Cayman Islands': 'ky',
  Kazachstan: 'kz',
  Laos: 'la',
  Lebanon: 'lb',
  'Saint Lucia': 'lc',
  Liechtenstein: 'li',
  'Sri Lanka': 'lk',
  Liberia: 'lr',
  Lesotho: 'ls',
  Lithuania: 'lt',
  Luxembourg: 'lu',
  Latvia: 'lv',
  Libya: 'ly',
  Morocco: 'ma',
  Monaco: 'mc',
  Moldova: 'md',
  Madagascar: 'mg',
  'Marshall Islands': 'mh',
  'Macedonia (prev. Yug.)': 'mk',
  Mali: 'ml',
  Myanmar: 'mm',
  Mongolia: 'mn',
  Macau: 'mo',
  'Northern Mariana Islands': 'mp',
  'Martinique (Fr.)': 'mq',
  Mauritania: 'mr',
  Montserrat: 'ms',
  Malta: 'mt',
  Mauritius: 'mu',
  Maldives: 'mv',
  Malawi: 'mw',
  Mexico: 'mx',
  Malaysia: 'my',
  Mozambique: 'mz',
  Namibia: 'na',
  'New Caledonia Fr.': 'nc',
  Niger: 'ne',
  'Norfolk Island': 'nf',
  Nigeria: 'ng',
  Nicaragua: 'ni',
  Netherlands: 'nl',
  Norway: 'no',
  Nepal: 'np',
  Nauru: 'nr',
  Niue: 'nu',
  'New Zealand': 'nz',
  Oman: 'om',
  Panama: 'pa',
  Peru: 'pe',
  'Polynesia (Fr.)': 'pf',
  'Papua New Guinea': 'pg',
  Philippines: 'ph',
  Pakistan: 'pk',
  Poland: 'pl',
  'St. Pierre & Miquelon': 'pm',
  Pitcairn: 'pn',
  'Puerto Rico (US)': 'pr',
  Portugal: 'pt',
  Palau: 'pw',
  Paraguay: 'py',
  Qatar: 'qa',
  'Reunion (Fr.)': 're',
  Romania: 'ro',
  'Russian Federation': 'ru',
  Rwanda: 'rw',
  'Saudi Arabia': 'sa',
  'Solomon Islands': 'sb',
  Seychelles: 'sc',
  Sudan: 'sd',
  Sweden: 'se',
  Singapore: 'sg',
  'St. Helena': 'sh',
  Slovenia: 'si',
  'Svalbard& Jan Mayen Islands': 'sj',
  'Slovakia (Slovak Republic)': 'sk',
  'Sierra Leone': 'sl',
  'San Marino': 'sm',
  Senegal: 'sn',
  Somalia: 'so',
  Suriname: 'sr',
  'St. Tome and Principe': 'st',
  'Soviet Union (obsolete)': 'su',
  'El Salvador': 'sv',
  Syria: 'sy',
  Swaziland: 'sz',
  'Turks& Caicos Islands': 'tc',
  Chad: 'td',
  'French Southern Territory': 'tf',
  Togo: 'tg',
  Thailand: 'th',
  Tadjikistan: 'tj',
  Tokelau: 'tk',
  Turkmenistan: 'tm',
  Tunisia: 'tn',
  Tonga: 'to',
  'East Timor': 'tp',
  Turkey: 'tr',
  'Trinidad Tobago': 'tt',
  Tuvalu: 'tv',
  Taiwan: 'tw',
  Tanzania: 'tz',
  Ukraine: 'ua',
  Uganda: 'ug',
  'United Kingdom': 'uk',
  'US Minor outlying Islands': 'um',
  'United States': 'us',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
  'Vatican City State': 'va',
  'St. Vincent& Grenadines': 'vc',
  Venezuela: 've',
  'VirginIslands (GB)': 'vg',
  'Virgin Islands (US)': 'vi',
  Vietnam: 'vn',
  Vanuatu: 'vu',
  'Wallis & Futuna Islands': 'wf',
  Samoa: 'ws',
  Yemen: 'ye',
  Mayotte: 'yt',
  'Yugoslavia (obsolete)': 'yu',
  'South Africa': 'za',
  Zambia: 'zm',
  Zaire: 'zr',
  Zimbabwe: 'zw',
};

export default (props: any) => {
  const country = props.value;
  const code = lookup[country];

  return (
    <span>
      <img
        src={`https://flagcdn.com/w20/${code}.png`}
        width="20"
        alt="{country}"
      />
      &nbsp;&nbsp;{country}
    </span>
  );
};
