# Suggested metadata entries for undocumented configs

    "ADDITIONAL_MIDDLEWARE": ConfigMetadata(
        key="ADDITIONAL_MIDDLEWARE",
        type=list,
        default=[],
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "ADDITIONAL_MODULE_DS_MAP": ConfigMetadata(
        key="ADDITIONAL_MODULE_DS_MAP",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "ADVANCED_DATA_TYPES": ConfigMetadata(
        key="ADVANCED_DATA_TYPES",
        type=dict,
        default=dict(),
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<dict instance>",
    ),

    "ALEMBIC_SKIP_LOG_CONFIG": ConfigMetadata(
        key="ALEMBIC_SKIP_LOG_CONFIG",
        type=bool,
        default=False,
        description="If True, we will skip the call to load the logger config found in alembic.init",
        category="logging",
        impact="medium",
        requires_restart=False,
    ),

    "ALERT_MINIMUM_INTERVAL": ConfigMetadata(
        key="ALERT_MINIMUM_INTERVAL",
        type=int,
        default=0,
        description="Set a minimum interval threshold between executions (for each Alert/Report) Value should be an integer i.e. int(timedelta(minutes=5).total_seconds()) You can also assign a function to the config that returns the expected integer",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "ALERT_REPORTS_CRON_WINDOW_SIZE": ConfigMetadata(
        key="ALERT_REPORTS_CRON_WINDOW_SIZE",
        type=int,
        default=59,
        description="--------------------------------------------------- Alerts & Reports --------------------------------------------------- Used for Alerts/Reports (Feature flask ALERT_REPORTS) to set the size for the sliding cron window size, should be synced with the celery beat config minus 1 second",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "ALERT_REPORTS_DEFAULT_CRON_VALUE": ConfigMetadata(
        key="ALERT_REPORTS_DEFAULT_CRON_VALUE",
        type=str,
        default='0 0 * * *',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "ALERT_REPORTS_DEFAULT_RETENTION": ConfigMetadata(
        key="ALERT_REPORTS_DEFAULT_RETENTION",
        type=int,
        default=90,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "ALERT_REPORTS_DEFAULT_WORKING_TIMEOUT": ConfigMetadata(
        key="ALERT_REPORTS_DEFAULT_WORKING_TIMEOUT",
        type=int,
        default=3600,
        description="Default values that user using when creating alert",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "ALERT_REPORTS_EXECUTORS": ConfigMetadata(
        key="ALERT_REPORTS_EXECUTORS",
        type=list,
        default=[<ExecutorType.OWNER: 'owner'>],
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "ALERT_REPORTS_MAX_CUSTOM_SCREENSHOT_WIDTH": ConfigMetadata(
        key="ALERT_REPORTS_MAX_CUSTOM_SCREENSHOT_WIDTH",
        type=int,
        default=2400,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "ALERT_REPORTS_MIN_CUSTOM_SCREENSHOT_WIDTH": ConfigMetadata(
        key="ALERT_REPORTS_MIN_CUSTOM_SCREENSHOT_WIDTH",
        type=int,
        default=600,
        description="Custom width for screenshots",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "ALERT_REPORTS_NOTIFICATION_DRY_RUN": ConfigMetadata(
        key="ALERT_REPORTS_NOTIFICATION_DRY_RUN",
        type=bool,
        default=False,
        description="If set to true no notification is sent, the worker will just log a message. Useful for debugging",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "ALERT_REPORTS_QUERY_EXECUTION_MAX_TRIES": ConfigMetadata(
        key="ALERT_REPORTS_QUERY_EXECUTION_MAX_TRIES",
        type=int,
        default=1,
        description="Max tries to run queries to prevent false errors caused by transient errors being returned to users. Set to a value >1 to enable retries.",
        category="database",
        impact="medium",
        requires_restart=True,
        min_value=1,
    ),

    "ALERT_REPORTS_WORKING_SOFT_TIME_OUT_LAG": ConfigMetadata(
        key="ALERT_REPORTS_WORKING_SOFT_TIME_OUT_LAG",
        type=int,
        default=1,
        description="if ALERT_REPORTS_WORKING_TIME_OUT_KILL is True, set a celery hard timeout Equal to working timeout + ALERT_REPORTS_WORKING_SOFT_TIME_OUT_LAG",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "ALERT_REPORTS_WORKING_TIME_OUT_KILL": ConfigMetadata(
        key="ALERT_REPORTS_WORKING_TIME_OUT_KILL",
        type=bool,
        default=True,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "ALERT_REPORTS_WORKING_TIME_OUT_LAG": ConfigMetadata(
        key="ALERT_REPORTS_WORKING_TIME_OUT_LAG",
        type=int,
        default=10,
        description="if ALERT_REPORTS_WORKING_TIME_OUT_KILL is True, set a celery hard timeout Equal to working timeout + ALERT_REPORTS_WORKING_TIME_OUT_LAG",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "ALLOWED_EXTENSIONS": ConfigMetadata(
        key="ALLOWED_EXTENSIONS",
        type=set,
        default=set(),
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<set instance>",
    ),

    "ALLOWED_EXTRA_AUTHENTICATIONS": ConfigMetadata(
        key="ALLOWED_EXTRA_AUTHENTICATIONS",
        type=dict,
        default={},
        description="None",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "ALLOWED_USER_CSV_SCHEMA_FUNC": ConfigMetadata(
        key="ALLOWED_USER_CSV_SCHEMA_FUNC",
        type=function,
        default=function(),
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<function instance>",
    ),

    "APP_ICON": ConfigMetadata(
        key="APP_ICON",
        type=str,
        default='/static/assets/images/superset-logo-horiz.png',
        description="Specify the App icon",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "APP_NAME": ConfigMetadata(
        key="APP_NAME",
        type=str,
        default='Superset',
        description="------------------------------ GLOBALS FOR APP Builder ------------------------------ Uncomment to setup Your App name",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "AUTH_DB": ConfigMetadata(
        key="AUTH_DB",
        type=int,
        default=1,
        description="None",
        category="security",
        impact="medium",
        requires_restart=True,
        min_value=1,
    ),

    "AUTH_RATE_LIMIT": ConfigMetadata(
        key="AUTH_RATE_LIMIT",
        type=str,
        default='5 per second',
        description="None",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "AUTH_RATE_LIMITED": ConfigMetadata(
        key="AUTH_RATE_LIMITED",
        type=bool,
        default=True,
        description="None",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "AUTH_TYPE": ConfigMetadata(
        key="AUTH_TYPE",
        type=int,
        default=1,
        description="The authentication type AUTH_OID : Is for OpenID AUTH_DB : Is for database (username/password) AUTH_LDAP : Is for LDAP AUTH_REMOTE_USER : Is for using REMOTE_USER from web server",
        category="security",
        impact="medium",
        requires_restart=True,
        min_value=1,
    ),

    "BABEL_DEFAULT_FOLDER": ConfigMetadata(
        key="BABEL_DEFAULT_FOLDER",
        type=str,
        default='superset/translations',
        description="Your application default translation path",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "BABEL_DEFAULT_LOCALE": ConfigMetadata(
        key="BABEL_DEFAULT_LOCALE",
        type=str,
        default='en',
        description="--------------------------------------------------- Babel config for translations --------------------------------------------------- Setup default language",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "BACKUP_COUNT": ConfigMetadata(
        key="BACKUP_COUNT",
        type=int,
        default=30,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "BASE_DIR": ConfigMetadata(
        key="BASE_DIR",
        type=str,
        default='/Users/max/code/superset/superset',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "BLUEPRINTS": ConfigMetadata(
        key="BLUEPRINTS",
        type=list,
        default=[],
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "BUG_REPORT_ICON": ConfigMetadata(
        key="BUG_REPORT_ICON",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "BUG_REPORT_TEXT": ConfigMetadata(
        key="BUG_REPORT_TEXT",
        type=str,
        default='Report a bug',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "BUG_REPORT_URL": ConfigMetadata(
        key="BUG_REPORT_URL",
        type=NoneType,
        default=None,
        description="Send user to a link where they can report bugs",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "BUILD_NUMBER": ConfigMetadata(
        key="BUILD_NUMBER",
        type=NoneType,
        default=None,
        description="Build number is shown in the About section if available. This can be replaced at build time to expose build information.",
        category="ui",
        impact="medium",
        requires_restart=False,
    ),

    "CACHE_CONFIG": ConfigMetadata(
        key="CACHE_CONFIG",
        type=dict,
        default={'CACHE_TYPE': 'NullCache'},
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "CACHE_DEFAULT_TIMEOUT": ConfigMetadata(
        key="CACHE_DEFAULT_TIMEOUT",
        type=int,
        default=86400,
        description="--------------------------------------------------- Cache configuration --------------------------------------------------- Default cache timeout, applies to all cache backends unless specifically overridden in each cache config.",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "CACHE_WARMUP_EXECUTORS": ConfigMetadata(
        key="CACHE_WARMUP_EXECUTORS",
        type=list,
        default=[<ExecutorType.OWNER: 'owner'>],
        description="a fixed user (admin in this example), use the following configuration: from superset.tasks.types import ExecutorType, FixedExecutor CACHE_WARMUP_EXECUTORS = [ExecutorType.OWNER, FixedExecutor("admin")]",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "CATALOGS_SIMPLIFIED_MIGRATION": ConfigMetadata(
        key="CATALOGS_SIMPLIFIED_MIGRATION",
        type=bool,
        default=False,
        description="None",
        category="logging",
        impact="medium",
        requires_restart=False,
    ),

    "CELERY_BEAT_SCHEDULER_EXPIRES": ConfigMetadata(
        key="CELERY_BEAT_SCHEDULER_EXPIRES",
        type=timedelta,
        default=timedelta(),
        description="This is used as a workaround for the alerts & reports scheduler task to get the time celery beat triggered it, see https://github.com/celery/celery/issues/6974 for details",
        category="async",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<timedelta instance>",
    ),

    "CELERY_CONFIG": ConfigMetadata(
        key="CELERY_CONFIG",
        type=type,
        default=type(),
        description="None",
        category="async",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<type instance>",
    ),

    "CHANGE_ME_SECRET_KEY": ConfigMetadata(
        key="CHANGE_ME_SECRET_KEY",
        type=str,
        default='CHANGE_ME_TO_A_COMPLEX_RANDOM_SECRET',
        description="None",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "COLUMNAR_EXTENSIONS": ConfigMetadata(
        key="COLUMNAR_EXTENSIONS",
        type=set,
        default=set(),
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<set instance>",
    ),

    "COMMON_BOOTSTRAP_OVERRIDES_FUNC": ConfigMetadata(
        key="COMMON_BOOTSTRAP_OVERRIDES_FUNC",
        type=function,
        default=function(),
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<function instance>",
    ),

    "CONFIG_PATH_ENV_VAR": ConfigMetadata(
        key="CONFIG_PATH_ENV_VAR",
        type=str,
        default='SUPERSET_CONFIG_PATH',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "CONTENT_SECURITY_POLICY_WARNING": ConfigMetadata(
        key="CONTENT_SECURITY_POLICY_WARNING",
        type=bool,
        default=True,
        description="Enable/disable CSP warning",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "CORS_OPTIONS": ConfigMetadata(
        key="CORS_OPTIONS",
        type=dict,
        default={'origins': ['https://tile.openstreetmap.org', 'https://tile.osm.ch']},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "CSV_DEFAULT_NA_NAMES": ConfigMetadata(
        key="CSV_DEFAULT_NA_NAMES",
        type=list,
        default=['1.#QNAN', '', '#N/A N/A', 'nan', 'None', '-1.#QNAN', '-1.#IND', 'NULL', 'NA', '-NaN', 'null', 'NaN', '#N/A', '-nan', '<NA>', '1.#IND', 'N/A', '#NA', 'n/a'],
        description="Values that should be treated as nulls for the csv uploads.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "CSV_EXPORT": ConfigMetadata(
        key="CSV_EXPORT",
        type=dict,
        default={'encoding': 'utf-8-sig'},
        description="CSV Options: key/value pairs that will be passed as argument to DataFrame.to_csv method. note: index option should not be overridden",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "CSV_EXTENSIONS": ConfigMetadata(
        key="CSV_EXTENSIONS",
        type=set,
        default=set(),
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<set instance>",
    ),

    "CSV_TO_HIVE_UPLOAD_DIRECTORY": ConfigMetadata(
        key="CSV_TO_HIVE_UPLOAD_DIRECTORY",
        type=str,
        default='EXTERNAL_HIVE_TABLES/',
        description="The directory within the bucket specified above that will contain all the external tables",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "CSV_TO_HIVE_UPLOAD_DIRECTORY_FUNC": ConfigMetadata(
        key="CSV_TO_HIVE_UPLOAD_DIRECTORY_FUNC",
        type=function,
        default=function(),
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<function instance>",
    ),

    "CSV_TO_HIVE_UPLOAD_S3_BUCKET": ConfigMetadata(
        key="CSV_TO_HIVE_UPLOAD_S3_BUCKET",
        type=NoneType,
        default=None,
        description="The S3 bucket where you want to store your external hive tables created from CSV files. For example, 'companyname-superset'",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "CURRENCIES": ConfigMetadata(
        key="CURRENCIES",
        type=list,
        default=['USD', 'EUR', 'GBP', 'INR', 'MXN', 'JPY', 'CNY'],
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "CUSTOM_SECURITY_MANAGER": ConfigMetadata(
        key="CUSTOM_SECURITY_MANAGER",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "CUSTOM_TEMPLATE_PROCESSORS": ConfigMetadata(
        key="CUSTOM_TEMPLATE_PROCESSORS",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "D3_FORMAT": ConfigMetadata(
        key="D3_FORMAT",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "D3_TIME_FORMAT": ConfigMetadata(
        key="D3_TIME_FORMAT",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DASHBOARD_AUTO_REFRESH_INTERVALS": ConfigMetadata(
        key="DASHBOARD_AUTO_REFRESH_INTERVALS",
        type=list,
        default=[[0, "Don't refresh"], [10, '10 seconds'], [30, '30 seconds'], [60, '1 minute'], [300, '5 minutes'], [1800, '30 minutes'], [3600, '1 hour'], [21600, '6 hours'], [43200, '12 hours'], [86400, '24 hours']],
        description="Dashboard auto refresh intervals",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DASHBOARD_AUTO_REFRESH_MODE": ConfigMetadata(
        key="DASHBOARD_AUTO_REFRESH_MODE",
        type=str,
        default='force',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DASHBOARD_TEMPLATE_ID": ConfigMetadata(
        key="DASHBOARD_TEMPLATE_ID",
        type=NoneType,
        default=None,
        description="The id of a template dashboard that should be copied to every new user",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DATABASE_OAUTH2_CLIENTS": ConfigMetadata(
        key="DATABASE_OAUTH2_CLIENTS",
        type=dict,
        default={},
        description="None",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "DATABASE_OAUTH2_JWT_ALGORITHM": ConfigMetadata(
        key="DATABASE_OAUTH2_JWT_ALGORITHM",
        type=str,
        default='HS256',
        description="OAuth2 state is encoded in a JWT using the alogorithm below.",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "DATABASE_OAUTH2_TIMEOUT": ConfigMetadata(
        key="DATABASE_OAUTH2_TIMEOUT",
        type=timedelta,
        default=timedelta(),
        description="applications. In that case, the proxy can forward the request to the correct instance by looking at the `default_redirect_uri` attribute in the OAuth2 state object. DATABASE_OAUTH2_REDIRECT_URI = "http://localhost:8088/api/v1/database/oauth2/" Timeout when fetching access and refresh tokens.",
        category="security",
        impact="medium",
        requires_restart=True,
        serializable=False,
        doc_default="<timedelta instance>",
    ),

    "DATASET_HEALTH_CHECK": ConfigMetadata(
        key="DATASET_HEALTH_CHECK",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DATASET_IMPORT_ALLOWED_DATA_URLS": ConfigMetadata(
        key="DATASET_IMPORT_ALLOWED_DATA_URLS",
        type=list,
        default=['.*'],
        description="Define a list of allowed URLs for dataset data imports (v1). Simple example to only allow URLs that belong to certain domains: ALLOWED_IMPORT_URL_DOMAINS = [ r"^https://.+\.domain1\.com\/?.*", r"^https://.+\.domain2\.com\/?.*" ]",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DATA_CACHE_CONFIG": ConfigMetadata(
        key="DATA_CACHE_CONFIG",
        type=dict,
        default={'CACHE_TYPE': 'NullCache'},
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "DATA_DIR": ConfigMetadata(
        key="DATA_DIR",
        type=str,
        default='/Users/max/.superset',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DBS_AVAILABLE_DENYLIST": ConfigMetadata(
        key="DBS_AVAILABLE_DENYLIST",
        type=dict,
        default={},
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "DB_CONNECTION_MUTATOR": ConfigMetadata(
        key="DB_CONNECTION_MUTATOR",
        type=NoneType,
        default=None,
        description="uri.username = user.email return uri, params Note that the returned uri and params are passed directly to sqlalchemy's as such `create_engine(url, **params)`",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "DB_POLL_INTERVAL_SECONDS": ConfigMetadata(
        key="DB_POLL_INTERVAL_SECONDS",
        type=dict,
        default={},
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "DB_SQLA_URI_VALIDATOR": ConfigMetadata(
        key="DB_SQLA_URI_VALIDATOR",
        type=NoneType,
        default=None,
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "DEBUG": ConfigMetadata(
        key="DEBUG",
        type=bool,
        default=False,
        description="Whether to run the web server in debug mode or not",
        category="logging",
        impact="medium",
        requires_restart=False,
    ),

    "DECKGL_BASE_MAP": ConfigMetadata(
        key="DECKGL_BASE_MAP",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DEFAULT_DB_ID": ConfigMetadata(
        key="DEFAULT_DB_ID",
        type=NoneType,
        default=None,
        description="The db id here results in selecting this one as a default in SQL Lab",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "DEFAULT_FEATURE_FLAGS": ConfigMetadata(
        key="DEFAULT_FEATURE_FLAGS",
        type=dict,
        default={'DRUID_JOINS': False, 'DYNAMIC_PLUGINS': False, 'ENABLE_TEMPLATE_PROCESSING': False, 'ENABLE_JAVASCRIPT_CONTROLS': False, 'PRESTO_EXPAND_DATA': False, 'THUMBNAILS': False, 'ENABLE_DASHBOARD_SCREENSHOT_ENDPOINTS': False, 'ENABLE_DASHBOARD_DOWNLOAD_WEBDRIVER_SCREENSHOT': False, 'TAGGING_SYSTEM': False, 'SQLLAB_BACKEND_PERSISTENCE': True, 'LISTVIEWS_DEFAULT_CARD_VIEW': False, 'ESCAPE_MARKDOWN_HTML': False, 'DASHBOARD_VIRTUALIZATION': True, 'GLOBAL_ASYNC_QUERIES': False, 'EMBEDDED_SUPERSET': False, 'ALERT_REPORTS': False, 'ALERT_REPORT_TABS': False, 'ALERT_REPORT_SLACK_V2': False, 'DASHBOARD_RBAC': False, 'ENABLE_ADVANCED_DATA_TYPES': False, 'ALERTS_ATTACH_REPORTS': True, 'ALLOW_FULL_CSV_EXPORT': False, 'ALLOW_ADHOC_SUBQUERY': False, 'USE_ANALOGOUS_COLORS': False, 'RLS_IN_SQLLAB': False, 'OPTIMIZE_SQL': False, 'IMPERSONATE_WITH_EMAIL_PREFIX': False, 'CACHE_IMPERSONATION': False, 'CACHE_QUERY_BY_USER': False, 'EMBEDDABLE_CHARTS': True, 'DRILL_TO_DETAIL': True, 'DRILL_BY': True, 'DATAPANEL_CLOSED_BY_DEFAULT': False, 'FILTERBAR_CLOSED_BY_DEFAULT': False, 'ESTIMATE_QUERY_COST': False, 'SSH_TUNNELING': False, 'AVOID_COLORS_COLLISION': True, 'MENU_HIDE_USER_INFO': False, 'ENABLE_SUPERSET_META_DB': False, 'PLAYWRIGHT_REPORTS_AND_THUMBNAILS': False, 'CHART_PLUGINS_EXPERIMENTAL': False, 'SQLLAB_FORCE_RUN_ASYNC': False, 'ENABLE_FACTORY_RESET_COMMAND': False, 'SLACK_ENABLE_AVATARS': False, 'CSS_TEMPLATES': True, 'DATE_FORMAT_IN_EMAIL_SUBJECT': False, 'DATASET_FOLDERS': False, 'AG_GRID_TABLE_ENABLED': False, 'TABLE_V2_TIME_COMPARISON_ENABLED': False},
        description="None",
        category="features",
        impact="medium",
        requires_restart=False,
    ),

    "DEFAULT_HTTP_HEADERS": ConfigMetadata(
        key="DEFAULT_HTTP_HEADERS",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DEFAULT_MODULE_DS_MAP": ConfigMetadata(
        key="DEFAULT_MODULE_DS_MAP",
        type=OrderedDict,
        default=OrderedDict([('superset.connectors.sqla.models', ['SqlaTable'])]),
        description="-------------------------------------------------- Modules, datasources and middleware to be registered --------------------------------------------------",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DEFAULT_RELATIVE_END_TIME": ConfigMetadata(
        key="DEFAULT_RELATIVE_END_TIME",
        type=str,
        default='today',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DEFAULT_RELATIVE_START_TIME": ConfigMetadata(
        key="DEFAULT_RELATIVE_START_TIME",
        type=str,
        default='today',
        description="'now' means it is relative to the query issue time If both start and end time is set to now, this will make the time filter a moving window. By only setting the end time to now, start time will be set to midnight, while end will be relative to the query issue time.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DEFAULT_SQLLAB_LIMIT": ConfigMetadata(
        key="DEFAULT_SQLLAB_LIMIT",
        type=int,
        default=1000,
        description="Default row limit for SQL Lab queries. Is overridden by setting a new limit in the SQL Lab UI",
        category="database",
        impact="medium",
        requires_restart=True,
        min_value=1,
    ),

    "DEFAULT_TIME_FILTER": ConfigMetadata(
        key="DEFAULT_TIME_FILTER",
        type=str,
        default='No filter',
        description="default time filter in explore values may be "Last day", "Last week", "<ISO date> : now", etc.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DEFAULT_VIZ_TYPE": ConfigMetadata(
        key="DEFAULT_VIZ_TYPE",
        type=str,
        default='table',
        description="default viz used in chart explorer & SQL Lab explore",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DISALLOWED_SQL_FUNCTIONS": ConfigMetadata(
        key="DISALLOWED_SQL_FUNCTIONS",
        type=dict,
        default=dict(),
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
        serializable=False,
        doc_default="<dict instance>",
    ),

    "DISPLAY_MAX_ROW": ConfigMetadata(
        key="DISPLAY_MAX_ROW",
        type=int,
        default=10000,
        description="Maximum number of rows displayed in SQL Lab UI Is set to avoid out of memory/localstorage issues in browsers. Does not affect exported CSVs",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "DOCUMENTATION_ICON": ConfigMetadata(
        key="DOCUMENTATION_ICON",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DOCUMENTATION_TEXT": ConfigMetadata(
        key="DOCUMENTATION_TEXT",
        type=str,
        default='Documentation',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "DOCUMENTATION_URL": ConfigMetadata(
        key="DOCUMENTATION_URL",
        type=NoneType,
        default=None,
        description="Send user to a link where they can read more about Superset",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "EMAIL_HEADER_MUTATOR": ConfigMetadata(
        key="EMAIL_HEADER_MUTATOR",
        type=function,
        default=function(),
        description="None",
        category="email",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<function instance>",
    ),

    "EMAIL_PAGE_RENDER_WAIT": ConfigMetadata(
        key="EMAIL_PAGE_RENDER_WAIT",
        type=int,
        default=30,
        description="Time selenium will wait for the page to load and render for the email report.",
        category="email",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "EMAIL_REPORTS_CTA": ConfigMetadata(
        key="EMAIL_REPORTS_CTA",
        type=str,
        default='Explore in Superset',
        description="The text for call-to-action link in Alerts & Reports emails",
        category="email",
        impact="medium",
        requires_restart=False,
    ),

    "EMAIL_REPORTS_SUBJECT_PREFIX": ConfigMetadata(
        key="EMAIL_REPORTS_SUBJECT_PREFIX",
        type=str,
        default='[Report] ',
        description="A custom prefix to use on all Alerts & Reports emails",
        category="email",
        impact="medium",
        requires_restart=False,
    ),

    "ENABLE_CHUNK_ENCODING": ConfigMetadata(
        key="ENABLE_CHUNK_ENCODING",
        type=bool,
        default=False,
        description="None",
        category="features",
        impact="medium",
        requires_restart=False,
    ),

    "ENABLE_CORS": ConfigMetadata(
        key="ENABLE_CORS",
        type=bool,
        default=True,
        description="CORS Options NOTE: enabling this requires installing the cors-related python dependencies `pip install .[cors]` or `pip install apache_superset[cors]`, depending",
        category="features",
        impact="medium",
        requires_restart=False,
    ),

    "ENABLE_PROXY_FIX": ConfigMetadata(
        key="ENABLE_PROXY_FIX",
        type=bool,
        default=False,
        description="Use all X-Forwarded headers when ENABLE_PROXY_FIX is True. When proxying to a different port, set "x_port" to 0 to avoid downstream issues.",
        category="features",
        impact="medium",
        requires_restart=False,
    ),

    "ENABLE_TIME_ROTATE": ConfigMetadata(
        key="ENABLE_TIME_ROTATE",
        type=bool,
        default=False,
        description="--------------------------------------------------- Enable Time Rotate Log Handler --------------------------------------------------- LOG_LEVEL = DEBUG, INFO, WARNING, ERROR, CRITICAL",
        category="features",
        impact="medium",
        requires_restart=False,
    ),

    "ENGINE_CONTEXT_MANAGER": ConfigMetadata(
        key="ENGINE_CONTEXT_MANAGER",
        type=function,
        default=function(),
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
        serializable=False,
        doc_default="<function instance>",
    ),

    "ENVIRONMENT_TAG_CONFIG": ConfigMetadata(
        key="ENVIRONMENT_TAG_CONFIG",
        type=dict,
        default={'variable': 'SUPERSET_ENV', 'values': {'debug': {'color': 'error.base', 'text': 'flask-debug'}, 'development': {'color': 'error.base', 'text': 'Development'}, 'production': {'color': '', 'text': ''}}},
        description="Configuration for environment tag shown on the navbar. Setting 'text' to '' will hide the tag.  # noqa: E501 'color' can either be a hex color code, or a dot-indexed theme color (e.g. error.base)",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "EXCEL_EXPORT": ConfigMetadata(
        key="EXCEL_EXPORT",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "EXCEL_EXTENSIONS": ConfigMetadata(
        key="EXCEL_EXTENSIONS",
        type=set,
        default=set(),
        description="Allowed format types for upload on Database view",
        category="general",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<set instance>",
    ),

    "EXCLUDE_USERS_FROM_LISTS": ConfigMetadata(
        key="EXCLUDE_USERS_FROM_LISTS",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "EXPLORE_FORM_DATA_CACHE_CONFIG": ConfigMetadata(
        key="EXPLORE_FORM_DATA_CACHE_CONFIG",
        type=dict,
        default=dict(),
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<dict instance>",
    ),

    "EXTRA_CATEGORICAL_COLOR_SCHEMES": ConfigMetadata(
        key="EXTRA_CATEGORICAL_COLOR_SCHEMES",
        type=list,
        default=[],
        description="None",
        category="ui",
        impact="medium",
        requires_restart=False,
    ),

    "EXTRA_DYNAMIC_QUERY_FILTERS": ConfigMetadata(
        key="EXTRA_DYNAMIC_QUERY_FILTERS",
        type=dict,
        default={},
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "EXTRA_RELATED_QUERY_FILTERS": ConfigMetadata(
        key="EXTRA_RELATED_QUERY_FILTERS",
        type=dict,
        default={},
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "EXTRA_SEQUENTIAL_COLOR_SCHEMES": ConfigMetadata(
        key="EXTRA_SEQUENTIAL_COLOR_SCHEMES",
        type=list,
        default=[],
        description="None",
        category="ui",
        impact="medium",
        requires_restart=False,
    ),

    "FAB_ADD_SECURITY_API": ConfigMetadata(
        key="FAB_ADD_SECURITY_API",
        type=bool,
        default=True,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "FAB_ADD_SECURITY_PERMISSION_VIEW": ConfigMetadata(
        key="FAB_ADD_SECURITY_PERMISSION_VIEW",
        type=bool,
        default=False,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "FAB_ADD_SECURITY_PERMISSION_VIEWS_VIEW": ConfigMetadata(
        key="FAB_ADD_SECURITY_PERMISSION_VIEWS_VIEW",
        type=bool,
        default=False,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "FAB_ADD_SECURITY_VIEWS": ConfigMetadata(
        key="FAB_ADD_SECURITY_VIEWS",
        type=bool,
        default=True,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "FAB_ADD_SECURITY_VIEW_MENU_VIEW": ConfigMetadata(
        key="FAB_ADD_SECURITY_VIEW_MENU_VIEW",
        type=bool,
        default=False,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "FAB_API_SWAGGER_UI": ConfigMetadata(
        key="FAB_API_SWAGGER_UI",
        type=bool,
        default=True,
        description="Enables SWAGGER UI for superset openapi spec ex: http://localhost:8080/swagger/v1",
        category="ui",
        impact="medium",
        requires_restart=False,
    ),

    "FAVICONS": ConfigMetadata(
        key="FAVICONS",
        type=list,
        default=[{'href': '/static/assets/images/favicon.png'}],
        description=""href":path/to/image.png", "sizes": "16x16", "type": "image/png" "rel": "icon" },",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "FILENAME": ConfigMetadata(
        key="FILENAME",
        type=str,
        default='/Users/max/.superset/superset.log',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "FILTER_SELECT_ROW_LIMIT": ConfigMetadata(
        key="FILTER_SELECT_ROW_LIMIT",
        type=int,
        default=10000,
        description="max rows retrieved by filter select auto complete",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "FILTER_STATE_CACHE_CONFIG": ConfigMetadata(
        key="FILTER_STATE_CACHE_CONFIG",
        type=dict,
        default=dict(),
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<dict instance>",
    ),

    "FLASK_APP_MUTATOR": ConfigMetadata(
        key="FLASK_APP_MUTATOR",
        type=NoneType,
        default=None,
        description="If a callable is specified, it will be called at app startup while passing a reference to the Flask app. This can be used to alter the Flask app in whatever way. example: FLASK_APP_MUTATOR = lambda x: x.before_request = f",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "FLASK_USE_RELOAD": ConfigMetadata(
        key="FLASK_USE_RELOAD",
        type=bool,
        default=True,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "GET_FEATURE_FLAGS_FUNC": ConfigMetadata(
        key="GET_FEATURE_FLAGS_FUNC",
        type=NoneType,
        default=None,
        description="None",
        category="features",
        impact="medium",
        requires_restart=False,
    ),

    "GLOBAL_ASYNC_QUERIES_CACHE_BACKEND": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_CACHE_BACKEND",
        type=dict,
        default={'CACHE_TYPE': 'RedisCache', 'CACHE_REDIS_HOST': 'localhost', 'CACHE_REDIS_PORT': 6379, 'CACHE_REDIS_USER': '', 'CACHE_REDIS_PASSWORD': '', 'CACHE_REDIS_DB': 0, 'CACHE_DEFAULT_TIMEOUT': 300, 'CACHE_REDIS_SENTINELS': [('localhost', 26379)], 'CACHE_REDIS_SENTINEL_MASTER': 'mymaster', 'CACHE_REDIS_SENTINEL_PASSWORD': None, 'CACHE_REDIS_SSL': False, 'CACHE_REDIS_SSL_CERTFILE': None, 'CACHE_REDIS_SSL_KEYFILE': None, 'CACHE_REDIS_SSL_CERT_REQS': 'required', 'CACHE_REDIS_SSL_CA_CERTS': None},
        description="Global async queries cache backend configuration options: - Set 'CACHE_TYPE' to 'RedisCache' for RedisCacheBackend. - Set 'CACHE_TYPE' to 'RedisSentinelCache' for RedisSentinelCacheBackend.",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "GLOBAL_ASYNC_QUERIES_JWT_COOKIE_DOMAIN": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_JWT_COOKIE_DOMAIN",
        type=NoneType,
        default=None,
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "GLOBAL_ASYNC_QUERIES_JWT_COOKIE_NAME": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_JWT_COOKIE_NAME",
        type=str,
        default='async-token',
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "GLOBAL_ASYNC_QUERIES_JWT_COOKIE_SAMESITE": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_JWT_COOKIE_SAMESITE",
        type=NoneType,
        default=None,
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "GLOBAL_ASYNC_QUERIES_JWT_COOKIE_SECURE": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_JWT_COOKIE_SECURE",
        type=bool,
        default=False,
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "GLOBAL_ASYNC_QUERIES_JWT_SECRET": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_JWT_SECRET",
        type=str,
        default='test-secret-change-me',
        description="None",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "GLOBAL_ASYNC_QUERIES_POLLING_DELAY": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_POLLING_DELAY",
        type=int,
        default=500,
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "GLOBAL_ASYNC_QUERIES_REDIS_STREAM_LIMIT": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_REDIS_STREAM_LIMIT",
        type=int,
        default=1000,
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "GLOBAL_ASYNC_QUERIES_REDIS_STREAM_LIMIT_FIREHOSE": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_REDIS_STREAM_LIMIT_FIREHOSE",
        type=int,
        default=1000000,
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "GLOBAL_ASYNC_QUERIES_REDIS_STREAM_PREFIX": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_REDIS_STREAM_PREFIX",
        type=str,
        default='async-events-',
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "GLOBAL_ASYNC_QUERIES_REGISTER_REQUEST_HANDLERS": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_REGISTER_REQUEST_HANDLERS",
        type=bool,
        default=True,
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "GLOBAL_ASYNC_QUERIES_TRANSPORT": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_TRANSPORT",
        type=str,
        default='polling',
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "GLOBAL_ASYNC_QUERIES_WEBSOCKET_URL": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERIES_WEBSOCKET_URL",
        type=str,
        default='ws://127.0.0.1:8080/',
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "GLOBAL_ASYNC_QUERY_MANAGER_CLASS": ConfigMetadata(
        key="GLOBAL_ASYNC_QUERY_MANAGER_CLASS",
        type=str,
        default='superset.async_events.async_query_manager.AsyncQueryManager',
        description="Global async query config options. Requires GLOBAL_ASYNC_QUERIES feature flag to be enabled.",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "GUEST_ROLE_NAME": ConfigMetadata(
        key="GUEST_ROLE_NAME",
        type=str,
        default='Public',
        description="Embedded config options",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "GUEST_TOKEN_HEADER_NAME": ConfigMetadata(
        key="GUEST_TOKEN_HEADER_NAME",
        type=str,
        default='X-GuestToken',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "GUEST_TOKEN_JWT_ALGO": ConfigMetadata(
        key="GUEST_TOKEN_JWT_ALGO",
        type=str,
        default='HS256',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "GUEST_TOKEN_JWT_AUDIENCE": ConfigMetadata(
        key="GUEST_TOKEN_JWT_AUDIENCE",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "GUEST_TOKEN_JWT_EXP_SECONDS": ConfigMetadata(
        key="GUEST_TOKEN_JWT_EXP_SECONDS",
        type=int,
        default=300,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "GUEST_TOKEN_JWT_SECRET": ConfigMetadata(
        key="GUEST_TOKEN_JWT_SECRET",
        type=str,
        default='test-guest-secret-change-me',
        description="None",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "GUEST_TOKEN_VALIDATOR_HOOK": ConfigMetadata(
        key="GUEST_TOKEN_VALIDATOR_HOOK",
        type=NoneType,
        default=None,
        description="lambda x: len(x['rls']) == 1 and "tenant_id=" in x['rls'][0]['clause'] Takes the GuestTokenUser dict as an argument Return False from the callable to return a HTTP 400 to the user.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "HTML_SANITIZATION": ConfigMetadata(
        key="HTML_SANITIZATION",
        type=bool,
        default=True,
        description="Sanitizes the HTML content used in markdowns to allow its rendering in a safe manner. Disabling this option is not recommended for security reasons. If you wish to allow valid safe elements that are not included in the default sanitization schema, use the HTML_SANITIZATION_SCHEMA_EXTENSIONS configuration.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "HTML_SANITIZATION_SCHEMA_EXTENSIONS": ConfigMetadata(
        key="HTML_SANITIZATION_SCHEMA_EXTENSIONS",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "HTTP_HEADERS": ConfigMetadata(
        key="HTTP_HEADERS",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "INTERVAL": ConfigMetadata(
        key="INTERVAL",
        type=int,
        default=1,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "IS_FEATURE_ENABLED_FUNC": ConfigMetadata(
        key="IS_FEATURE_ENABLED_FUNC",
        type=NoneType,
        default=None,
        description="None",
        category="features",
        impact="medium",
        requires_restart=False,
    ),

    "JINJA_CONTEXT_ADDONS": ConfigMetadata(
        key="JINJA_CONTEXT_ADDONS",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "LANGUAGES": ConfigMetadata(
        key="LANGUAGES",
        type=dict,
        default={},
        description="The allowed translation for your app",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "LOGO_RIGHT_TEXT": ConfigMetadata(
        key="LOGO_RIGHT_TEXT",
        type=str,
        default='',
        description="None",
        category="logging",
        impact="medium",
        requires_restart=False,
    ),

    "LOGO_TARGET_PATH": ConfigMetadata(
        key="LOGO_TARGET_PATH",
        type=NoneType,
        default=None,
        description="Specify where clicking the logo would take the user' Default value of None will take you to '/superset/welcome' You can also specify a relative URL e.g. '/superset/welcome' or '/dashboards/list' or you can specify a full URL e.g. 'https://foo.bar'",
        category="logging",
        impact="medium",
        requires_restart=False,
    ),

    "LOGO_TOOLTIP": ConfigMetadata(
        key="LOGO_TOOLTIP",
        type=str,
        default='',
        description="Specify tooltip that should appear when hovering over the App Icon/Logo",
        category="logging",
        impact="medium",
        requires_restart=False,
    ),

    "LOG_FORMAT": ConfigMetadata(
        key="LOG_FORMAT",
        type=str,
        default='%(asctime)s:%(levelname)s:%(name)s:%(message)s',
        description="Console Log Settings",
        category="logging",
        impact="medium",
        requires_restart=False,
    ),

    "LOG_LEVEL": ConfigMetadata(
        key="LOG_LEVEL",
        type=int,
        default=20,
        description="None",
        category="logging",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "MACHINE_AUTH_PROVIDER_CLASS": ConfigMetadata(
        key="MACHINE_AUTH_PROVIDER_CLASS",
        type=str,
        default='superset.utils.machine_auth.MachineAuthProvider',
        description="This auth provider is used by background (offline) tasks that need to access protected resources. Can be overridden by end users in order to support custom auth mechanisms",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "MAPBOX_API_KEY": ConfigMetadata(
        key="MAPBOX_API_KEY",
        type=str,
        default='',
        description="Set this API key to enable Mapbox visualizations",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "MUTATE_AFTER_SPLIT": ConfigMetadata(
        key="MUTATE_AFTER_SPLIT",
        type=bool,
        default=False,
        description="It allows for using the SQL_QUERY_MUTATOR function for more than comments Usage: If you want to apply a change to every statement to a given query, set MUTATE_AFTER_SPLIT = True  # noqa: E501 An example use case is if data has role based access controls, and you want to apply a SET ROLE statement alongside every user query. Changing this variable maintains functionality for both the SQL_Lab and Charts.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "MUTATE_ALERT_QUERY": ConfigMetadata(
        key="MUTATE_ALERT_QUERY",
        type=bool,
        default=False,
        description="Boolean config that determines if alert SQL queries should also be mutated or not.",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "NATIVE_FILTER_DEFAULT_ROW_LIMIT": ConfigMetadata(
        key="NATIVE_FILTER_DEFAULT_ROW_LIMIT",
        type=int,
        default=1000,
        description="default row limit for native filters",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "NO_TIME_RANGE": ConfigMetadata(
        key="NO_TIME_RANGE",
        type=str,
        default='No filter',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "OVERRIDE_HTTP_HEADERS": ConfigMetadata(
        key="OVERRIDE_HTTP_HEADERS",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "PACKAGE_JSON_FILE": ConfigMetadata(
        key="PACKAGE_JSON_FILE",
        type=str,
        default='/Users/max/code/superset/superset/static/assets/package.json',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "PERMISSION_INSTRUCTIONS_LINK": ConfigMetadata(
        key="PERMISSION_INSTRUCTIONS_LINK",
        type=str,
        default='',
        description="This link should lead to a page with instructions on how to gain access to a Datasource. It will be placed at the bottom of permissions errors.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "PREFERRED_DATABASES": ConfigMetadata(
        key="PREFERRED_DATABASES",
        type=list,
        default=['PostgreSQL', 'Presto', 'MySQL', 'SQLite'],
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "PRESTO_POLL_INTERVAL": ConfigMetadata(
        key="PRESTO_POLL_INTERVAL",
        type=int,
        default=1,
        description="Interval between consecutive polls when using Presto Engine See here: https://github.com/dropbox/PyHive/blob/8eb0aeab8ca300f3024655419b93dad926c1a351/pyhive/presto.py#L93  # noqa: E501",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "PREVENT_UNSAFE_DB_CONNECTIONS": ConfigMetadata(
        key="PREVENT_UNSAFE_DB_CONNECTIONS",
        type=bool,
        default=True,
        description="Some sqlalchemy connection strings can open Superset to security risks. Typically these should not be allowed.",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "PREVENT_UNSAFE_DEFAULT_URLS_ON_DATASET": ConfigMetadata(
        key="PREVENT_UNSAFE_DEFAULT_URLS_ON_DATASET",
        type=bool,
        default=True,
        description="If true all default urls on datasets will be handled as relative URLs by the frontend",
        category="logging",
        impact="medium",
        requires_restart=False,
    ),

    "PROFILING": ConfigMetadata(
        key="PROFILING",
        type=bool,
        default=False,
        description="Enable profiling of Python calls. Turn this on and append ``?_instrument=1`` to the page to see the call stack.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "PROXY_FIX_CONFIG": ConfigMetadata(
        key="PROXY_FIX_CONFIG",
        type=dict,
        default={'x_for': 1, 'x_proto': 1, 'x_host': 1, 'x_port': 1, 'x_prefix': 1},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "PUBLIC_ROLE_LIKE": ConfigMetadata(
        key="PUBLIC_ROLE_LIKE",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "QUERY_COST_FORMATTERS_BY_ENGINE": ConfigMetadata(
        key="QUERY_COST_FORMATTERS_BY_ENGINE",
        type=dict,
        default={},
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "QUERY_LOGGER": ConfigMetadata(
        key="QUERY_LOGGER",
        type=NoneType,
        default=None,
        description="client=None, security_manager=None, log_params=None, ): pass",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "QUERY_SEARCH_LIMIT": ConfigMetadata(
        key="QUERY_SEARCH_LIMIT",
        type=int,
        default=1000,
        description="The limit of queries fetched for query search",
        category="database",
        impact="medium",
        requires_restart=True,
        min_value=1,
    ),

    "RATELIMIT_APPLICATION": ConfigMetadata(
        key="RATELIMIT_APPLICATION",
        type=str,
        default='50 per second',
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "RATELIMIT_ENABLED": ConfigMetadata(
        key="RATELIMIT_ENABLED",
        type=bool,
        default=False,
        description="FAB Rate limiting: this is a security feature for preventing DDOS attacks. The feature is on by default to make Superset secure by default, but you should fine tune the limits to your needs. You can read more about the different parameters here: https://flask-limiter.readthedocs.io/en/stable/configuration.html",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "REPORT_MINIMUM_INTERVAL": ConfigMetadata(
        key="REPORT_MINIMUM_INTERVAL",
        type=int,
        default=0,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "RESULTS_BACKEND": ConfigMetadata(
        key="RESULTS_BACKEND",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "RESULTS_BACKEND_USE_MSGPACK": ConfigMetadata(
        key="RESULTS_BACKEND_USE_MSGPACK",
        type=bool,
        default=True,
        description="Use PyArrow and MessagePack for async query results serialization, rather than JSON. This feature requires additional testing from the community before it is fully adopted, so this config option is provided in order to disable should breaking issues be discovered.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "ROBOT_PERMISSION_ROLES": ConfigMetadata(
        key="ROBOT_PERMISSION_ROLES",
        type=list,
        default=['Public', 'Gamma', 'Alpha', 'Admin', 'sql_lab'],
        description="Roles that are controlled by the API / Superset and should not be changed by humans.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "ROLLOVER": ConfigMetadata(
        key="ROLLOVER",
        type=str,
        default='midnight',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SCHEDULED_QUERIES": ConfigMetadata(
        key="SCHEDULED_QUERIES",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SCREENSHOT_LOAD_WAIT": ConfigMetadata(
        key="SCREENSHOT_LOAD_WAIT",
        type=int,
        default=60,
        description="Time before selenium times out after waiting for all DOM class elements named "loading" are gone.",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SCREENSHOT_LOCATE_WAIT": ConfigMetadata(
        key="SCREENSHOT_LOCATE_WAIT",
        type=int,
        default=10,
        description="Time before selenium times out after trying to locate an element on the page and wait for that element to load for a screenshot.",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SCREENSHOT_PLAYWRIGHT_DEFAULT_TIMEOUT": ConfigMetadata(
        key="SCREENSHOT_PLAYWRIGHT_DEFAULT_TIMEOUT",
        type=int,
        default=60000,
        description="Default timeout for Playwright browser context for all operations",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SCREENSHOT_PLAYWRIGHT_WAIT_EVENT": ConfigMetadata(
        key="SCREENSHOT_PLAYWRIGHT_WAIT_EVENT",
        type=str,
        default='domcontentloaded',
        description="Event that Playwright waits for when loading a new page Possible values: "load", "commit", "domcontentloaded", "networkidle" Docs: https://playwright.dev/python/docs/api/class-page#page-goto-option-wait-until",
        category="logging",
        impact="medium",
        requires_restart=False,
    ),

    "SCREENSHOT_REPLACE_UNEXPECTED_ERRORS": ConfigMetadata(
        key="SCREENSHOT_REPLACE_UNEXPECTED_ERRORS",
        type=bool,
        default=False,
        description="Replace unexpected errors in screenshots with real error messages",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SCREENSHOT_SELENIUM_ANIMATION_WAIT": ConfigMetadata(
        key="SCREENSHOT_SELENIUM_ANIMATION_WAIT",
        type=int,
        default=5,
        description="Wait for the chart animation, in seconds",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SCREENSHOT_SELENIUM_HEADSTART": ConfigMetadata(
        key="SCREENSHOT_SELENIUM_HEADSTART",
        type=int,
        default=3,
        description="Give selenium an headstart, in seconds",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SCREENSHOT_SELENIUM_RETRIES": ConfigMetadata(
        key="SCREENSHOT_SELENIUM_RETRIES",
        type=int,
        default=5,
        description="Selenium destroy retries",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SCREENSHOT_WAIT_FOR_ERROR_MODAL_INVISIBLE": ConfigMetadata(
        key="SCREENSHOT_WAIT_FOR_ERROR_MODAL_INVISIBLE",
        type=int,
        default=5,
        description="Max time to wait for error message modal to close, in seconds",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SCREENSHOT_WAIT_FOR_ERROR_MODAL_VISIBLE": ConfigMetadata(
        key="SCREENSHOT_WAIT_FOR_ERROR_MODAL_VISIBLE",
        type=int,
        default=5,
        description="Max time to wait for error message modal to show up, in seconds",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SEND_FILE_MAX_AGE_DEFAULT": ConfigMetadata(
        key="SEND_FILE_MAX_AGE_DEFAULT",
        type=int,
        default=31536000,
        description="Other possible config options and backends: # https://flask-session.readthedocs.io/en/latest/config.html Cache static resources.",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SESSION_COOKIE_HTTPONLY": ConfigMetadata(
        key="SESSION_COOKIE_HTTPONLY",
        type=bool,
        default=True,
        description="Flask session cookie options See https://flask.palletsprojects.com/en/1.1.x/security/#set-cookie-options for details",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SESSION_COOKIE_SAMESITE": ConfigMetadata(
        key="SESSION_COOKIE_SAMESITE",
        type=str,
        default='Lax',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SESSION_COOKIE_SECURE": ConfigMetadata(
        key="SESSION_COOKIE_SECURE",
        type=bool,
        default=False,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SESSION_SERVER_SIDE": ConfigMetadata(
        key="SESSION_SERVER_SIDE",
        type=bool,
        default=False,
        description="Whether to use server side sessions from flask-session or Flask secure cookies",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SHOW_STACKTRACE": ConfigMetadata(
        key="SHOW_STACKTRACE",
        type=bool,
        default=False,
        description="Superset allows server-side python stacktraces to be surfaced to the user when this feature is on. This may have security implications and it's more secure to turn it off in production settings.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SILENCE_FAB": ConfigMetadata(
        key="SILENCE_FAB",
        type=bool,
        default=True,
        description="Whether to bump the logging level to ERROR on the flask_appbuilder package Set to False if/when debugging FAB related issues like permission management",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SLACK_API_TOKEN": ConfigMetadata(
        key="SLACK_API_TOKEN",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SLACK_CACHE_TIMEOUT": ConfigMetadata(
        key="SLACK_CACHE_TIMEOUT",
        type=int,
        default=86400,
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SLACK_PROXY": ConfigMetadata(
        key="SLACK_PROXY",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SMTP_HOST": ConfigMetadata(
        key="SMTP_HOST",
        type=str,
        default='localhost',
        description="smtp server configuration",
        category="email",
        impact="medium",
        requires_restart=False,
    ),

    "SMTP_MAIL_FROM": ConfigMetadata(
        key="SMTP_MAIL_FROM",
        type=str,
        default='superset@superset.com',
        description="None",
        category="email",
        impact="medium",
        requires_restart=False,
    ),

    "SMTP_PASSWORD": ConfigMetadata(
        key="SMTP_PASSWORD",
        type=str,
        default='superset',
        description="None",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "SMTP_PORT": ConfigMetadata(
        key="SMTP_PORT",
        type=int,
        default=25,
        description="None",
        category="email",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SMTP_SSL": ConfigMetadata(
        key="SMTP_SSL",
        type=bool,
        default=False,
        description="None",
        category="email",
        impact="medium",
        requires_restart=False,
    ),

    "SMTP_SSL_SERVER_AUTH": ConfigMetadata(
        key="SMTP_SSL_SERVER_AUTH",
        type=bool,
        default=False,
        description="If True creates a default SSL context with ssl.Purpose.CLIENT_AUTH using the default system root CA certificates.",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "SMTP_STARTTLS": ConfigMetadata(
        key="SMTP_STARTTLS",
        type=bool,
        default=True,
        description="None",
        category="email",
        impact="medium",
        requires_restart=False,
    ),

    "SMTP_USER": ConfigMetadata(
        key="SMTP_USER",
        type=str,
        default='superset',
        description="None",
        category="email",
        impact="medium",
        requires_restart=False,
    ),

    "SQLALCHEMY_CUSTOM_PASSWORD_STORE": ConfigMetadata(
        key="SQLALCHEMY_CUSTOM_PASSWORD_STORE",
        type=NoneType,
        default=None,
        description="example: def lookup_password(url): return 'secret' SQLALCHEMY_CUSTOM_PASSWORD_STORE = lookup_password",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "SQLALCHEMY_DATABASE_URI": ConfigMetadata(
        key="SQLALCHEMY_DATABASE_URI",
        type=str,
        default='postgresql+psycopg2://superset:superset@127.0.0.1/superset',
        description="The SQLAlchemy connection string.",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SQLALCHEMY_ENCRYPTED_FIELD_TYPE_ADAPTER": ConfigMetadata(
        key="SQLALCHEMY_ENCRYPTED_FIELD_TYPE_ADAPTER",
        type=ABCMeta,
        default=ABCMeta(),
        description=") raise Exception("Missing app_config kwarg") SQLALCHEMY_ENCRYPTED_FIELD_TYPE_ADAPTER = AesGcmEncryptedAdapter",
        category="database",
        impact="medium",
        requires_restart=True,
        serializable=False,
        doc_default="<ABCMeta instance>",
    ),

    "SQLALCHEMY_ENGINE_OPTIONS": ConfigMetadata(
        key="SQLALCHEMY_ENGINE_OPTIONS",
        type=dict,
        default={},
        description="that may be specific to the database engine you are using. Note that you can use this to set the isolation level of your database, as in `SQLALCHEMY_ENGINE_OPTIONS = {"isolation_level": "READ COMMITTED"}` Also note that we recommend READ COMMITTED for regular operation. Find out more here https://flask-sqlalchemy.palletsprojects.com/en/3.1.x/config/",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SQLALCHEMY_EXAMPLES_URI": ConfigMetadata(
        key="SQLALCHEMY_EXAMPLES_URI",
        type=str,
        default='sqlite:////Users/max/.superset/examples.db?check_same_thread=false',
        description="URI to database storing the example data, points to SQLALCHEMY_DATABASE_URI by default if set to `None`",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SQLALCHEMY_TRACK_MODIFICATIONS": ConfigMetadata(
        key="SQLALCHEMY_TRACK_MODIFICATIONS",
        type=bool,
        default=False,
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SQLA_TABLE_MUTATOR": ConfigMetadata(
        key="SQLA_TABLE_MUTATOR",
        type=function,
        default=function(),
        description="to allow mutating the object with this callback. This can be used to set any properties of the object based on naming conventions and such. You can find examples in the tests. pylint: disable-next=unnecessary-lambda-assignment",
        category="database",
        impact="medium",
        requires_restart=True,
        serializable=False,
        doc_default="<function instance>",
    ),

    "SQLGLOT_DIALECTS_EXTENSIONS": ConfigMetadata(
        key="SQLGLOT_DIALECTS_EXTENSIONS",
        type=dict,
        default={},
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SQLLAB_CTAS_NO_LIMIT": ConfigMetadata(
        key="SQLLAB_CTAS_NO_LIMIT",
        type=bool,
        default=False,
        description="Flag that controls if limit should be enforced on the CTA (create table as queries).",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SQLLAB_CTAS_SCHEMA_NAME_FUNC": ConfigMetadata(
        key="SQLLAB_CTAS_SCHEMA_NAME_FUNC",
        type=NoneType,
        default=None,
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SQLLAB_DEFAULT_DBID": ConfigMetadata(
        key="SQLLAB_DEFAULT_DBID",
        type=NoneType,
        default=None,
        description="SQLLAB_DEFAULT_DBID",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SQLLAB_PAYLOAD_MAX_MB": ConfigMetadata(
        key="SQLLAB_PAYLOAD_MAX_MB",
        type=NoneType,
        default=None,
        description="Max payload size (MB) for SQL Lab to prevent browser hangs with large results.",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SQLLAB_QUERY_COST_ESTIMATE_TIMEOUT": ConfigMetadata(
        key="SQLLAB_QUERY_COST_ESTIMATE_TIMEOUT",
        type=int,
        default=10,
        description="Some databases support running EXPLAIN queries that allow users to estimate query costs before they run. These EXPLAIN queries should have a small timeout.",
        category="database",
        impact="medium",
        requires_restart=True,
        min_value=1,
    ),

    "SQLLAB_QUERY_RESULT_TIMEOUT": ConfigMetadata(
        key="SQLLAB_QUERY_RESULT_TIMEOUT",
        type=int,
        default=0,
        description="Timeout duration for SQL Lab fetching query results by the resultsKey. 0 means no timeout.",
        category="database",
        impact="medium",
        requires_restart=True,
        min_value=1,
    ),

    "SQLLAB_SAVE_WARNING_MESSAGE": ConfigMetadata(
        key="SQLLAB_SAVE_WARNING_MESSAGE",
        type=NoneType,
        default=None,
        description="Adds a warning message on sqllab save query and schedule query modals.",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SQLLAB_SCHEDULE_WARNING_MESSAGE": ConfigMetadata(
        key="SQLLAB_SCHEDULE_WARNING_MESSAGE",
        type=NoneType,
        default=None,
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SQLLAB_VALIDATION_TIMEOUT": ConfigMetadata(
        key="SQLLAB_VALIDATION_TIMEOUT",
        type=int,
        default=10,
        description="Timeout duration for SQL Lab query validation",
        category="database",
        impact="medium",
        requires_restart=True,
        min_value=1,
    ),

    "SQL_MAX_ROW": ConfigMetadata(
        key="SQL_MAX_ROW",
        type=int,
        default=100000,
        description="Maximum number of rows returned for any analytical database query",
        category="database",
        impact="medium",
        requires_restart=True,
        min_value=1,
    ),

    "SQL_QUERY_MUTATOR": ConfigMetadata(
        key="SQL_QUERY_MUTATOR",
        type=function,
        default=function(),
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
        serializable=False,
        doc_default="<function instance>",
    ),

    "SQL_VALIDATORS_BY_ENGINE": ConfigMetadata(
        key="SQL_VALIDATORS_BY_ENGINE",
        type=dict,
        default={'presto': 'PrestoDBSQLValidator', 'postgresql': 'PostgreSQLValidator'},
        description="Configure which SQL validator to use for each engine",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "SSH_TUNNEL_LOCAL_BIND_ADDRESS": ConfigMetadata(
        key="SSH_TUNNEL_LOCAL_BIND_ADDRESS",
        type=str,
        default='127.0.0.1',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SSH_TUNNEL_MANAGER_CLASS": ConfigMetadata(
        key="SSH_TUNNEL_MANAGER_CLASS",
        type=str,
        default='superset.extensions.ssh.SSHManager',
        description="-------------+              |    +----------+ | FIREWALL (only port 22 is open) ----------------------------------------------------------------------",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SSH_TUNNEL_PACKET_TIMEOUT_SEC": ConfigMetadata(
        key="SSH_TUNNEL_PACKET_TIMEOUT_SEC",
        type=float,
        default=1.0,
        description=": Timeout (seconds) for transport socket (``socket.settimeout``)",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "SSH_TUNNEL_TIMEOUT_SEC": ConfigMetadata(
        key="SSH_TUNNEL_TIMEOUT_SEC",
        type=float,
        default=10.0,
        description=": Timeout (seconds) for tunnel connection (open_channel timeout)",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "SSL_CERT_PATH": ConfigMetadata(
        key="SSL_CERT_PATH",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "STATIC_ASSETS_PREFIX": ConfigMetadata(
        key="STATIC_ASSETS_PREFIX",
        type=str,
        default='',
        description="Optional prefix to be added to all static asset paths when rendering the UI. This is useful for hosting assets in an external CDN, for example",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "STORE_CACHE_KEYS_IN_METADATA_DB": ConfigMetadata(
        key="STORE_CACHE_KEYS_IN_METADATA_DB",
        type=bool,
        default=False,
        description="store cache keys by datasource UID (via CacheKey) for custom processing/invalidation",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "STR_NA_VALUES": ConfigMetadata(
        key="STR_NA_VALUES",
        type=set,
        default=set(),
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<set instance>",
    ),

    "SUPERSET_CLIENT_RETRY_ATTEMPTS": ConfigMetadata(
        key="SUPERSET_CLIENT_RETRY_ATTEMPTS",
        type=int,
        default=3,
        description="SupersetClient HTTP retry configuration Controls retry behavior for all HTTP requests made through SupersetClient This helps handle transient server errors (like 502 Bad Gateway) automatically",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SUPERSET_CLIENT_RETRY_BACKOFF_MULTIPLIER": ConfigMetadata(
        key="SUPERSET_CLIENT_RETRY_BACKOFF_MULTIPLIER",
        type=int,
        default=2,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SUPERSET_CLIENT_RETRY_DELAY": ConfigMetadata(
        key="SUPERSET_CLIENT_RETRY_DELAY",
        type=int,
        default=1000,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SUPERSET_CLIENT_RETRY_JITTER_MAX": ConfigMetadata(
        key="SUPERSET_CLIENT_RETRY_JITTER_MAX",
        type=int,
        default=1000,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SUPERSET_CLIENT_RETRY_MAX_DELAY": ConfigMetadata(
        key="SUPERSET_CLIENT_RETRY_MAX_DELAY",
        type=int,
        default=10000,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SUPERSET_CLIENT_RETRY_STATUS_CODES": ConfigMetadata(
        key="SUPERSET_CLIENT_RETRY_STATUS_CODES",
        type=list,
        default=[502, 503, 504],
        description="HTTP status codes that should trigger retries (502, 503, 504 gateway errors)",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SUPERSET_DASHBOARD_PERIODICAL_REFRESH_LIMIT": ConfigMetadata(
        key="SUPERSET_DASHBOARD_PERIODICAL_REFRESH_LIMIT",
        type=int,
        default=0,
        description="this 2 settings are used by dashboard period force refresh feature When user choose auto force refresh frequency < SUPERSET_DASHBOARD_PERIODICAL_REFRESH_LIMIT they will see warning message in the Refresh Interval Modal. please check PR #9886",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SUPERSET_DASHBOARD_PERIODICAL_REFRESH_WARNING_MESSAGE": ConfigMetadata(
        key="SUPERSET_DASHBOARD_PERIODICAL_REFRESH_WARNING_MESSAGE",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SUPERSET_DASHBOARD_POSITION_DATA_LIMIT": ConfigMetadata(
        key="SUPERSET_DASHBOARD_POSITION_DATA_LIMIT",
        type=int,
        default=65535,
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SUPERSET_LOG_VIEW": ConfigMetadata(
        key="SUPERSET_LOG_VIEW",
        type=bool,
        default=True,
        description="None",
        category="logging",
        impact="medium",
        requires_restart=False,
    ),

    "SUPERSET_META_DB_LIMIT": ConfigMetadata(
        key="SUPERSET_META_DB_LIMIT",
        type=int,
        default=1000,
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
        min_value=1,
    ),

    "SUPERSET_SECURITY_VIEW_MENU": ConfigMetadata(
        key="SUPERSET_SECURITY_VIEW_MENU",
        type=bool,
        default=True,
        description="This config is used to enable/disable the folowing security menu items: List Users, List Roles, List Groups",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SUPERSET_WEBSERVER_DOMAINS": ConfigMetadata(
        key="SUPERSET_WEBSERVER_DOMAINS",
        type=NoneType,
        default=None,
        description="than 6 slices in dashboard, a lot of time fetch requests are queued up and wait for next available socket. PR #5039 added domain sharding for Superset, and this feature can be enabled by configuration only (by default Superset doesn't allow cross-domain request). This feature is deprecated, annd will be removed in the next major version of Superset, as enabling HTTP2 will serve the same goals.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "SUPERSET_WEBSERVER_TIMEOUT": ConfigMetadata(
        key="SUPERSET_WEBSERVER_TIMEOUT",
        type=int,
        default=60,
        description="This is an important setting, and should be lower than your [load balancer / proxy / envoy / kong / ...] timeout settings. You should also make sure to configure your WSGI server (gunicorn, nginx, apache, ...) timeout setting to be <= to this setting",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "SYNC_DB_PERMISSIONS_IN_ASYNC_MODE": ConfigMetadata(
        key="SYNC_DB_PERMISSIONS_IN_ASYNC_MODE",
        type=bool,
        default=False,
        description="None",
        category="database",
        impact="medium",
        requires_restart=True,
    ),

    "TABLE_VIZ_MAX_ROW_SERVER": ConfigMetadata(
        key="TABLE_VIZ_MAX_ROW_SERVER",
        type=int,
        default=500000,
        description="Maximum number of rows for any query with Server Pagination in Table Viz type",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "TALISMAN_CONFIG": ConfigMetadata(
        key="TALISMAN_CONFIG",
        type=dict,
        default={'content_security_policy': {'base-uri': ["'self'"], 'default-src': ["'self'"], 'img-src': ["'self'", 'blob:', 'data:', 'https://apachesuperset.gateway.scarf.sh', 'https://static.scarf.sh/', 'ows.terrestris.de', 'https://cdn.document360.io'], 'worker-src': ["'self'", 'blob:'], 'connect-src': ["'self'", 'https://api.mapbox.com', 'https://events.mapbox.com', 'https://tile.openstreetmap.org', 'https://tile.osm.ch'], 'object-src': "'none'", 'style-src': ["'self'", "'unsafe-inline'"], 'script-src': ["'self'", "'strict-dynamic'"]}, 'content_security_policy_nonce_in': ['script-src'], 'force_https': False, 'session_cookie_secure': False},
        description="If you want Talisman, how do you want it configured?? For more information on setting up Talisman, please refer to https://superset.apache.org/docs/configuration/networking-settings/#changing-flask-talisman-csp",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "TALISMAN_DEV_CONFIG": ConfigMetadata(
        key="TALISMAN_DEV_CONFIG",
        type=dict,
        default={'content_security_policy': {'base-uri': ["'self'"], 'default-src': ["'self'"], 'img-src': ["'self'", 'blob:', 'data:', 'https://apachesuperset.gateway.scarf.sh', 'https://static.scarf.sh/', 'https://cdn.brandfolder.io', 'ows.terrestris.de', 'https://cdn.document360.io'], 'worker-src': ["'self'", 'blob:'], 'connect-src': ["'self'", 'https://api.mapbox.com', 'https://events.mapbox.com', 'https://tile.openstreetmap.org', 'https://tile.osm.ch'], 'object-src': "'none'", 'style-src': ["'self'", "'unsafe-inline'"], 'script-src': ["'self'", "'unsafe-inline'", "'unsafe-eval'"]}, 'content_security_policy_nonce_in': ['script-src'], 'force_https': False, 'session_cookie_secure': False},
        description="React requires `eval` to work correctly in dev mode",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "TALISMAN_ENABLED": ConfigMetadata(
        key="TALISMAN_ENABLED",
        type=bool,
        default=False,
        description="Do you want Talisman enabled?",
        category="features",
        impact="medium",
        requires_restart=False,
    ),

    "TEST_DATABASE_CONNECTION_TIMEOUT": ConfigMetadata(
        key="TEST_DATABASE_CONNECTION_TIMEOUT",
        type=timedelta,
        default=timedelta(),
        description="When adding a new database we try to connect to it. Depending on which parameters are incorrect this could take a couple minutes, until the SQLAlchemy driver pinging the database times out. Instead of relying on the driver timeout we can specify a shorter one here.",
        category="database",
        impact="medium",
        requires_restart=True,
        serializable=False,
        doc_default="<timedelta instance>",
    ),

    "THEME_DARK": ConfigMetadata(
        key="THEME_DARK",
        type=dict,
        default={'algorithm': 'dark'},
        description="None",
        category="ui",
        impact="medium",
        requires_restart=False,
    ),

    "THEME_SETTINGS": ConfigMetadata(
        key="THEME_SETTINGS",
        type=dict,
        default={'enforced': False, 'allowSwitching': True, 'allowOSPreference': True},
        description="- enforced: Forces the default theme always, overriding all other settings - allowSwitching: Allows users to manually switch between default and dark themes. - allowOSPreference: Allows the app to automatically use the system's preferred theme mode  # noqa: E501 Example:",
        category="ui",
        impact="medium",
        requires_restart=False,
    ),

    "THUMBNAIL_CACHE_CONFIG": ConfigMetadata(
        key="THUMBNAIL_CACHE_CONFIG",
        type=dict,
        default={'CACHE_TYPE': 'NullCache', 'CACHE_DEFAULT_TIMEOUT': 604800, 'CACHE_NO_NULL_WARNING': True},
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
    ),

    "THUMBNAIL_CHART_DIGEST_FUNC": ConfigMetadata(
        key="THUMBNAIL_CHART_DIGEST_FUNC",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "THUMBNAIL_DASHBOARD_DIGEST_FUNC": ConfigMetadata(
        key="THUMBNAIL_DASHBOARD_DIGEST_FUNC",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "THUMBNAIL_ERROR_CACHE_TTL": ConfigMetadata(
        key="THUMBNAIL_ERROR_CACHE_TTL",
        type=int,
        default=86400,
        description="None",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "THUMBNAIL_EXECUTORS": ConfigMetadata(
        key="THUMBNAIL_EXECUTORS",
        type=list,
        default=[<ExecutorType.CURRENT_USER: 'current_user'>],
        description="configuration: from superset.tasks.types import ExecutorType, FixedExecutor THUMBNAIL_EXECUTORS = [FixedExecutor("admin")]",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "TIME_GRAIN_ADDONS": ConfigMetadata(
        key="TIME_GRAIN_ADDONS",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "TIME_GRAIN_ADDON_EXPRESSIONS": ConfigMetadata(
        key="TIME_GRAIN_ADDON_EXPRESSIONS",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "TIME_GRAIN_DENYLIST": ConfigMetadata(
        key="TIME_GRAIN_DENYLIST",
        type=list,
        default=[],
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "TIME_GRAIN_JOIN_COLUMN_PRODUCERS": ConfigMetadata(
        key="TIME_GRAIN_JOIN_COLUMN_PRODUCERS",
        type=dict,
        default={},
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "TIME_ROTATE_LOG_LEVEL": ConfigMetadata(
        key="TIME_ROTATE_LOG_LEVEL",
        type=int,
        default=20,
        description="None",
        category="logging",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "TRACKING_URL_TRANSFORMER": ConfigMetadata(
        key="TRACKING_URL_TRANSFORMER",
        type=function,
        default=function(),
        description="to your transformer function, e.g.: TRACKING_URL_TRANSFORMER = ( lambda url, query: url if is_fresh(query) else None ) pylint: disable-next=unnecessary-lambda-assignment",
        category="general",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<function instance>",
    ),

    "TROUBLESHOOTING_LINK": ConfigMetadata(
        key="TROUBLESHOOTING_LINK",
        type=str,
        default='',
        description="The link to a page containing common errors and their resolutions It will be appended at the bottom of sql_lab errors.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "TYPE_CHECKING": ConfigMetadata(
        key="TYPE_CHECKING",
        type=bool,
        default=False,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "UPLOADED_CSV_HIVE_NAMESPACE": ConfigMetadata(
        key="UPLOADED_CSV_HIVE_NAMESPACE",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "UPLOAD_CHUNK_SIZE": ConfigMetadata(
        key="UPLOAD_CHUNK_SIZE",
        type=int,
        default=4096,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "UPLOAD_FOLDER": ConfigMetadata(
        key="UPLOAD_FOLDER",
        type=str,
        default='/Users/max/code/superset/superset/static/uploads/',
        description="--------------------------------------------------- Image and file configuration --------------------------------------------------- The file upload folder, when using models with files",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "URL": ConfigMetadata(
        key="URL",
        type=type,
        default=type(),
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        serializable=False,
        doc_default="<type instance>",
    ),

    "USER_AGENT_FUNC": ConfigMetadata(
        key="USER_AGENT_FUNC",
        type=NoneType,
        default=None,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "VERSION_INFO_FILE": ConfigMetadata(
        key="VERSION_INFO_FILE",
        type=str,
        default='/Users/max/code/superset/superset/static/version_info.json',
        description="--------------------------------------------------------- Superset specific config ---------------------------------------------------------",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "VERSION_SHA": ConfigMetadata(
        key="VERSION_SHA",
        type=str,
        default='',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "VERSION_SHA_LENGTH": ConfigMetadata(
        key="VERSION_SHA_LENGTH",
        type=int,
        default=8,
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "VERSION_STRING": ConfigMetadata(
        key="VERSION_STRING",
        type=str,
        default='0.0.0-dev',
        description="version_info.json file may or may not be available, as it is generated on install via setup.py. In the event that we're actually running Superset, we will have already installed, therefore it WILL exist. When unit tests are running, however, it WILL NOT exist, so we fall back on reading package.json",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "VIZ_TYPE_DENYLIST": ConfigMetadata(
        key="VIZ_TYPE_DENYLIST",
        type=list,
        default=[],
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "WEBDRIVER_AUTH_FUNC": ConfigMetadata(
        key="WEBDRIVER_AUTH_FUNC",
        type=NoneType,
        default=None,
        description="An optional override to the default auth hook used to provide auth to the offline webdriver (when using Selenium) or browser context (when using Playwright - see PLAYWRIGHT_REPORTS_AND_THUMBNAILS feature flag)",
        category="security",
        impact="medium",
        requires_restart=True,
    ),

    "WEBDRIVER_BASEURL": ConfigMetadata(
        key="WEBDRIVER_BASEURL",
        type=str,
        default='http://0.0.0.0:8080/',
        description="The base URL to query for accessing the user interface",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "WEBDRIVER_BASEURL_USER_FRIENDLY": ConfigMetadata(
        key="WEBDRIVER_BASEURL_USER_FRIENDLY",
        type=str,
        default='http://0.0.0.0:8080/',
        description="The base URL for the email report hyperlinks.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "WEBDRIVER_CONFIGURATION": ConfigMetadata(
        key="WEBDRIVER_CONFIGURATION",
        type=dict,
        default={'options': {'capabilities': {}, 'preferences': {}, 'binary_location': ''}, 'service': {'log_output': '/dev/null', 'service_args': [], 'port': 0, 'env': {}}},
        description="Any config options to be passed as-is to the webdriver",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "WEBDRIVER_OPTION_ARGS": ConfigMetadata(
        key="WEBDRIVER_OPTION_ARGS",
        type=list,
        default=['--headless'],
        description="Additional args to be passed as arguments to the config object Note: If using Chrome, you'll want to add the "--marionette" arg.",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "WEBDRIVER_TYPE": ConfigMetadata(
        key="WEBDRIVER_TYPE",
        type=str,
        default='firefox',
        description="Requires: geckodriver and firefox installations Limitations: can be buggy at times chrome: Requires: headless chrome Limitations: unable to generate screenshots of elements",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "WEBDRIVER_WINDOW": ConfigMetadata(
        key="WEBDRIVER_WINDOW",
        type=dict,
        default={'dashboard': (1600, 2000), 'slice': (3000, 1200), 'pixel_density': 1},
        description="Window size - this will impact the rendering of the data",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "WELCOME_PAGE_LAST_TAB": ConfigMetadata(
        key="WELCOME_PAGE_LAST_TAB",
        type=str,
        default='all',
        description="None",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "WTF_CSRF_EXEMPT_LIST": ConfigMetadata(
        key="WTF_CSRF_EXEMPT_LIST",
        type=list,
        default=['superset.views.core.log', 'superset.views.core.explore_json', 'superset.charts.data.api.data', 'superset.dashboards.api.cache_dashboard_screenshot'],
        description="Add endpoints that need to be exempt from CSRF protection",
        category="general",
        impact="medium",
        requires_restart=False,
    ),

    "WTF_CSRF_TIME_LIMIT": ConfigMetadata(
        key="WTF_CSRF_TIME_LIMIT",
        type=int,
        default=604800,
        description="CSRF token timeout, set to None for a token that never expires",
        category="performance",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "ZIPPED_FILE_MAX_SIZE": ConfigMetadata(
        key="ZIPPED_FILE_MAX_SIZE",
        type=int,
        default=104857600,
        description="Max allowed size for a zipped file",
        category="general",
        impact="medium",
        requires_restart=False,
        min_value=1,
    ),

    "ZIP_FILE_MAX_COMPRESS_RATIO": ConfigMetadata(
        key="ZIP_FILE_MAX_COMPRESS_RATIO",
        type=float,
        default=200.0,
        description="Max allowed compression ratio for a zipped file",
        category="general",
        impact="medium",
        requires_restart=False,
    ),
