# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
description: Share of sales by product line as a labeled donut.
params:
  color_scheme: supersetColors
  donut: true
  groupby:
  - product_line
  innerRadius: 35
  show_legend: true
  label_type: percent
  labels_outside: false
  metric:
    aggregate: SUM
    column:
      column_name: sales
    expressionType: SIMPLE
    label: SUM(sales)
    optionName: metric_sales_pie
  number_format: SMART_NUMBER
  outerRadius: 55
  row_limit: 100
  show_labels: true
  show_labels_threshold: 5
  sort_by_metric: true
  time_range: No filter
  viz_type: pie
query_context: null
slice_name: Product Line Donut
uuid: 86e12cd7-1d2b-407b-ad3e-20f11ccbbcc2
version: 1.0.0
viz_type: pie
