# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 69e9de42-fe7f-4948-946a-f7913227aee8
description: World rural population share on a colored gauge.
params:
  adhoc_filters: []
  animation: false
  color_scheme: supersetColors
  end_angle: -45
  font_size: 14
  granularity_sqla: year
  interval_color_indices: 1,2,3
  intervals: 33,66,100
  max_val: 100
  metric:
    aggregate: AVG
    column:
      column_name: SP_RUR_TOTL_ZS
    expressionType: SIMPLE
    label: Rural share
    optionName: metric_rural_gauge
  min_val: 0
  number_format: .0f
  show_axis_tick: true
  show_pointer: true
  show_progress: false
  show_split_line: true
  split_number: 10
  start_angle: 225
  time_range: '2014-01-01 : 2014-01-02'
  value_formatter: '{value}%'
  viz_type: gauge_chart
query_context: null
slice_name: Rural Population Gauge
uuid: 3c504d55-0ad2-4b45-95d7-f857e800ee6a
version: 1.0.0
viz_type: gauge_chart
