import getInitialState from '../../../src/dashboard/reducers/getInitialState';

export const defaultFilters = {
  256: { region: [] },
  257: { country_name: ['United States'] },
};
export const regionFilter = {
  datasource: null,
  description: null,
  description_markeddown: '',
  edit_url: '/slicemodelview/edit/256',
  form_data: {
    datasource: '2__table',
    date_filter: false,
    filters: [
      {
        col: 'country_name',
        op: 'in',
        val: ['United States', 'France', 'Japan'],
      },
    ],
    granularity_sqla: null,
    groupby: ['region', 'country_name'],
    having: '',
    instant_filtering: true,
    metric: 'sum__SP_POP_TOTL',
    show_druid_time_granularity: false,
    show_druid_time_origin: false,
    show_sqla_time_column: false,
    show_sqla_time_granularity: false,
    since: '100 years ago',
    slice_id: 256,
    time_grain_sqla: null,
    until: 'now',
    viz_type: 'filter_box',
    where: '',
  },
  slice_id: 256,
  slice_name: 'Region Filters',
  slice_url:
    '/superset/explore/table/2/?form_data=%7B%22slice_id%22%3A%20256%7D',
};
export const countryFilter = {
  datasource: null,
  description: null,
  description_markeddown: '',
  edit_url: '/slicemodelview/edit/257',
  form_data: {
    datasource: '2__table',
    date_filter: false,
    filters: [],
    granularity_sqla: null,
    groupby: ['country_name'],
    having: '',
    instant_filtering: true,
    metric: 'sum__SP_POP_TOTL',
    show_druid_time_granularity: false,
    show_druid_time_origin: false,
    show_sqla_time_column: false,
    show_sqla_time_granularity: false,
    since: '100 years ago',
    slice_id: 257,
    time_grain_sqla: null,
    until: 'now',
    viz_type: 'filter_box',
    where: '',
  },
  slice_id: 257,
  slice_name: 'Country Filters',
  slice_url:
    '/superset/explore/table/2/?form_data=%7B%22slice_id%22%3A%20257%7D',
};
export const slice = {
  datasource: null,
  description: null,
  description_markeddown: '',
  edit_url: '/slicemodelview/edit/248',
  form_data: {
    annotation_layers: [],
    bottom_margin: 'auto',
    color_scheme: 'bnbColors',
    contribution: false,
    datasource: '2__table',
    filters: [],
    granularity_sqla: null,
    groupby: [],
    having: '',
    left_margin: 'auto',
    limit: 50,
    line_interpolation: 'linear',
    metrics: ['sum__SP_POP_TOTL'],
    num_period_compare: '',
    order_desc: true,
    period_ratio_type: 'growth',
    resample_fillmethod: null,
    resample_how: null,
    resample_rule: null,
    rich_tooltip: true,
    rolling_type: 'None',
    show_brush: false,
    show_legend: true,
    show_markers: false,
    since: '1961-01-01T00:00:00',
    slice_id: 248,
    time_compare: null,
    time_grain_sqla: null,
    timeseries_limit_metric: null,
    until: '2014-12-31T00:00:00',
    viz_type: 'line',
    where: '',
    x_axis_format: 'smart_date',
    x_axis_label: '',
    x_axis_showminmax: true,
    y_axis_bounds: [null, null],
    y_axis_format: '.3s',
    y_axis_label: '',
    y_axis_showminmax: true,
    y_log_scale: false,
  },
  slice_id: 248,
  slice_name: 'Filtered Population',
  slice_url:
    '/superset/explore/table/2/?form_data=%7B%22slice_id%22%3A%20248%7D',
};

const mockDashboardData = {
  css: '',
  dash_edit_perm: true,
  dash_save_perm: true,
  dashboard_title: 'Births',
  id: 2,
  metadata: {
    default_filters: JSON.stringify(defaultFilters),
    filter_immune_slices: [256],
    timed_refresh_immune_slices: [],
    filter_immune_slice_fields: {},
    expanded_slices: {},
  },
  position_json: [
    {
      size_x: 4,
      slice_id: '256',
      row: 0,
      size_y: 4,
      col: 5,
    },
    {
      size_x: 4,
      slice_id: '248',
      row: 0,
      size_y: 4,
      col: 1,
    },
  ],
  slug: 'births',
  slices: [regionFilter, slice, countryFilter],
  standalone_mode: false,
};
export const {
  dashboardState,
  dashboardInfo,
  charts,
  datasources,
  sliceEntities,
  dashboardLayout,
} = getInitialState({
  common: {},
  dashboard_data: mockDashboardData,
  datasources: {},
  user_id: '1',
});

export const mockSliceEntities = {
  slices: {
    '127': {
      slice_id: 127,
      slice_url: '/superset/explore/?form_data=%7B%22slice_id%22%3A%20127%7D',
      slice_name: 'Region Filter',
      form_data: {},
      edit_url: '/slicemodelview/edit/127',
      viz_type: 'filter_box',
      datasource: '2__table',
      description: null,
      description_markeddown: '',
      modified: '23 hours ago',
      changed_on: 1529453332615,
    },
    '128': {
      slice_id: 128,
      slice_url: '/superset/explore/?form_data=%7B%22slice_id%22%3A%20128%7D',
      slice_name: "World's Population",
      form_data: {},
      edit_url: '/slicemodelview/edit/128',
      viz_type: 'big_number',
      datasource: '2__table',
      description: null,
      description_markeddown: '',
      modified: '23 hours ago',
      changed_on: 1529453332628,
    },
    '129': {
      slice_id: 129,
      slice_url: '/superset/explore/?form_data=%7B%22slice_id%22%3A%20129%7D',
      slice_name: 'Most Populated Countries',
      form_data: {},
      edit_url: '/slicemodelview/edit/129',
      viz_type: 'table',
      datasource: '2__table',
      description: null,
      description_markeddown: '',
      modified: '23 hours ago',
      changed_on: 1529453332637,
    },
    '130': {
      slice_id: 130,
      slice_url: '/superset/explore/?form_data=%7B%22slice_id%22%3A%20130%7D',
      slice_name: 'Growth Rate',
      form_data: {},
      edit_url: '/slicemodelview/edit/130',
      viz_type: 'line',
      datasource: '2__table',
      description: null,
      description_markeddown: '',
      modified: '23 hours ago',
      changed_on: 1529453332645,
    },
    '131': {
      slice_id: 131,
      slice_url: '/superset/explore/?form_data=%7B%22slice_id%22%3A%20131%7D',
      slice_name: '% Rural',
      form_data: {},
      edit_url: '/slicemodelview/edit/131',
      viz_type: 'world_map',
      datasource: '2__table',
      description: null,
      description_markeddown: '',
      modified: '23 hours ago',
      changed_on: 1529453332654,
    },
    '132': {
      slice_id: 132,
      slice_url: '/superset/explore/?form_data=%7B%22slice_id%22%3A%20132%7D',
      slice_name: 'Life Expectancy VS Rural %',
      form_data: {},
      edit_url: '/slicemodelview/edit/132',
      viz_type: 'bubble',
      datasource: '2__table',
      description: null,
      description_markeddown: '',
      modified: '23 hours ago',
      changed_on: 1529453332663,
    },
    '133': {
      slice_id: 133,
      slice_url: '/superset/explore/?form_data=%7B%22slice_id%22%3A%20133%7D',
      slice_name: 'Rural Breakdown',
      form_data: {},
      edit_url: '/slicemodelview/edit/133',
      viz_type: 'sunburst',
      datasource: '2__table',
      description: null,
      description_markeddown: '',
      modified: '23 hours ago',
      changed_on: 1529453332673,
    },
    '134': {
      slice_id: 134,
      slice_url: '/superset/explore/?form_data=%7B%22slice_id%22%3A%20134%7D',
      slice_name: "World's Pop Growth",
      form_data: {},
      edit_url: '/slicemodelview/edit/134',
      viz_type: 'area',
      datasource: '2__table',
      description: null,
      description_markeddown: '',
      modified: '23 hours ago',
      changed_on: 1529453332680,
    },
    '135': {
      slice_id: 135,
      slice_url: '/superset/explore/?form_data=%7B%22slice_id%22%3A%20135%7D',
      slice_name: 'Box plot',
      form_data: {},
      edit_url: '/slicemodelview/edit/135',
      viz_type: 'box_plot',
      datasource: '2__table',
      description: null,
      description_markeddown: '',
      modified: '23 hours ago',
      changed_on: 1529453332688,
    },
    '136': {
      slice_id: 136,
      slice_url: '/superset/explore/?form_data=%7B%22slice_id%22%3A%20136%7D',
      slice_name: 'Treemap',
      form_data: {},
      edit_url: '/slicemodelview/edit/136',
      viz_type: 'treemap',
      datasource: '2__table',
      description: null,
      description_markeddown: '',
      modified: '23 hours ago',
      changed_on: 1529453332700,
    },
  },
  isLoading: false,
  errorMessage: null,
  lastUpdated: 0,
};
