# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Local extensions file watcher for development mode."""

from __future__ import annotations

import logging
import os
import threading
import time
from pathlib import Path
from typing import Any

from flask import Flask

logger = logging.getLogger(__name__)

# Sentinel file Flask watches via --extra-files.  Touching it on a real change
# triggers a server reload without depending on cwd or the location of any
# Python source file.
RELOAD_TRIGGER = Path(__file__).resolve().parent / ".reload_trigger"

# Guard to prevent multiple initializations
_watcher_initialized = False
_watcher_lock = threading.Lock()


def _get_file_handler_class() -> Any:  # noqa: C901
    """Get the file handler class, importing watchdog only when needed."""
    try:
        import hashlib

        from watchdog.events import (
            FileCreatedEvent,
            FileModifiedEvent,
            FileMovedEvent,
            FileSystemEventHandler,
        )

        class LocalExtensionFileHandler(FileSystemEventHandler):
            """Custom file system event handler for LOCAL_EXTENSIONS directories.

            Only reacts to genuine content changes (create / modify / move) in the
            dist directory, verified by comparing a SHA-256 of the file's content.
            This avoids the Docker VirtioFS / osxfs problem where reading a file
            generates inotify events that watchdog surfaces as modifications.
            """

            def __init__(self) -> None:
                super().__init__()
                # sha256 of last-seen content, keyed by absolute path
                self._file_hashes: dict[str, str] = {}
                # Deduplicate: only trigger once per second across all files
                self._last_trigger: float = 0.0
                self._lock = threading.Lock()

            # ── helpers ──────────────────────────────────────────────────────

            @staticmethod
            def _sha256(path: str) -> str | None:
                try:
                    with open(path, "rb") as fh:
                        return hashlib.sha256(fh.read()).hexdigest()
                except OSError:
                    return None

            def _content_changed(self, path: str) -> bool:
                """Return True only when the file's content differs from last seen.

                The first time a path is observed its hash is stored as the baseline
                and False is returned — that event is a 'first-seen', not a change.
                Only a subsequent event where the digest differs from the baseline
                is treated as a genuine content change.
                """
                digest = self._sha256(path)
                if digest is None:
                    return False
                old_digest = self._file_hashes.get(path)
                self._file_hashes[path] = digest
                if old_digest is None:
                    # First observation — record baseline, do not trigger restart.
                    return False
                return old_digest != digest

            # ── event handler ─────────────────────────────────────────────────

            def on_any_event(self, event: Any) -> None:
                """Handle file system events in the watched directories."""
                if event.is_directory:
                    return

                # Only react to true write events; skip access / close / open etc.
                if not isinstance(
                    event, (FileCreatedEvent, FileModifiedEvent, FileMovedEvent)
                ):
                    return

                # Only care about files inside a `dist` directory
                src = getattr(event, "src_path", None)
                if not isinstance(src, str) or "dist" not in Path(src).parts:
                    return

                # Verify the file content actually changed to ignore spurious
                # inotify events generated by Docker bind-mount reads.
                if not self._content_changed(src):
                    return

                # Debounce: one restart per second max, regardless of how many
                # files webpack writes simultaneously.
                now = time.monotonic()
                with self._lock:
                    if now - self._last_trigger < 1.0:
                        return
                    self._last_trigger = now

                logger.info(
                    "File change detected in LOCAL_EXTENSIONS: %s", event.src_path
                )

                # Touch the dedicated reload-trigger sentinel file.
                # Flask watches this via --extra-files; it is never read by Python
                # so Docker VirtioFS will not generate spurious inotify events on it.
                logger.info("Triggering restart by touching %s", RELOAD_TRIGGER)
                os.utime(RELOAD_TRIGGER, (time.time(), time.time()))

        return LocalExtensionFileHandler
    except ImportError:
        logger.warning("watchdog not installed, LOCAL_EXTENSIONS watcher disabled")
        return None


def setup_local_extensions_watcher(app: Flask) -> None:  # noqa: C901
    """Set up file watcher for LOCAL_EXTENSIONS directories."""
    global _watcher_initialized

    # Prevent multiple initializations
    with _watcher_lock:
        if _watcher_initialized:
            return
        _watcher_initialized = True

    # Only set up watcher in debug mode or when Flask reloader is enabled
    if not (app.debug or app.config.get("FLASK_USE_RELOAD", False)):
        return

    # Check if we're running under Flask's reloader to avoid conflicts
    if os.environ.get("WERKZEUG_RUN_MAIN") == "true":
        return

    local_extensions = app.config.get("LOCAL_EXTENSIONS", [])
    if not local_extensions:
        return

    # Try to import watchdog and get handler class
    handler_class = _get_file_handler_class()
    if not handler_class:
        return

    # Collect extension directories to watch
    # We watch the parent extension directory instead of just dist/
    # to avoid the observer stopping when dist/ is deleted/recreated
    # Use a set to avoid duplicate entries
    watch_dirs: set[str] = set()
    for ext_path in local_extensions:
        if not ext_path:
            continue

        ext_path = Path(ext_path).resolve()
        if not ext_path.exists():
            logger.warning("LOCAL_EXTENSIONS path does not exist: %s", ext_path)
            continue

        # Ensure we're watching a directory, not a file
        if ext_path.is_file():
            logger.warning(
                "LOCAL_EXTENSIONS path is a file, not a directory: %s. "
                "Provide the extension directory path instead.",
                ext_path,
            )
            continue

        if not ext_path.is_dir():
            logger.warning("LOCAL_EXTENSIONS path is not a directory: %s", ext_path)
            continue

        # Add to set (automatically handles duplicates)
        watch_dir_str = str(ext_path)
        if watch_dir_str not in watch_dirs:
            watch_dirs.add(watch_dir_str)
            logger.info("Watching LOCAL_EXTENSIONS directory: %s", ext_path)

    if not watch_dirs:
        return

    # Ensure the sentinel exists so os.utime() and Flask's --extra-files watcher
    # both have a real path to operate on.
    try:
        RELOAD_TRIGGER.touch(exist_ok=True)
    except OSError as e:
        logger.warning("Could not create reload trigger %s: %s", RELOAD_TRIGGER, e)
        return

    try:
        from watchdog.observers import Observer

        # Set up and start the file watcher
        event_handler = handler_class()
        observer = Observer()

        for watch_dir in watch_dirs:
            try:
                observer.schedule(event_handler, watch_dir, recursive=True)
            except Exception as e:
                logger.warning("Failed to watch directory %s: %s", watch_dir, e)
                continue

        observer.daemon = True
        observer.start()

        logger.info(
            "LOCAL_EXTENSIONS file watcher started for %s directories",  # noqa: E501
            len(watch_dirs),
        )

    except Exception as e:
        logger.error("Failed to start LOCAL_EXTENSIONS file watcher: %s", e)


def start_local_extensions_watcher_thread(app: Flask) -> None:
    """Start the LOCAL_EXTENSIONS file watcher in a daemon thread."""
    # Start setup in daemon thread if we're in main thread
    if threading.current_thread() is threading.main_thread():
        threading.Thread(
            target=lambda: setup_local_extensions_watcher(app), daemon=True
        ).start()
