name: Validate All GitHub Actions

on:
  push:
    branches:
      - "master"
      - "[0-9].[0-9]*"
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:

  validate-all-ghas:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install -g @action-validator/core @action-validator/cli --save-dev

      - name: Run Script
        run: bash .github/workflows/github-action-validator.sh
